### ISSUE TITLE
Start a previously stopped/kept container

### ISSUE THREAD

**Issue by ShahinKordasti** [fabric8io/docker-maven-plugin#1029]
### Description

Hello! I have a maven build where two different modules are using the same DB so I would like to re-use the docker container started/stopped by one module in another. But if I set the naming strategy to 'alias' and then add start/stop hooks for both modules, then the modules running first will start and stop just fine but the second module gives me the error msg: 
```
[ERROR] DOCKER> Error occurred during container startup, shutting down...
[ERROR] DOCKER> I/O Error [Unable to create container for [mysql:5.7] : Conflict. The container name "/lw-mysqldb" is already in use by container "e3d2ca79933809adf587fa89d33515686d9e2157c08b3034264d21f86fb7004b". You have to remove (or rename) that container to be able to reuse that name. (Conflict: 409)]`
```
Is this something not supported by the plugin or am I not configuring this properly?

relevant pom.xmls:
parent pom plugin management:
``` 
<plugin>
    <groupId>io.fabric8</groupId>
    <artifactId>docker-maven-plugin</artifactId>
    <version>0.25.2</version>
    <extensions>true</extensions>
    <configuration>
        <verbose>true</verbose>
        <skip>${skip.integration.tests}</skip>
        <images>
            <image>
                <alias>lw-mysqldb</alias>
                <name>mysql:5.7</name>
                <run>
                    <namingStrategy>alias</namingStrategy>
                    <wait>
                        <time>10000</time>
                    </wait>
                    <env>
                        <MYSQL_ROOT_PASSWORD>...</MYSQL_ROOT_PASSWORD>
                        <MYSQL_DATABASE>...</MYSQL_DATABASE>
                        <MYSQL_USER>...</MYSQL_USER>
                        <MYSQL_PASSWORD>...</MYSQL_PASSWORD>
                    </env>
                    <ports>
                        <port>3307:3306</port>
                    </ports>
                    <log><enabled>true</enabled></log>
                </run>
            </image>
        </images>
    </configuration>
</plugin>
``` 
child 1 pom.xml
``` 
 <plugin>
    <groupId>io.fabric8</groupId>
    <artifactId>docker-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>docker:start</id>
            <phase>pre-integration-test</phase>
            <goals>
                <goal>start</goal>
            </goals>
        </execution>
        <execution>
            <id>docker:stop</id>
            <phase>post-integration-test</phase>
            <goals>
                <goal>stop</goal>
            </goals>
            <configuration>
                <keepContainer>true</keepContainer>
            </configuration>
        </execution>
    </executions>
</plugin>
``` 
child 2 pom.xml
``` 
 <plugin>
    <groupId>io.fabric8</groupId>
    <artifactId>docker-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>docker:start</id>
            <phase>pre-integration-test</phase>
            <goals>
                <goal>start</goal>
            </goals>
        </execution>
        <execution>
            <id>docker:stop</id>
            <phase>post-integration-test</phase>
            <goals>
                <goal>stop</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by rhuss** [comment]
Sorry, restarting container is currently not supported. It will always start a new container from an image and since the container already exists with the fixed name, it refuses to start.

But my question is, why would you want to do this ? I don't see any reason why the container should be the same and not two copies from the same image.

Could you elaborate a bit on your use case ?

**Comment by rhuss** [comment]
> However being able to use the same integration database for two different modules in a Maven build I guess would be a quite common use case no?

I would argue against it as it introduces a subtle dependencies between those modules as the first one can modify the database in such ways that in influences the run of the second. Actually, on of the main benefits of containers is that you start afresh from a defined state and throw away the containers afterwards.

So your solution to create an _image_ with a test fixture in the database and creating two containers for it for each module respectively is indeed not only a workaround but would be my preferred solution to avoid implicit dependencies and possibly flaky tests. You don't even have to push it to a registry, just create the image in a dedicated submodule on the docker daemon itself before running the tests.

I'm not sure we should promote the reuse of containers at all. It really opens a can of worms, and I dare to point users of d-m-p into this direction.

**Comment by ShahinKordasti** [comment]
Ok fair enough. We are going with the docker image with test fixtures and, as you say, it seems like a more robust solution.
