### ISSUE TITLE
docker:build does not support 'network' option

### ISSUE THREAD

**Issue by KedneckInc** [fabric8io/docker-maven-plugin#1030]
### Description

The command `docker build` supports the `--network=<name>` option, but the docker:build configuration in the plugin does not.

### Info

* d-m-p version : 0.23.0

* Maven version (`mvn -v`) :
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.8.0_152, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_152/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-862.3.2.el7.x86_64", arch: "amd64", family: "unix"
```
* Docker version : Docker version 1.13.1, build 94f4240/1.13.1

* If it's a feature request, what is your use case :

There is an issue with the corporate VPN that I must use, where if you use the SSL version, everything works as expected; but if you use the IPSec version, the standard docker build process via the maven plugin fails because it apparently cannot receive responses from the remote host.  This despite multiple attempts at turning off  firewalls, adding the `iptables -P FORWARD ACCEPT` command, restarting docker, wiping out docker0 and restarting docker again, and again, and again, etc.

Doing the build manually, the same thing happens, until I add the `--network=host` option to the `docker build` command; then it works.

Now, the 'obvious' solution is to either (a) use the SSL version of the VPN, or (b) figure out what the network settings are needed to make it work with the IPSec version.  As to (a), I've been politely requested to not use that version of the VPN [for a really silly reason, but I can't make them fix it], and for (b) I'm not enough of a network guru to figure out what the correct settings are.

What I can do, is look at the docker build command's options, see the 'network' setting, and use it...

Except it isn't supported by docker-maven-plugin.

Please?

**Comment by EricThieme** [comment]
I had the same problem yesterday... and to be honest a few times before with our internal company proxy setup. To prevent passwords from being added as build arguments to the final image (you would see them with docker history <imagename>) we use a local proxy and provide it in an extra docker network to each build. That works perfectly on a console but currently not with the plugin.

@KedneckInc: If you want a quick workaround you can help yourself quite easy. Checkout the project and modify src/main/java/io/fabric8/maven/docker/access/UrlBuilder.java. If you have a look in the REST documentation of docker https://docs.docker.com/engine/api/v1.27/#operation/ImageBuild you will see that the Rest call requires the URL to contain networkmode=host (for your case). 

Modify  Builder.build() and build the plugin on your own. 
``ret.append("?");
ret.append("networkmode=host&");``

Not a solution for everyone, but an interim solution for you in your case until the feature was implemented.

**Comment by EricThieme** [comment]
@rhuss I have already created a company internal request to provide a pull request. I will start once I get the clearance. ... and don't ask :D

**Comment by fforloff** [comment]
Any update on this issue?

**Comment by rhuss** [comment]
Nope, not from my side yet. But still happy to help integrating PRs.

**Comment by albertschwarzkopf** [comment]
@rhuss Do you have any updates on this issue?

**Comment by rohanKanojia** [comment]
Shall I look into this?

**Comment by albertschwarzkopf** [comment]
This would be nice. Thank you!

**Comment by rohanKanojia** [comment]
cool, let me look into this issue this weekend.
