### ISSUE TITLE
Unable to mvn deploy - error on org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy

### ISSUE THREAD

**Issue by soickm** [fabric8io/docker-maven-plugin#1043]
### Description

Trying run any of the examples I keep getting the same message:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project mongodb: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]

### Info

* d-m-p version :
* Maven version (`mvn -v`) :
```
Maven home: /Applications/apache-maven-3.5.3
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"
```
* Docker version :

Docker version 18.03.0-ce, build 0520e24

* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

Here is a simple pom.xml

<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.spotify.it</groupId>
    <artifactId>mongodb</artifactId>
    <version>2.0.0</version>

    <description>MongoDB for Music app.</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <version>1.3.6</version>
                <executions>
                    <execution>
                        <id>default</id>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

Dockerfile

# MongoDB image with host-based data volume

FROM mongo:latest

VOLUME ["/data/db"]
WORKDIR /data
CMD ["mongod", "--smallfiles"]

**Comment by rhuss** [comment]
1. You issue has todo with the configuration of your pom.xml when using `deploy`. Nothing related to build docker images.

2. You pom.xml use the dockerfile-maven-plugin from spotify which is a different beast.

**Comment by soickm** [comment]
Sorry about that - I was going back and forth between yours and spotify's to find one that better suited my needs.
