### ISSUE TITLE
Specify which client is too old when reporting error

### ISSUE THREAD

**Issue by apupier** [fabric8io/docker-maven-plugin#1058]
it was using the fabric8-maven-plugin but maintainers asked me to report it on docker-maven-plugin too https://github.com/fabric8io/fabric8-maven-plugin/issues/1200#issuecomment-408209899

### Description

[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.33.fuse-000007:build (build-image) on project karaf-camel-log: Failed to execute the build: Error while trying to build the image: Unable to check image [jboss-fuse-7/fuse-karaf-openshift:1.0] : client version 1.18 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version (Bad Request: 400) -> [Help 1]

https://github.com/fabric8io/fabric8-maven-plugin/issues/1200

### Info

* d-m-p version :
* Maven version (`mvn -v`) :
```

```
* Docker version :
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rhuss** [comment]
Opened already a followup issue at #1060 Lets move over there ...

thanks for reporting, @apupier
