### ISSUE TITLE
Smarter API version handling

### ISSUE THREAD

**Issue by rhuss** [fabric8io/docker-maven-plugin#1060]
### Description

As described in https://github.com/fabric8io/fabric8-maven-plugin/issues/1200 the minimal version 1.18 used by d-m-p gets rejected for newer Docker daemons (e.g. those having 1.35). 

Actually we are compliant with the newer versions (its a minimal version after all), so I see two solutions:

* If possible, we don't send an API version. However when we use features which require a minimal version of 1.21 this still will still break.

* We send a test request to the Daemon, and check whether it succeeds. In the return response there's a header `Api-Version:` which holds the actual Docker daemon version. So if this test request because of a too low version, we can just pick up that version and use it as minimal version for us.

**Comment by rohanKanojia** [comment]
@rhuss : Could you please give some code pointer related to this?

**Comment by rhuss** [comment]
During initialization we check which features are used and then calculate the minimal version required: https://github.com/rhuss/docker-maven-plugin/blob/ccb3adb766c3b2f94f4f624e189f57478b4768ce/src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java#L215

If nothing special is used its, the default of 1.18 for now.The docker client will be created with this version https://github.com/rhuss/docker-maven-plugin/blob/9e59f3501667182a27fda321cd38392839892418/src/main/java/io/fabric8/maven/docker/service/DockerAccessFactory.java#L38-L39

Then, for each request this version is send to the daemon https://github.com/rhuss/docker-maven-plugin/blob/ee113cd7d6291d37c51ff6b9b68a5d63357244fb/src/main/java/io/fabric8/maven/docker/access/UrlBuilder.java#L209

Actually when we get back an error that indicates that's a version mismatch like in the first post, we should adapt the minimal version to that provided in the response header.

Alternatively, and actually i like that better, we could send a single request to some version endpoint and pick up the api version. If this version is larger then our minimal version we just use that for our minimal version. otherwise we throw an error that we can't talk to the daemon (as our minimal version is higher of what the daemon provides).

**Comment by rohanKanojia** [comment]
@JoshLitt : ah, apologies for the inconvenience. You're right, this change wasn't supposed to break backward compatibility. We should also handle the case when there is no apiVersion specified in header

**Comment by rhuss** [comment]
@JoshLitt should be fixed now with the next release (see later PR merged)

**Comment by dantran** [comment]
I just ran into same issue with d-m-p 0.28 to 0.30 running against latest docker windows

How do fix this? my apology for not seeing the obvious in this discussion
