### ISSUE TITLE
Credentials helper not working with new docker versions

### ISSUE THREAD

**Issue by furti** [fabric8io/docker-maven-plugin#1068]
### Description
With the newest docker version the credentials helper seems to fail to get the credentials even when logged in to docker with `docker login` before.

### Info

Running `mvn docker:push -Ddocker.tag=$USERNAME -Ddocker.verbose=true -X` on the console gives me this output:

```
...
[INFO] DOCKER> Credentials helper reply for "docker-credential-wincred" is 0.6.0
[DEBUG] DOCKER> AuthConfig: credentials from credential helper/store docker-credential-wincred version 0.6.0
[DEBUG] DOCKER> AuthConfig: no credentials found
...
Caused by: io.fabric8.maven.docker.access.DockerAccessException: no basic auth credentials
```

I think the problem is the following:
In io.fabric8.maven.docker.util.CredentialHelperClient.getAuthConfig(..) Line 41 you prefix the registry with "https://" by default. Maybe the older versions needed this. But the new docker version does not need the prefix anymore.

With prefix
```
$ echo https://my.registry.com | docker-credential-wincred get
credentials not found in native keychain
```

Without prefix
```
$ echo my.registry.com | docker-credential-wincred get
{"ServerURL":"my.registry.com","Username":"user","Secret":"password"}
```

* d-m-p version : 0.26.1
* Maven version (`mvn -v`) :
```
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T18:37:52+01:00)
Java version: 1.8.0_121, vendor: Oracle Corporation
Default locale: de_AT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"
```
* Docker version : Docker version 18.06.0-ce, build 0ffa825

**Comment by thedikiy** [comment]
To workaround this, I had to use [store](https://docs.docker.com/engine/reference/commandline/login/#credential-helper-protocol) command specifying https://docker.mypath.net explicitly.
The thing is that even if you are using docker login command with "https://" in server url, the entry will be saved without protocol. 
Ubuntu 16.04 docker-credential-pass

**Comment by rhuss** [comment]
@furti thanks for reporting, and sorry for the delay.

I think we should try both, with prefix and without. I'm a bit busy these days, so if you would like to tackle this and submit a PR, that would be awesome. Otherwise I'm going to tackle this next weeks.

**Comment by jakub-bochenski** [comment]
I think we hit this problem too.
```
[DEBUG] DOCKER> AuthConfig: credentials from credential helper/store docker-credential-wincred version 0.6.0
[DEBUG] DOCKER> AuthConfig: no credentials found
```

A workaround we used was to disable the credentials helper and just store the auth data in config.json

**Comment by rhuss** [comment]
Can you please check version 0.27.1 where I added a fix for this ?

**Comment by jakub-bochenski** [comment]
Thanks, it worked with 0.27.1

**Comment by rhuss** [comment]
Cool, thanks for the feedback!

**Comment by furti** [comment]
Sorry for the late reply. Unfortunately had no time to test this until now. :/

Tested it right now and it also works for me now :)
