### ISSUE TITLE
[0.27.2] portPropertyFile not written anymore

### ISSUE THREAD

**Issue by mixaaaa** [fabric8io/docker-maven-plugin#1112]
### Description

After upgrading to newer d-m-p version (0.26.1 -> 0.27.2) the _portPropertyFile_-property is not working anymore. By checking change logs and issues we did not really found an explanation why this failure happens. We used following standard configuration.

```
<configuration>
    <portPropertyFile>${project.basedir}/src/test/resources/ports.properties</portPropertyFile>
    <images>
        <image>
            <name>test-db</name>
            <registry>vm-test:443</registry>
            <alias>dockerfile</alias>
            <build>
                <dockerFileDir>${project.basedir}/src/test/docker</dockerFileDir>
            </build>
            <run>
                <ports>
                    <port>host.port:5432</port>
                </ports>
                <wait>
                    <time>5000</time>
                </wait>
            </run>
        </image>
    </images>
</configuration>
```

Thanks in advance,
Uwe

### Info

* d-m-p version : 0.26.1 -> 0.27.2
* Maven version (`mvn -v`) : Apache Maven 3.3.9
* Docker version :
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
* If it's a bug, how to reproduce :
just change the version ;)

**Comment by rhuss** [comment]
Thanks for the report, really looks like a regression. I'm trying to jump on that asap.

**Comment by JesperTerkelsen** [comment]
👍

**Comment by vap78** [comment]
Hi

any update here? This is still an issue in 0.30.0.

Best regards
Vasil

**Comment by rhuss** [comment]
Nope, not yet. Sorry. @rohanKanojia do you have some spare cycles to look into this ?

**Comment by rohanKanojia** [comment]
oh, okay. Let me try to look into this.
