### ISSUE TITLE
Add support for cachefrom

### ISSUE THREAD

**Issue by llowrey** [fabric8io/docker-maven-plugin#1132]
Adding support for `cachefrom` should improve build time when running in a CI DinD environment. This field is supported as of API v1.25. 

The POM configuration block should take a list of image names, possibly as one comma delimited string. The `cachefrom` field would then be added to the build request as a JSON array of strings.

Ideally, the build process would pull each image before submitting the image build request.

**Comment by pbillen** [comment]
+1 for this

Typical usage of this flag can be found on https://github.com/spotify/dockerfile-maven/issues/202#issuecomment-417944349.

**Comment by rhuss** [comment]
I agree that this makes much sense. Anyone fancy to add this ? Shouldn't be hard and I could help in ramp up.

**Comment by llowrey** [comment]
I'm not sure this is testable. IMO the only way to verify this is to inspect the JSON sent to docker but I don't see a way to do that. Do you have a way to capture the JSON?

**Comment by llowrey** [comment]
I made an attempt at implementing this feature (PR #1139). I can see (in docker.log) that the cachefrom arg is being passed and the api version is now v1.25 instead of v1.24 but I can't tell if docker is actually acting on it. Any ideas for how to verify that it's actually working?
