### ISSUE TITLE
wait/healthcheck does not work properly

### ISSUE THREAD

**Issue by burtsevyg** [fabric8io/docker-maven-plugin#1133]
### Description
When I start container wait/healthy don't use timeout/interval/retries configuration from image and after 17 tries in 10 seconds it failed build.
### Info
I use oracle db image:
https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/Dockerfile
healthcheck from github:
`HEALTHCHECK --interval=1m --start-period=5m \
   CMD "$ORACLE_BASE/$CHECK_DB_FILE" >/dev/null || exit 1`

* d-m-p version : 0.31.0
* Maven version (`mvn -v`) : 3.6.1
* Docker version : 1.13.1 & 18.09.9
* If it's a bug, how to reproduce : 
Start any image with healthcheck and wait healthy.

**Comment by burtsevyg** [comment]
Strange but I can not reproduce this problem now. All work as expected.

**Comment by burtsevyg** [comment]
I think that I can reproduce this issue. If packaging is war health check does not work.

For jar:
"db": Start container a29d62862d77
"db": Waiting to become healthy
"db": Waited on healthcheck '"CMD-SHELL", "\"$ORACLE_BASE/$CHECK_DB_FILE\" >/dev/null || exit 1"' 30422 ms

For war:
"db": Start container 5dfbcf85ee54
"db": Pausing for 300000 ms

I check for 0.27.2 and 0.28.0 versions.
My pom.xml:
```
...
       <wait>
           <exec>
               <postStart>/maven/postStart.sh</postStart>
               <breakOnError>true</breakOnError>
           </exec>
           <healthy>true</healthy>
           <time>${docker.wait.timeout}</time>
       </wait>
...
```

**Comment by burtsevyg** [comment]
Issue reproduced only on rhel docker 1.13.1. On Docker version 17.05.0-ce, build 89658be issue didn't reproduce.

**Comment by SourMonk89** [comment]
I can also reproduce this behavior. My healthcheck definition:

```
<healthCheck>
     <interval>10s</interval>
     <startPeriod>3m</startPeriod>
     <timeout>30s</timeout>
     <cmd>/opt/jboss/wildfly_healthcheck.sh</cmd>
</healthCheck>
```

And then when starting the container, it always errors out after 10-12 seconds:
```
[ERROR] DOCKER> [fwa_wildfly:9.0.2.Final]: Timeout after 10129 ms while waiting on healthcheck '"CMD-SHELL", ". /opt/jboss/wildfly_healthcheck.sh"'
[ERROR] DOCKER> Error occurred during container startup, shutting down...
042116> *** JBossAS process (92) received TERM signal ***
042116> 15:47:38,403 INFO  [org.jboss.as.server] (Thread-2) WFLYSRV0220: Server shutdown has been requested.
```

My base image is jboss/wildfly:9.0.2.Final and I am using version 0.30.0 of the docker-maven-plugin and Docker version is 18.06.0-ce, build 0ffa825.

**Comment by yaitskov** [comment]
I am also in trouble

**Comment by rhuss** [comment]
> I also tried moving the healthcheck out of my pom.xml and into my Dockerfile, but still got the error.

If this is the case, then it look strongly like that it is a Docker issue when calling this command. Does this shell script work in time when running the image manually ? For me it looks that the check itself takes longer than 10s to execute.

**Comment by burtsevyg** [comment]
I don't point any script I use
```<healthy>true</healthy>```
docker ps show that container in healthy status, but maven break the build.

**Comment by burtsevyg** [comment]
Also I can't see any log in docker container which running from dmp throught Jenkins. May be it problem related only for oracle image.

**Comment by Khalil-Bouzekri** [comment]
I have also the same problem, maven fails after 10s or so. I think this issue should be re-opened.

docker-maven-plugin version : 0.32.0
docker version : 19.03.9

Here is my config in pom.xml:

`<wait>
  <healthy>true</healthy>
</wait>`

and in my Dockerfile:

`HEALTHCHECK --interval=10s --start-period=1m --timeout=3s --retries=3 CMD ps -ef | grep "java -jar \/home\/skevt\/uc-map.*" || exit 1`

Finally the error that causes maven to fail:

`[ERROR] DOCKER> I/O Error [[uc-map:latest] "uc-map": Timeout after 10050 ms while waiting on healthcheck '"CMD-SHELL", "ps -ef | grep \"java -jar \\/home\\/skevt\\/uc-map.*\" || exit 1"']`

Without the "wait" condition, the deployment goes as axpected and the container turns to healthy after 1m or so

**Comment by Khalil-Bouzekri** [comment]
It works now for me if I specify "time" as follows: 

`<wait>` 
 `   <healthy>true</healthy>`
`    <time>180000</time> `
`</wait>`

3min is enough time for my service to be up and healthy.

However it would be much better not to have to specify "time"
