### ISSUE TITLE
Building custom image does not work - reproduced with samples/healthcheck

### ISSUE THREAD

**Issue by gsmet** [fabric8io/docker-maven-plugin#1138]
I tried to build a custom image to include a healthcheck. Unfortunately, it does not work as Docker tries to get the image from the registry and then fails.

It's reproducible with the samples/healthcheck here: https://github.com/fabric8io/docker-maven-plugin/tree/master/samples/healthcheck .

Just go to this directory then use `mvn clean install`.

You end up with:
```
[INFO] --- docker-maven-plugin:0.27-SNAPSHOT:start (start) @ dmp-sample-healthcheck ---
[INFO] DOCKER> Trying to pull repository docker.io/library/busybox1 ... 
[INFO] DOCKER> Trying to pull repository registry.fedoraproject.org/busybox1 ... 
[INFO] DOCKER> Trying to pull repository quay.io/busybox1 ... 
[INFO] DOCKER> Trying to pull repository registry.access.redhat.com/busybox1 ... 
[INFO] DOCKER> Trying to pull repository registry.centos.org/busybox1 ... 
[INFO] DOCKER> Trying to pull repository docker.io/library/busybox1 ... 
[ERROR] DOCKER> Error occurred during container startup, shutting down...
[ERROR] DOCKER> I/O Error [Unable to pull 'busybox1:latest' : repository docker.io/busybox1 not found: does not exist or no pull access ]
```

This is quite problematic as I'm unable to add proper healthchecks to an existing image.

**Comment by rhuss** [comment]
You have to build the image "busybox1" first :

```
mvn package docker:build
mvn clean install
```

I agrred that for this sample, building should be bound to the install phase, too.

**Comment by gsmet** [comment]
Ah right, thanks for the quick answer. Found the example and it is a bit misleading.

Attaching build to the compile phase worked for me.

Thanks for the quick answer.

**Comment by rhuss** [comment]
you are welcome :)
