### ISSUE TITLE
remove goal doesn't get executed when timeout on container start

### ISSUE THREAD

**Issue by Tal24** [fabric8io/docker-maven-plugin#1143]
We have this execution as part of the fabric8:

```
<execution>
	<id>remove-it-docker</id>
	<phase>post-integration-test</phase>
	<configuration>
		<filter>release-management-couchbase</filter>
		<removeAll>true</removeAll>
	</configuration>
	<goals>
		<goal>remove</goal>
	</goals>
</execution>
```

But I saw that in case of an error:
[INFO] DOCKER> [illin5225.corp.company.com:5000/couchbase-release-management:d424c4e] "release-management-couchbase": Start container c9a6a101269a
**[ERROR] DOCKER> Cannot process chunk response: java.net.SocketException: Socket closed**
[ERROR] DOCKER> [illin5225.corp.company.com:5000/couchbase-release-management:d424c4e] "release-management-couchbase": **Timeout** after 120350 ms while waiting on log out 'Couchbase server setup completed'
[ERROR] DOCKER> Error occurred during container startup, shutting down...
[INFO] DOCKER> [illin5225.corp.company.com:5000/couchbase-release-management:d424c4e] "release-management-couchbase": Stop and removed container c9a6a101269a after 0 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

The 'remove' goal doesn't get executed and the image remains. I want the remove goal to be executed anyway.

f-m-p version : 0.23.0
Maven version (mvn -v) : 3.3.9

**Comment by rohanKanojia** [comment]
@Tal24 : You're using quite old version of dmp, Could you please try with latest one, i.e `0.28.1`?

**Comment by Tal24** [comment]
@rohanKanojia , I see that the docker:start, remove the container but doesn't remove the image.
is it solved in 0.28.1 version?

**Comment by rohanKanojia** [comment]
@Tal24 : Did it just work for you? the latest dmp version I mean...

**Comment by burtsevyg** [comment]
> @Tal24 : Did it just work for you? the latest dmp version I mean...

I can not find version 0.28.1 in maven central.

**Comment by burtsevyg** [comment]
@rohanKanojia no problem, thank you.
