### ISSUE TITLE
Proxy settings are ignored

### ISSUE THREAD

**Issue by jakub-bochenski** [fabric8io/docker-maven-plugin#1148]
### Description
[Since Docker 17.07](https://docs.docker.com/network/proxy/) you can configure the client to use a proxy. 
When running build via d-m-p it doesn't work.

See linked project on how to reproduce.

### Info

* d-m-p version : 0.27.2
* Maven version (`mvn -v`) : 3.5.4
* Docker version : 18.06.1-ce
* Sample project : https://github.com/jakub-bochenski/demp-link-problem/tree/proxy

**Comment by jakub-bochenski** [comment]
Workaround: pass the settings manually using build args, e.g. `-Ddocker.buildArg.http_proxy=http://proxy:8001`

**Comment by daniele-bottelli** [comment]
same problem proxy set in ~/.docker/config.json is ignored

plugin version 0.26.0
docker 18.06.1-ce

thanks @jakub-bochenski for the workaround :)

**Comment by kortemik** [comment]
It would be really useful to be able to configure pushProxy and pullProxy, as either one of them can be behind a proxy.

**Comment by rhuss** [comment]
@jakub-bochenski So your suggestion is that d-m-p should evaluated a `~/.docker/config.json` for proxy setting and then set those environment variables (`HTTP_PROXY`) automatically for `build` and `run` ?  When you would set them manually (as you did with build.args) then it should would already work, right ? Also I think, we could examine the proxy settings in `~/.maven/settings.xml` for Maven to implicitely evaluate the proxy settings. Please note though, that the proxy is used on the Docker dameon's host and not on the host where maven is running on (but they could be the same).

@kortemik For pull and push the situation is different, as this is performed by the Docker dameon itself. I don't see any possibility that a client can influence this. The only way I know to use proxies for pull and push is to configure the Docker daemon accordingly. But I could have missed something, so when you know how a Docker client can influence this, please let me know.

**Comment by jakub-bochenski** [comment]
>  your suggestion is that d-m-p should evaluated a ~/.docker/config.json for proxy setting 

d-m-p is already processing some of the config values there. Principle of least astonishment would suggest processing all of it.

I value the ability to switch between bare docker CLI and d-m-p seamlessly. It makes (would make) hacking/testing/migration etc. so much easier. 

Finally just as I woulnd't want to have to specify the proxy settings explicitly for Docker CLI, I don't want to hve to expose them for Maven. This is not only about readability but also about portability.
Right now I have to make special arrangements to inject a correct value just for Maven. For all other cases I just have a docker config provided.

> Also I think, we could examine the proxy settings in ~/.maven/settings.xml for Maven to implicitely evaluate the proxy settings.

That certainly wouldn't hurt, though I would suggest giving the docker config priority in case of settings being present in both.

**Comment by rhuss** [comment]
I totally agree that a proxy setting should not be part of the build (i.e. not entered in the pom.xml) and ideally not how the build is called. So it should be specific to the environment _where_ the build is called.

So I agree and I think respecting the proxy settings in ~/.docker/config.json is a good thing.

@jakub-bochenski @rohanKanojia fancy for jumping on a PR for this ? (sorry, no space left on my plate right now ;-(
