### ISSUE TITLE
Connection is still allocated error on Windows

### ISSUE THREAD

**Issue by Madanor** [fabric8io/docker-maven-plugin#1152]
### Description
d-m-p 0.28.0 is not working on Windows, e.g. `mvn docker:build`
Error: `Connection is still allocated`
0.28.0 works fine on Linux. Old version 0.27.2 works on Windows.
The issue is reproducible with d-m-p version switching back and forth, restarting, colleagues machine.
I found this issue from f-m-p, which looks related: https://github.com/fabric8io/fabric8-maven-plugin/issues/1468

```
> mvn docker:build
[INFO] Scanning for projects...
... download artifacts ...
[INFO]
[INFO] --------------------------< com.example:test >--------------------------
[INFO] Building test 1.0-SNAPSHOT
[INFO] ----------------------------[ docker-build ]----------------------------
[INFO]
[INFO] --- docker-maven-plugin:0.28.0:build (default-cli) @ test ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.089 s
[INFO] Finished at: 2019-01-17T14:55:35+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.28.0:build (default-cli) on project test: Execution default-cli of goal io.fabric8:docker-maven-plugin:0.28.0:build failed: Connection is still allocated -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

```
### Info

* d-m-p version : 0.28.0
* Maven version (`mvn -v`) : 3.5.4 or 3.6.0
* Windows version : 10.0.14393 Build 14393
* Docker version : Docker Desktop 2.0.0.2 (30215)
* How to reproduce : [windows-0.28.0.zip](https://github.com/fabric8io/docker-maven-plugin/files/2768983/windows-0.28.0.zip)

**Comment by JoepWeijers** [comment]
Running into exactly the same issue. Reverting to 0.27.2 as a workaround for now.

**Comment by a-a-davydov** [comment]
I have same problem:

d-m-p version : 0.28.0
Maven version (`mvn -v`) : 3.3.9 (Netbeans 9.0)
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
Windows 10 pro

Docker version : Docker desctop community Version 2.0.0.2 (30215) Channel: stable Build: 0b030e1

**Comment by nilsonpontello** [comment]
Same problem here, also downgraded to 0.27.2.

**Comment by brandonheck** [comment]
👍 Seeing the same here, downgrade to 0.27.2 works.

**Comment by reneploetz** [comment]
Looking at the source code and the changes between 0.27.2 and 0.28, this is might be a connection leak in DockerAccessWithHcClient.fetchApiVersionFromServer as the CloseableHttpResponse is never closed.

**Comment by LorenzoBettini** [comment]
Thanks! When will this fixed version be released?

**Comment by rohanKanojia** [comment]
@LorenzoBettini : Umm, I think it would be available in 2-3 weeks. Roland manages the release process; if he is too busy, maybe it can be delayed by 1-2 weeks.

**Comment by rhuss** [comment]
I'm going to make a release this weekend. Sorry for any inconvenience and the long delay.

**Comment by Madanor** [comment]
Thank you.

**Comment by meier297** [comment]
Thanks. But latest version 4.1.0 on https://mvnrepository.com/artifact/io.fabric8/fabric8-maven-plugin uses still docker-maven-plugin 0.28.0. When a new release will be available?

**Comment by rodrigorodrigues** [comment]
@meier297 had same issue with 0.28.0 but I updated for latest version 0.30.0 and worked fine

**Comment by sramshek** [comment]
We are still seeing this error with docker-maven 0.44.0 version.

**Comment by rohanKanojia** [comment]
@sramshek : Could you please open a new issue with a reproducer project and your environment details?
