### ISSUE TITLE
pull form hub.docker.com when I use private registry

### ISSUE THREAD

**Issue by zamek42** [fabric8io/docker-maven-plugin#1155]
### Description
When I use private registry in my project, Dockerfile contains reference to openjdk:8, but the plugin cannot pull it, because it tries to pull from my private registry. How can I reference hub.docker.com/openjdk:8? 
[ERROR] DOCKER> Unable to pull 'openjdk:8' : 404 page not found (Not Found: 404) [404 page not found (Not Found: 404)]

### Info

* d-m-p version : 0.28.0
* Maven version (`mvn -v`) : Apache Maven 3.6.0
```

```
* Docker version : 18.09.1
* If it's a feature request, what is your use case :
there is a private repository defined: in docker-host, it would be better if I can reference original docker hub in Dockerfile

**Comment by wrosenuance** [comment]
I worked around this by always referencing images from the Docker library with index.docker.io/library, so for the openjdk:8 image that would be index.docker.io/library/openjdk:8.

**Comment by rhuss** [comment]
@zamek42 Indeed, a `<registry>` configuration will be used if no explicit registry is contained as part of the image name. Is the solution that @wrosenuance suggest good enough for you ? 

I hope so, so I'm closing this issue. But please don't hesitate to reopen it in case you think that d-m-p needs a fix here.

**Comment by zamek42** [comment]
Hi rhuss,
Yes it is ok. Thanks, we can close this.
