### ISSUE TITLE
runCmds are only executable with /bin/sh set

### ISSUE THREAD

**Issue by MeiSign** [fabric8io/docker-maven-plugin#1156]
### Description
I am trying to create a docker image with `RUN` parameters and a linux distribution as `FROM` param, that hasn't linked `/bin/sh`. Dockerfiles support two `RUN` syntaxes to set the executable that should  your command or to use the standard shell (`/bin/sh`). (https://docs.docker.com/engine/reference/builder/#run).

When you are in the situation that `/bin/sh` is not linked you are in a deadlock situation with the plugin. You need a RUN cmd to link the shell but you can't execute the link command.

I can think of two possible solutions:
1. Extend the runCmd section to support the exec syntax
2. Support the SHELL param to set a standard shell without linking it per RUN parameter (https://docs.docker.com/engine/reference/builder/#shell)

If I didn't miss something, I can make a pull request if you tell me which of the options you would prefer.

**Comment by MeiSign** [comment]
I have added a pull request with the implementation of the second option. 
The runCommands have already the optimise option and I don't wanted to complicate this setting further.

**Comment by rhuss** [comment]
I agree that option 2 is probably simpler (remember, you have always the option to use a plain Dockerfile if advanced Dockerfile options are required). 

The PR looks good, with some minor change request (see over there).
