### ISSUE TITLE
Container name pattern ignored when stopping

### ISSUE THREAD

**Issue by jakub-bochenski** [fabric8io/docker-maven-plugin#1168]
### Description
I want to run concurrent builds on a single docker host (for CI).

I started two builds with `-Ddocker.containerNamePattern="$BUILD_TAG-%n-%i"` (e.g. `-Ddocker.containerNamePattern=build-1-%n-%i` and `-Ddocker.containerNamePattern=build-2-%n-%i`).

I expected the builds to ignore each other's containers, only stopping the ones that match their respective build pattern, but instead they stop each other's containers.

This results in errors because containers being stopped mid-use.
```
12:59:54 [ERROR] DOCKER> [acme-all:latest] "acme-all": Container stopped with exit code 137 unexpectedly after 35529 ms while waiting on healthcheck '"CMD-SHELL", "wget --server-response -q -O /dev/null http://localhost:8080/acme/status || exit 1"'
12:59:54 [ERROR] DOCKER> Error occurred during container startup, shutting down...
12:59:54 [ERROR] DOCKER> Unable to remove container [b097fd97dc80] : removal of container b097fd97dc80 is already in progress (Conflict: 409) [removal of container b097fd97dc80 is already in progress (Conflict: 409)]
```
While in the other build log there is
```
12:59:54 [INFO] DOCKER> [acme-all:latest]: Stop and removed container b097fd97dc80 after 0 ms
```

### Info

* d-m-p version : 0.27.2
* Maven version (`mvn -v`) : 3.5
* Sample project: https://github.com/jakub-bochenski/demp-concurrent-stop

**Comment by jakub-bochenski** [comment]
I've created a sample project to demonstrate the issue: https://github.com/jakub-bochenski/demp-concurrent-stop

This is a major blocker for me, so I would appreciate at least some hints on how to work around this.

**Comment by jakub-bochenski** [comment]
Looking at https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/util/ContainerNamingUtil.java#L66 there is no code to differentiate images created with different name patterns. 

Seems like the only thing that matters is GAV and the image used for the container. The name pattern is not taken into account to differentiate containers. This is not what the documentation suggests

> You can combine the placeholders in any combination and will be resolved during docker:start, docker:stop and docker:watch.

Would you accept a PR that would change it, so that only containers started with the same name pattern would be considered?

**Comment by rhuss** [comment]
Sorry for the long delay, but yes, it sounds like a very valid bug. If you would send a PR, that would be awesome. Currently I have a bit of a time window to work on d-m-p, so happy to get a fix in quickly.

**Comment by jakub-bochenski** [comment]
OK, thanks
I'll get round to do this eventually, for now I have a workaround in place and some other priorities

**Comment by rhuss** [comment]
thanks, I totally understand and happy that you found a solution. I keep that bug open, maybe someone else wants to jump on it.

**Comment by j3t** [comment]
We have a similar issue but in our case the containerNamePattern is just %a. I can provide a fix for that and maybe I can also try to fix the original issue.

**Comment by j3t** [comment]
Regarding the original issue, in case the containerNamePattern contains the %i or %t placeholder then we probably cannot fix it easily.

**Comment by jakub-bochenski** [comment]
I think that would be appreciated. Unfortunately I think I won't be able to work on it any time soon

**Comment by j3t** [comment]
The current implementation treats index placeholders specially. It keeps the container with highest index (see https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/util/ContainerNamingUtil.java#L85). Why is this necessary? I don't get it.

However, for me it's not clear how we should handle the stopping process when the containerPattern contains %i or %t. Both parameters are automatically generated (see `io.fabric8.maven.docker.util.ContainerNamingUtil#formatContainerName`) and they are not available when the stop mojo is executed. My suggestion:
* all containers where the name matches the containerNamePattern are stopped
* %a is replaced with the alias of the image configuration (equivalent to the start mojo)
* %n is replaced with the name of the image configuration (equivalent to the start mojo)
* %i is replaced with any number (\d+)
* %t is replaced with any date (\d{10,})
