### ISSUE TITLE
Coordinate with other plugins for IT

### ISSUE THREAD

**Issue by heruan** [fabric8io/docker-maven-plugin#1178]
I'm using the plugin for integration tests with Spring Boot and this is my `pom.xml` build plugins section:

```xml
<plugin>
    <groupId>io.fabric8</groupId>
    <artifactId>docker-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>prepare-it-database</id>
            <phase>pre-integration-test</phase>
            <goals>
                <goal>start</goal>
            </goals>
            <configuration>
                <!-- image configuration -->
            </configuration>
        </execution>
        <execution>
            <id>remove-it-database</id>
            <phase>post-integration-test</phase>
            <goals>
                <goal>stop</goal>
            </goals>
        </execution>
    </executions>
</plugin>
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>spring-boot-start</id>
            <phase>pre-integration-test</phase>
            <goals>
                <goal>start</goal>
            </goals>
        </execution>
        <execution>
            <id>spring-boot-stop</id>
            <phase>post-integration-test</phase>
            <goals>
                <goal>stop</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

This executes the plugins in this order:

1. `pre-integration-test`: `docker-maven-plugin:start`
2. `pre-integration-test`: `spring-boot-maven-plugin:start`
3. `integration-test`: runs actual tests
4. `post-integration-test`: `docker-maven-plugin:stop`
5. `post-integration-test`: `spring-boot-maven-plugin:stop`

The problem is that the container is stopped at step (4), i.e. before the Spring app being stopped at step (5), resulting in database connection exception.

How can I swap steps (4) and (5), to have the container still started before starting the app, but stopped before stopping the app?

**Comment by rhuss** [comment]
That's a good question ;-) I'm not sure whether you can influence the order of multiple goals bound to the same lifecycle phase in Maven (this is more a general Maven question).

A workaround could be to use different phases for d-m-p and spring boot plugin.

See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference for the order of phase (default lifecycle).

So maybe binding d-m-p stop to the "verify" phase could help ?

**Comment by heruan** [comment]
Thank you @rhuss for the response! You're right, that's more a Maven question but I guessed the use case might have been already faced with d-m-p 🙂

I'm actually using the `verify` phase to stop the container, but somehow I still get the connection exception (most probably because of a race condition between the Spring shutdown process and the next Maven phase).

Maybe some kind of `wait` configuration also for stopping the container would help (e.g. in my case to wait until there are no more active connections to the database). What do you think?

**Comment by rhuss** [comment]
Yeah, might make sense. But have you considered to switch tohttps://www.testcontainers.org/ ?
I'm asking because I think there support for integration tests is superior of that of d-m-p and for the near future, I plan to stop adding new features to docker:start / docker:stop here, and recommend testcontainer instead.

Would this be an option for you, too ?

**Comment by heruan** [comment]
Didn't know about testcontainers, sure it seems a fit solution but I have to a look and understand how to use it with Spring. Thank you!

**Comment by rhuss** [comment]
'hope its ok for you when I close this issue (I have no good solution anyway). Feel free to reopen if you think otherwise.
