### ISSUE TITLE
Allow killing and removing all spawned containers

### ISSUE THREAD

**Issue by ivanfryda** [fabric8io/docker-maven-plugin#1182]
We use the maven plugin for integration testing. The stopping of every container in a sequential order takes some time. As it is used just for testing, it would be better if the plugin could offer a mechanism to execute docker kill on every container, which should be almost immediate.

**Comment by rhuss** [comment]
Not sure if I understand you correctly when you say 'kill on every' container, and why this is faster than proper docker:stop.

**Comment by danielwegener** [comment]
I he means that a regular docker stop would wait for the process to terminate correctly while a hard docker rm -f would terminate the process with a sigkill which is faster for some heavy application servers.

**Comment by rhuss** [comment]
I see and think it might be a valid use case for testing. I'm positive for adding a `stopMode` to `RunImageConfiguration` with e.g. possible values `graceful` and `kill` and implementing the proper semantics.

However, I can't do the coding but would happy to support a submitted PR (if you have some patience, as I'm really low on time which I can spend on d-m-p)

**Comment by rohanKanojia** [comment]
@rhuss : Shall I look into this?

**Comment by rhuss** [comment]
@rohanKanojia would be awesome. You are the best ;-)
