### ISSUE TITLE
Unable to pull 'postgres:9' : {"message":"page not found"} (Not Found: 404) [{"message":"page not found"} (Not Found: 404)]

### ISSUE THREAD

**Issue by dlanorf** [fabric8io/docker-maven-plugin#1183]
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< com.hp.am.browser:sam-ui >----------------------
[INFO] Building SAM Web MAIN-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:0.28.0:build (build-docker-image) @ sam-ui ---
[ERROR] DOCKER> Unable to pull 'postgres:9' : {"message":"page not found"} (Not Found: 404) [{"message":"page not found"} (Not Found: 404)]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.742 s
[INFO] Finished at: 2019-03-28T16:40:28+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.28.0:build (build-docker-image) on project sam-ui: Unable to pull 'postgres:9' : {"message":"page not found"} (Not Found: 404) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by dlanorf** [comment]
Below is part of my pom
<plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.28.0</version>
        <configuration>
          <images>
            <image>
              <alias>samAlias</alias>
              <name>${project.artifactId}/sam</name>
              <build>
                <dockerFileDir>${project.build.outputDirectory}</dockerFileDir>
              </build>
              <build>
                <from>postgres:9</from>
                <assembly>
                  <targetDir>${project.build.outputDirectory}</targetDir>
                </assembly>
              </build>
            </image>
          </images>
        </configuration>
        <executions>
          <execution>
            <id>build-docker-image</id>
            <goals>
              <goal>build</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
      </plugin>

**Comment by dlanorf** [comment]
<plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.28.0</version>
        <configuration>
          <images>
            <image>
              <alias>samAlias</alias>
              <name>${project.artifactId}/sam</name>
              <build>
                <dockerFileDir>${project.build.outputDirectory}</dockerFileDir>
              </build>
              <build>
                <from>postgres:9</from>
                <assembly>
                  <targetDir>${project.build.outputDirectory}</targetDir>
                </assembly>
              </build>
            </image>
          </images>
        </configuration>
        <executions>
          <execution>
            <id>build-docker-image</id>
            <goals>
              <goal>build</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
      </plugin>

**Comment by cmooney** [comment]
How did you resolve this? I am having a similar issue when trying to execute within a Jenkins pipeline.
