### ISSUE TITLE
maven enforcer rule for minimum docker version

### ISSUE THREAD

**Issue by hauntingEcho** [fabric8io/docker-maven-plugin#1184]
### Description
Our CI environment was giving strange behavior/errors when trying to use the docker-maven-plugin.  As it turns out, the build server uses docker 17.12.0 but a minimum of 18 is required.  A rule in maven-enforcer would make the failure case much more clear and abort before attempting to build (in the validate phase).

### Info
* d-m-p version : 0.28.0
* Maven version (`mvn -v`) : 3.3.9
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/maven-3.3.9
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.8.0_112/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.10.1.el7.x86_64", arch: "amd64", family: "unix"
```
* Docker version : `Docker version 17.12.0-ce, build c97c6d6`

**Comment by rhuss** [comment]
From where did you got the info that Docker 18 is a minimal requirement ? Actually, depending on the features you are using, d-m-p works with Docker as old as Docker version 1.6.0 (from 2014).

Also, there is an initial API check which will fail the d-m-p early.

Please describe your use case a bit in more detail, preferable with an example pom.xml and the error message you get.

**Comment by hauntingEcho** [comment]
I may have been misunderstanding a coworker's comment on Docker's versioning, and interpreting docker version naming as behaving like Java versioning (where 1.6 = 6).

I'll follow up on Monday with build logs and a minimal reproduction POM - currently we're seeing d-m-p failures on the build server (whose specs are in the OP) which are not present locally (OSX with up-to-date docker & maven 3.5.x)

**Comment by hauntingEcho** [comment]
sorry it's taken awhile to get back to you - the build server was updated, and I haven't been able to replicate the issue since (there or locally).  Closing this ticket
