### ISSUE TITLE
docker:save fails if no images are defined

### ISSUE THREAD

**Issue by wrose504** [fabric8io/docker-maven-plugin#1185]
If the save goal is executed when no images are defined, it fails with a message indicating that multiple images are defined. This occurs because the code checks whether the image list size is exactly one, and does not consider the possibility that the list is empty.

https://github.com/fabric8io/docker-maven-plugin/blob/546c7a1aed3627a8216e7c06524e942514eee9c4/src/main/java/io/fabric8/maven/docker/SaveMojo.java#L104

The warning is then emitted just below:

https://github.com/fabric8io/docker-maven-plugin/blob/546c7a1aed3627a8216e7c06524e942514eee9c4/src/main/java/io/fabric8/maven/docker/SaveMojo.java#L107

I came across this issue when I bound the docker:save goal to the install phase in a parent pom that defined no images, with the intention of defining images only in child poms. However, this code meant that the parent failed to build.

I was able to work around this with a non-inherited plugin configuration in the parent that set skipSave=true, but it seems like it would be better if the mojo would skip over projects where there were no images without raising an error.

**Comment by rhuss** [comment]
Good catch. Fancy to submit a PR ?

**Comment by wrose504** [comment]
I would, but I'm not sure whether my employer allows open-source contributions without prior approval. I will check though.

**Comment by rhuss** [comment]
@wrose504 cool. Maybe it helps as an argument, that you are using that open source component for your product and you would like to help to fix it (which then also helps your productised usage).

That is how open source works btw.

**Comment by wrosenuance** [comment]
I figured out the company policy and I have created PR #1194 using my other account.

I tested it against 0.28.0 as a baseline because the recent changes on master mean the test suite no longer runs cleanly on Windows, but the patch is small and applies cleanly to master.

**Comment by rhuss** [comment]
Cool, thanks a lot for your support !

Sorry we don't do regular tests on Windows (we should though). Could you please open another issue witht the Windows build problems ? That would be awesome !
