### ISSUE TITLE
Test cases fail on Windows

### ISSUE THREAD

**Issue by wrosenuance** [fabric8io/docker-maven-plugin#1195]
### Description
Existing test cases use relative paths in dockerFile, but the EnvUtil.isValidWindowsFileName() test applied to this field fails if there are slashes or backslashes.

### Info
This is only reproducible if running the test suite on Windows as EnvUtil.isWindows() is called before EnvUtil.isValidWindowsFileName(). This also means the restriction that the dockerFile attribute only be a file name and not a path is only applied to Windows.

* d-m-p version : 0.29-SNAPSHOT
* Maven version (`mvn -v`) : 3.5.4
```

```
* If it's a bug, how to reproduce : run mvn clean test on latest checkout on a Windows host

**Comment by rhuss** [comment]
In fact, the dockerFile should be possibly a path, not only a plain filename.

Thanks for reporting this. @rohanKanojia would this be an issue you could have a look if time permits ?

**Comment by rohanKanojia** [comment]
Hmm, let me check it on my brother's laptop.

**Comment by wrosenuance** [comment]
@rohanKanojia I created a PR #1198 that resolves this issue for me by taking out the Windows-specific validations that are inconsistent with other platforms. I think it should be enough to rely on the File() constructor and other java.io class code to validate paths in a cross-platform way.

There was one test case that tried to create an absolute path for the dockerFile parameter by passing "/Dockerfile": I updated this test case to use new File("Dockerfile").getAbsolutePath() so that it generates a valid absolute path for the platform.

**Comment by rhuss** [comment]
Actually this check was introduced with https://github.com/fabric8io/docker-maven-plugin/pull/834 . Not sure anymore what this actually fixed ;-)

**Comment by rohanKanojia** [comment]
@wrosenuance : I tried building this on windows but surefire failed before test suite could run: https://pastebin.com/SiK8wBMT. Could you please tell me how you tested it on windows?

**Comment by rohanKanojia** [comment]
bdw, has anyone considered integrating Azure pipelines into repo?  I've seen on Quarkus repository that they're using it, here is a sample https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=912 . I think it's free for OSS projects

**Comment by wrosenuance** [comment]
> @wrosenuance : I tried building this on windows but surefire failed before test suite could run: https://pastebin.com/SiK8wBMT. Could you please tell me how you tested it on windows?

I just checked out the branch, opened the Git bash from Git for Windows, and ran:
`env -u DOCKER_REGISTRY mvn clean install`

I needed to unset DOCKER_REGISTRY to avoid some test failures. I am also running on a computer that doesn't have Docker for Windows installed: instead, I'm using Docker Toolbox to access a remote Docker build server that is Linux based. So that may be a factor?

**Comment by rohanKanojia** [comment]
I don't think plain build requires docker to be installed :confused: . Strange, for me it failed; tests could not even run

**Comment by rhuss** [comment]
I guess that's a Maven issue and due to the space in your user name. The classical Windows issue ;-)

**Comment by rohanKanojia** [comment]
when I `-DskipTests` it passes

**Comment by wrosenuance** [comment]
An example build log from my computer is 
[build-log.txt](https://github.com/fabric8io/docker-maven-plugin/files/3060574/build-log.txt).

I don't have a space in my username so that could be helping.

**Comment by rhuss** [comment]
@rohanKanojia you could try it by just checking out d-m-p in a directory without a space in the path (e.g. `C:\tmp`)
