### ISSUE TITLE
Support detecting image name during docker:build from docker archive

### ISSUE THREAD

**Issue by wrosenuance** [fabric8io/docker-maven-plugin#1207]
### Description
When an image archive is saved with the docker:save mojo or using docker save on the command line, the archive contains a manifest that records the tags that were saved. Later, when loading the image using docker:build and dockerArchive, these tags are restored. However, if these tags do not match the <name> configured in the image, then later actions by the plugin fail as they attempt to refer to a non-existent tag.

### Info
In a workflow where containers are built, saved to an archive with docker:save, and published to a Maven artifactory, then retrieved later using maven-dependency-plugin and reloaded into the Docker server, it may be difficult to know exactly how the image was tagged when the docker:save happened.

For instance, images tagged with a snapshot timestamp, or built with a Git hash in the tag that is not part of the version, can still be attached and later retrieved by a project that doesn't know (and can't know) the actual build timestamp or hash. Images saved from outside of the plugin may have had a repository in the tag that could vary, or be absent sometimes and present other times.

In these cases, it would be useful to be able to scan the archive to find the tag that matches a pattern (e.g. with the tag containing a wildcard, or an optional prefix).

* d-m-p version : 0.29-SNAPSHOT
* Maven version (`mvn -v`) : 3.5.4

**Comment by rhuss** [comment]
Sound like a legit use case. Happy to help to integrate the PR you sent together with you.
