### ISSUE TITLE
Bug in fix #1148

### ISSUE THREAD

**Issue by rpecheur** [fabric8io/docker-maven-plugin#1237]
When data are extracted from local ~/.docker/config.json, "docker.buildArg" is not removed from property name.

It give:
"Build args set {docker.buildArg.http_proxy=http://127.0.0.1:3001}"
Instead of:
"Build args set {http_proxy=http://127.0.0.1:3001}"

In commit ad5b3222fafc598456de74dc42ed4b3b24e97709:
BuildService.java: Line 217:
buildArgs.put(argPrefix + entry.getValue(), defaultProxyObj.get(entry.getKey()).getAsString());
-> Should remove argPrefix.

Thank you

**Comment by rohanKanojia** [comment]
You mean #1148 ?

**Comment by rpecheur** [comment]
Yes

**Comment by rohanKanojia** [comment]
Can you raise a PR to fix it then? If you have spotted the bug?

**Comment by rpecheur** [comment]
It s detailed in my post.
One element to remove i think.

**Comment by rohanKanojia** [comment]
Yeah, I get it. But I'm asking you to raise PR if you have time :-)

**Comment by rpecheur** [comment]
Done #1238

**Comment by rhuss** [comment]
#1238 is merged. Thanks for your patience and sorry for the delay.
