### ISSUE TITLE
Use identity token from Docker config.json if present

### ISSUE THREAD

**Issue by wrosenuance** [fabric8io/docker-maven-plugin#1249]
### Description
Identity tokens in Docker config.json are not used, which prevents token-based access to Azure Container Registry.

### Info
When using the Azure CLI to authenticate to Azure Container Registry, the Docker config.json is edited to add authentication information with a default username (GUID that is all zeroes) and blank password, and a time-limited access token. The default username and password are not actually acceptable: instead, the registry expects to receive the identity token, as described at https://docs.docker.com/engine/api/v1.39/#section/Authentication.

I will submit a PR to enable checking for an existing identity token as I was able to make this work fairly easily.

* d-m-p version : 0.30.0-SNAPSHOT
* Maven version (`mvn -v`) : 3.5.4
* If it's a feature request, what is your use case :

**Comment by rhuss** [comment]
Happy to integrate the PR, but please note that I will be off for 3 weeks starting next week.
