### ISSUE TITLE
NPE when cacheFrom is missing from config

### ISSUE THREAD

**Issue by travishaagen** [fabric8io/docker-maven-plugin#1274]
### Description

A `NullPointerException` is thrown when `cacheFrom` is missing from the configuration.

```
Caused by: java.lang.NullPointerException
    at io.fabric8.maven.docker.config.handler.property.PropertyConfigHandler.extractBuildConfiguration (PropertyConfigHandler.java:140)
    at io.fabric8.maven.docker.config.handler.property.PropertyConfigHandler.resolve (PropertyConfigHandler.java:73)
...
```

### Info

The fix is most likely to  update the following line in `PropertyConfigHandler` to check for `config.getCacheFrom()` returning `null`, instead of calling `.toString()` in all cases:

```
.cacheFrom(valueProvider.getString(CACHE_FROM, config == null ? null : config.getCacheFrom().toString()))
```

The workaround is to provide an empty tag in the config:

```
                            <build>
                                <dockerFile>Dockerfile</dockerFile>
                                <cacheFrom/>
                            </build>
```

**Comment by rohanKanojia** [comment]
@travishaagen Which version are you using?

**Comment by travishaagen** [comment]
I was going from `0.28.0` to `0.31.0`.

**Comment by rohanKanojia** [comment]
oh, so it's still reproducible on 0.31.0. Could you please raise a PR to resolve this?

**Comment by travishaagen** [comment]
Done! :)

**Comment by rhuss** [comment]
thanks !
