### ISSUE TITLE
Log is not enabled if Dockerfile present.

### ISSUE THREAD

**Issue by dpwrussell** [fabric8io/docker-maven-plugin#1291]
### Description

Under certain conditions, logging does not get correctly enabled. This is not a definitive list!

Basically if I run the following docker command, it logs to stdout as I would expect. It prints the npm version.

```bash
docker run \
  --rm \
  -it \
  --entrypoint npm \
  node:12-alpine \
  --version
```

When I try the equivalent using the plugin, it does not get output with the rest of the Maven output despite logging being explicitly set to true.

```xml
<execution>
    <id>npm version</id>
    <goals>
        <goal>start</goal>
        <goal>stop</goal>
        <goal>remove</goal>
    </goals>
    <phase>test</phase>
    <configuration>
        <images>
            <image>
                <name>node:12-alpine</name>
                <run>
                    <entrypoint>
                        <arg>npm</arg>
                    </entrypoint>
                    <cmd>
                        <arg>--version</arg>
                    </cmd>
                    <wait>
                        <exit>0</exit>
                        <time>18000</time>
                    </wait>
                    <log>
                        <enabled>true</enabled>
                    </log>
                </run>
            </image>
        </images>
    </configuration>
</execution>
```

If I add a color tag, it starts to correctly log:

```xml
                    <log>
                        <enabled>true</enabled>
                        <color>cyan</color>
                    </log>
```

If I build a docker image instead then simply start/stop it, it also starts to log correctly (even without the colour.

```Dockerfile
# test.Dockerfile
FROM node:12-alpine
CMD ["npm", "--version"]
```

```xml
<execution>
    <id>npm version</id>
    <goals>
        <goal>build</goal>
        <goal>start</goal>
        <goal>stop</goal>
        <goal>remove</goal>
    </goals>
    <phase>test</phase>
    <configuration>
        <images>
            <image>
                <name>dmp-test</name>
                <build>
                    <dockerFile>${project.basedir}/test.Dockerfile</dockerFile>
                </build>
                <run>
                    <wait>
                        <exit>0</exit>
                        <time>18000</time>
                    </wait>
                    <log>
                        <enabled>true</enabled>
                    </log>
                </run>
            </image>
        </images>
    </configuration>
</execution>
```

This seems very strange and I can only imagine that somehow logging is deactivated under certain conditions when it should not be.

### Info

* d-m-p version : 0.31.0
* Maven version (`mvn -v`) : Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T20:00:29+01:00)
* Docker version : 19.03.2, build 6a30dfc

**Comment by rhuss** [comment]
Thanks a for the report, it indeed looks strange. I can assure that there is no special treatment for logging within dmp.

However, to reproduce the issue, could you please craft a full working pom.xml so that I can try and debug it locally ? Thanks !

**Comment by dpwrussell** [comment]
@rhuss Apologies for the delay.

https://gist.github.com/dpwrussell/229479428fd0907913fb088a030c0697

Essentially it comes down to the presence of a `Dockerfile`. If you delete that, it will behave as expected. Perhaps there is some configuration done upon detecting a Dockerfile, even if that Dockerfile is not used in any of executions of the plugin?

**Comment by rhuss** [comment]
Thanks a lot for your investigation. I could track the bug down to an erronous boolean check. The fix should be available in the next release which should be published very soon (probably still this week).
