### ISSUE TITLE
stop goal does not remove stop/remove containers when using containerNamePattern or stopNamePattern

### ISSUE THREAD

**Issue by chadmalla-ff** [fabric8io/docker-maven-plugin#1294]
### Description
I have a child module that has the `stop` goal with `containerNamePattern` with the exact name of the container started in the parent module for testing purposes. The plugin doesn't do anything. When I use the `allContainers` option, it removes the containers which is what I want but I want to specify which container.
### Info
I have tried this:

```xml
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>stop-postgres</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <dockerHost>tcp://${docker.ip}:2375</dockerHost>
                    <removeVolumes>true</removeVolumes>
                    <stopNamePattern>%regex[maven]</stopNamePattern>
                </configuration>
            </plugin>
```
and this:

```xml
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>stop-postgres</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <dockerHost>tcp://${docker.ip}:2375</dockerHost>
                    <removeVolumes>true</removeVolumes>
                    <containerNamePattern>database</containerNamePattern>
                </configuration>
            </plugin>
```
* d-m-p version : 0.31.0
* Maven version (`mvn -v`) : 3.6.1
```

```
* Docker version : 19.03.4
* If it's a bug, how to reproduce : Start a container in a separate module then try to remove it in another module using the exact name of the container.

**Comment by rhuss** [comment]
Thanks for the report. It's hard for me to reproduce, would it be please possible to provide a complex pom.xml to reproduce the error locally ? You could also check, if the container name is really the one you expect (with `docker ps`). Remember, the `alias` is not the container name.

**Comment by chadmalla-ff** [comment]
Hi @rhuss , so looking at [this](https://github.com/fabric8io/docker-maven-plugin/blob/5f1fed9f95b887e5c4dcc5cc4da78a41deaf3800/src/main/java/io/fabric8/maven/docker/StopMojo.java#L211), my understanding is that if I have two pom files, one in the parent project and a pom file in a child project where in the parent project I have the `start` goal and in the child project I have the `stop` goal then there isn't a way for me to stop containers started in the parent project using a name pattern?

What I see in that function is with `allContainers` set to true, the plugin will just stop all the containers but if I want to chose which containers to stop then my `start` and `stop` goal have to be in the same pom file because it depends on `GAVlabel`. 

If this is not clear then I can work on making a sample project that exercises this behavior.

Thank you very much for this plugin!

**Comment by rhuss** [comment]
Yes, start/stopping containers does reliably only work when done within a single pom.xml. It's really a complex setup to spread the container lifecycle over multiple pom.xmls. I wonder whether it wouldn't be better to use a different lifecycle phase to bind your start/stop of the containers in the same pom.xml  ?

**Comment by chadmalla-ff** [comment]
Binding to a different lifecycle was my initial go-to solution but I could not find a lifecycle that happens after all the the child modules have finished with their build lifecycles. 

Would it be too hard to enhance the `allContainers` feature to pick up name patterns? Essentially I am able to `stop` containers from a different `pom` file than the one the containers are started from if I have the option `allContainers` set as `true`. Only in my case I want to additionally filter the `allContainers` with a pattern.

**Comment by rhuss** [comment]
I think this is possible. Unfortunately,  I no time to implement that but I would happily help to integrate any submitted PR.

btw, I think your use case could also be solved with a Maven _extension_ like in https://github.com/khmarbaise/maven-deployer-extension, i.e. run something after all child plugins have been run. That would require coding, too, so let's take the simpler route.

**Comment by chadmalla-ff** [comment]
Okay, thank you. I will try to look into implementing this when I have time.

**Comment by mattnelson** [comment]
I was able to get this to work using `allContainers` and `stopNamePattern` together. It will stop all container that match the pattern.
