### ISSUE TITLE
<envPropertyFile> not running within the tag <build>.

### ISSUE THREAD

**Issue by aarushig14** [fabric8io/docker-maven-plugin#1308]
### Description

I wanted to add environment variables while building a docker image using property file. But after building the environment variables does not show inside the container.

Code seems like this

`<image>
       <build>
            ........
             <envPropertyFile>/path/to/environment.properties</envPropertyFile>
            ..........
       </build>
</image>`

### Info

* d-m-p version :
* Maven version (`mvn -v`) :
```

```
* Docker version : 17.05.*
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
@aarushig14 : Which version of dmp are you using? Would it be possible for you to share a sample project to reproduce this behavior?

**Comment by aarushig14** [comment]
@rohanKanojia 

I might not be able to provide any project for this.
But can you tell me how can I check dmp version?

**Comment by rohanKanojia** [comment]
@aarushig14 : I think you have to specify `envPropertyFile` in `RunImageConfiguration`, not in `BuildImageConfiguration`. Here is an example:
https://github.com/fabric8io/docker-maven-plugin/blob/413c68139b86a5238d3caa6cac57b1a3d1f2e099/samples/data-jolokia/pom.xml#L111

**Comment by aarushig14** [comment]
@rohanKanojia Hi I checked the dmp version is 0.21.0
Also What I find is that if I use <dockerFileDir> tag it doesn't read the <env> tag under <build>.

**Comment by rohanKanojia** [comment]
You're using quite old version(~2 yrs old). Could you please try on latest version i.e 0.31.0?

**Comment by aarushig14** [comment]
@rohanKanojia okay let me try. Does it work if I am trying build a dockerfile as well

**Comment by rohanKanojia** [comment]
Yes, you can have a look at [this](https://github.com/fabric8io/docker-maven-plugin/tree/master/samples/dockerfile) example.

**Comment by aarushig14** [comment]
@rohanKanojia Thank you this is really a good example.

**Comment by rhuss** [comment]
@aarushig14 is your question and is ok to close this issue ? I assume so :), so I'm closing it but feel free to reopen it if this is not the case.
