### ISSUE TITLE
Build image(s) conditionally

### ISSUE THREAD

**Issue by alessiostalla** [fabric8io/docker-maven-plugin#1313]
### Description

We would like to have the ability to specify which image(s) to build, or not, using Maven profiles.
Since the configuration is a monolithic XML block or file, it's impossible to build a certain image only if a certain precondition is met (e.g. build the frontend HTTP server only if I'm building the frontend).

Duplicating and splitting the d-m-p configuration over multiple profiles is, of course, possible but suboptimal.

### Info

* d-m-p version : 0.31.1
* Maven version (`mvn -v`) : 3.5.2
* Docker version : 18.09.7
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :

We have profiles that control whether to build (or not) the frontend and/or that customize the build for specific customers. However, we cannot easily combine those with d-m-p.

* Sample project: https://github.com/ManyDesigns/Portofino.git (look into the demo-tt directory for an example).

**Comment by rhuss** [comment]
I'm afraid I don't have a good answer. Maven profiles' plugin configuration can not easily be combined when multiple profiles are activated. So if you split the image configuration over multiple profiles then you would have to call Maven for each profile separately.

The only way I know how to combine plugin configurations is via inheritance like e.g. described in https://blog.sonatype.com/2011/01/maven-how-to-merging-plugin-configuration-in-complex-projects/

Even here the complex configuration of dmp might not be a good fit here. You can also try to use the other configuration options, like plain Dockerfiles or the property based configuration as described in the documentation.

**Comment by alessiostalla** [comment]
Thanks @rhuss . I was thinking that adding a flag to `<image>`, say, `<skip>true|false</skip>`, would be enough. d-m-p configuration would still be monolithic, but we could then turn on and off parts of it according to properties set by other profiles. What do you think?

**Comment by rhuss** [comment]
We already have several skip options on various levels, so they might be already achieve what you need ? See https://dmp.fabric8.io/ and look for `skip` (e.g. in https://dmp.fabric8.io/#build-configuration which is part of <image><build>)

But probably the new alternative configuration syntax might be useful to you, which allows easy merging of image configuration. This has just been released as part of 0.32.0. See the documentation https://dmp.fabric8.io/#image-configuration, check for `imagesMap`. Also, the discussion in the PR introducing this feature might be useful to you: https://github.com/fabric8io/docker-maven-plugin/pull/1259

**Comment by alessiostalla** [comment]
Oh, great! That's exactly what I needed! Sorry, I had totally not seen that, or maybe it wasn't there when I looked (0.32.0 was not out yet).
