### ISSUE TITLE
volumes not binding

### ISSUE THREAD

**Issue by koren-gershoni** [fabric8io/docker-maven-plugin#1316]
I am using docker-maven-plugin to run an image from a remote repository.

The image is running using docker:start but it seems like the volumes not working.

I run the command using groovy (Jenkins):

`sh(script:"mvn -B -gs ${cfg} -f lib/pom.xml docker:start", returnStatus: true)`
my pom.xml code is:
<img width="334" alt="Untitled2" src="https://user-images.githubusercontent.com/57925934/72158584-3f307100-33c3-11ea-8d84-ea113f4eb4e9.png">

any idea what is going wrong?

**Comment by rhuss** [comment]
Are you running against a remote Docker daemon ? If so, then volume binding is not possible.

**Comment by koren-gershoni** [comment]
> Are you running against a remote Docker daemon ? If so, then volume binding is not possible.
@rhuss 
I am not sure if I understood you well.
I'll explain better:
I made a docker image using docker, and then I hosted it in a repository.
Now I run this docker-image which located in the repository and use volume binding.
It is not possible? if no, something else I can do?

**Comment by rhuss** [comment]
It all depends what Docker daemon you are using. Is it Docker Desktop on Mac or Windows, accessing it via a unix socker or named pipes ? Is it a remote Docker daemon that you access over TCP (i.e. a port) ?

Also the mapping you are configured looking suspicious. The first part should point to a directory on your local machine. See https://dmp.fabric8.io/#start-volumes for more details.

**Comment by koren-gershoni** [comment]
@rhuss 
It is a remote Docker daemon that accesses over TCP, runs on centOS.
So is it not possible to do volume binding?

**Comment by rhuss** [comment]
No

**Comment by rhuss** [comment]
If it doesnt work with plain Docker, it obviously won't work with d-m-p.
