### ISSUE TITLE
Failed to execute goal io.fabric8:docker-maven-plugin:0.33.0:build (docker-build) on project openid-connect-server: Execution docker-build of goal io.fabric8:docker-maven-plugin:0.33.0:build failed: Unable to load the mojo 'build' in the plugin 'io.fabric8:docker-maven-plugin:0.33.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: io/fabric8/maven/docker/BuildMojo : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by vmalhotra22** [fabric8io/docker-maven-plugin#1325]
Hi All,

I have started to build docker using the Maven's plugin called docker-maven-plugin.

But I am stuck at the error given below.

"Failed to execute goal io.fabric8:docker-maven-plugin:0.33.0:build (docker-build) on project openid-connect-server: Execution docker-build of goal io.fabric8:docker-maven-plugin:0.33.0:build failed: Unable to load the mojo 'build' in the plugin 'io.fabric8:docker-maven-plugin:0.33.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: io/fabric8/maven/docker/BuildMojo : Unsupported major.minor version 52.0"

my maven version is 3.0.5
my docker verson hosted on a separate server is there which I have defined using 

<plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <configuration>
				<verbose>true</verbose>
                <dockerHost>http://172.xx.1.xxx:2375</dockerHost>
                <images>
                    <image>
                    <name>${project.version}</name>
                    <alias>openid-connect</alias>
                    <build>
                            
                            <dockerFileDir>${project.basedir}/src/main/docker</dockerFileDir>
                            <assembly>
                                <descriptorRef>artifact</descriptorRef>
                            </assembly>
                    </build>
                    </image>
                </images>
                </configuration>
                <executions>
                    <execution>
                        <id>docker-build</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>		
            </plugin>      
            <plugin>

Please let us know what could be the issue. This is coming for both Fabrio8 and spotify plugins.

Cheers

**Comment by rhuss** [comment]
You should check your java version. dmp needs at least Java 8.

Let me close this issue (its pretty evident that its a Java version mismatch), but don't hesitate to reopen it if you think it still a bug of dmp.
