### ISSUE TITLE
Volume binding bug in windows

### ISSUE THREAD

**Issue by giovannicuccu** [fabric8io/docker-maven-plugin#1338]
### Description
I think volume binding in windows has a bug.
Consider this snippet
```
<volumes>
  <bind>
        <volume>${settings.localRepository}/../:/var/maven/.m2</volume>
   </bind>
</volumes>
```
on a windows pc it can resolve to C:\Users\giovanni\.m2\repository/../
If you run the plugin with this volume configuration the container does not start and report File not found
If you use an explicit Windows path value like this one
```
<volumes>
  <bind>
        <volume>C:\Users\giovanni\.m2\:/var/maven/.m2</volume>
   </bind>
</volumes>
```
the container starts correctly
Looking at the code it seems that in class VolumeBindingUtil

`public static String resolveRelativeVolumeBinding(File baseDir, String bindingString) `

the code applies
 
`resolvedFile.getCanonicalFile().getAbsolutePath()`

only to relative paths

On windows the canonicalization operation it's needed even on absolute paths since it translates 
C:\Users\giovanni\.m2\repository/../ to C:\Users\giovanni\.m2

### Info

* d-m-p version : all 
* Maven version (`mvn -v`) : 3.6.1

I don't think the problem is bound to a specific maven version

**Comment by rhuss** [comment]
Good find. Can you craft a PR to fix it ? That would be awesome !
