### ISSUE TITLE
Tag an already built image

### ISSUE THREAD

**Issue by codepitbull** [fabric8io/docker-maven-plugin#1351]
### Description
Sorry for asking this question here, couldn't find a more appropriate channel.

I am currently migrating an old build chain to this plugin, os far everything works like a charm.

The only thing I don't get is how to tag and push an already built image.
I need this since our images go through several stages until they are promoted to a full release and I don't want to rebuild all of them for promoting.

To do this I need to add tags well after the images have been built.

Is this actually possible?

**Comment by rhuss** [comment]
This sound like a valid use-case, but I'm afraid dmp supports tagging only as part of a build. I can see that a `docker:tag` goal could make sense, or a mode `tagOnly` for `docker:build` (which would be a bit hackish though).

From where do you get the tag value (is it something hardcoded in the pom) ?

As a possible workaround I could see that you already tag with that finally tag during `docker:build`, before going through the pipeline, and configure individual `docker:push` tasks with appropriate filter config to individually push tags (see https://dmp.fabric8.io/#docker:push). However, this of course against the spirit of CD, where you should only "stamp" an image when it passes the various CI stages (and when the "stamp" is a tag).

Unfortunately I don't have any time for implementing a separate `tag` goal, but I or @rohanKanojia  would help anyone to integrate a PR for a `TagMojo`.

**Comment by codepitbull** [comment]
Thanks a lot for your reply (and your amazing plugin).

I just saw that @rohanKanojia already worked omn this.

Thank you so much!

I will keep the small shell skript until the work of @rohanKanojia is available, it's a sm all price to pay when replacing a rake-build with a maven-build ;)
