### ISSUE TITLE
how do i get a random container name on docker:start?

### ISSUE THREAD

**Issue by jgangemi** [fabric8io/docker-maven-plugin#1352]
howdy! been a while, eh @rhuss? 

i see that #1004 introduced a new way to name containers at run time, but i don't see any option to continue using a random container name at start up. is this still possible?

how else would i resolve container naming conflicts on my build server if i have two jobs that use the same container (via parent pom) configuration running at the same time?

**Comment by rhuss** [comment]
I see your point, but I wonder whether we should reintroduce it via a special placeholder or by other means. But would be happy to integrate the PR with some extra checks.

**Comment by rohanKanojia** [comment]
@jgangemi : Hi, since #1410 is merged; Shall we close this issue?

**Comment by jgangemi** [comment]
sure! any idea when it might be released?

**Comment by rohanKanojia** [comment]
I'm planning to cut a release near month's end. I'll let you know whenever we release 0.35.0
