### ISSUE TITLE
Apply replacements to additional tags in:  tags/tag

### ISSUE THREAD

**Issue by Xyaren** [fabric8io/docker-maven-plugin#1367]
This should be allowed:
```
<tags>
  <tag>%t</tag>
  <tag>%l</tag>
</tags>
```
But sadly isn't:
`  * tag part '%t' doesn't match allowed pattern '^[\w][\w.-]{0,127}$'`

Replacements should be applied to the additional tags aswell.

**Comment by rhuss** [comment]
May I ask you what your use case is for using these tags ? 

I remember darkly that the validation for tag values was the pattern referenced in the error message, but if you have a better reference for the pattern allowed for tags, please let me know.

**Comment by Xyaren** [comment]
I would like to create an image i.e. with "latest" (if SNAPSHOT) "version-123456" (date) AND the exact defined verison develop-SNAPSHOT.
The replacements are not working in the additional tags like they do in the "real" tag

**Comment by rhuss** [comment]
I see. thought first that you wanted to use these tags literally :)

I think that is definitely a good idea and I happely would help to integrate a pull request with this feature (but don't have enough time to work on it on my own)
