### ISSUE TITLE
"skipPush" introduced an NPE when pushing

### ISSUE THREAD

**Issue by towtow** [fabric8io/docker-maven-plugin#1380]
See https://github.com/fabric8io/docker-maven-plugin/commit/493aa8be14c642fc148c0a0eed717945ef9ef40f#r42621565

Happens when pushing if `<images>` contains an `<image>` that doesn't have a `<build>` element.

**Comment by rohanKanojia** [comment]
@towtow: Could you please create a PR to fix it?

**Comment by rhuss** [comment]
thanks for the finding ! A PR would be cool as well as unit test that checks for that behaviour.

**Comment by rhuss** [comment]
I consider this a prio 1 issue as this affects everyone without a build configuration (e.g. only a run configuration)

**Comment by towtow** [comment]
Yeah, just found some time to do it. PR sent including test.
