### ISSUE TITLE
0.34.0 and 0.34.1 fail with "Unsupported or unrecognized SSL message"

### ISSUE THREAD

**Issue by pe-st** [fabric8io/docker-maven-plugin#1382]
### Description

After updating the d-m-p to version 0.34.0 the build on our Jenkins Build server fails with
```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.34.1:build (build-start-docker) on project XXX: Cannot create docker access object : Unsupported or unrecognized SSL message
```

Rolling back to d-m-p version 0.33.0 fixes the build. I also tried with the new release 0.34.1, but it failed as well.

On my local workstation I have no such problems.

The project is not public, so I can't share a link to it. But if you need more information I should be able to get it.

### Info

* d-m-p version : 0.34.0
* Maven version (`mvn -v`) : 3.6.1
```

```
* Docker version : Docker version 1.13.1, build 64e9980/1.13.1
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
@pe-st : What's version of docker on your Jenkins? Is it same as your local docker version?

**Comment by pe-st** [comment]
> @pe-st : What's docker/jdk version is your jenkins instance running on? Is it same as your local docker version?

```
Jenkins: jdk-11.0.3+7,  Docker Version:         1.13.1 / API version:     1.26
local  : jdk-11.0.7+10, Docker Version:        19.03.5 / API version:     1.40
```

**Comment by rohanKanojia** [comment]
hmm, seems like somehow dmp has broken backward compatibility for older versions. Would it be possible for you to set up docker 1.13.1 on your local machine and do a git bisect to see why it's failing?

**Comment by pe-st** [comment]
It seems that the commit https://github.com/fabric8io/docker-maven-plugin/commit/dba617ea5137aa9c357ab314cef7ee6e77a80c2b#diff-c9c2f37e986a0ff74e5e7c340ace74e8 on EnvUtil.java is the culprit. See issue https://github.com/fabric8io/docker-maven-plugin/issues/1359 and PR https://github.com/fabric8io/docker-maven-plugin/issues/1360. @rhuss even mentioned that people might be affected ;-) : https://github.com/fabric8io/docker-maven-plugin/pull/1360#issuecomment-667867080

The cause in my case is that the Jenkins build server has a non-standard port in its configuration as docker host: `tcp://myjenkins.domain.tld:4243`. Before the change `tcp` was replaced by `http`, now it's replaced by `https`.

I guess I'd just have to change the configuration of the Jenkins build server to `http://myjenkins.domain.tld:4243`, as the [documentation](https://dmp.fabric8.io/) mentions `tcp:` only for ports 2375 and 2376 anyway?

**Comment by rhuss** [comment]
@pe-st Sorry that this change bite you, but I found it reasonable to switch over to https by default (except for the standard port that is known to be connected to http). It's a bit unfortunate that Docker decided to skip the protocol from their connect URL scheme in the beginning (replacing it with `tcp:` which can be anything on L7).

And you are right, the solution to explicittly select the scheme as you suggest.

Please let us know if this solves the issue so that we can close the issue then.

Apologies for any inconvenience.

**Comment by pe-st** [comment]
@rhuss I managed to change the build server configuration and it works now, so I'll close the issue.

Maybe it would be an idea to emit some warning if somebody uses an unsupported port with the `tcp:` protocol?

**Comment by nodece** [comment]
I submitted https://github.com/fabric8io/docker-maven-plugin/pull/1613 for covert the tcp protocol to http protocol.
