### ISSUE TITLE
"Multiple entries with same key" when building an image

### ISSUE THREAD

**Issue by sabi0** [fabric8io/docker-maven-plugin#1407]
Linux environment variables are case sensitive. But it seems the plugin transforms them all to lower case.

And then a directive like this in a base image:
```
ENV HTTP_PROXY=... http_proxy=...
```
results in the following error: "Multiple entries with same key: http_proxy=... and http_proxy=..."
(Caused by Guava's ImmutableMap?)

P.S. 0.26.1 did not have this problem. 0.31.0 has it. So it was introduced somewhere between these two versions.

**Comment by sabi0** [comment]
Actually I am not sure anymore the two entries come from the base image `ENV`.
I switched to azul/zulu-openjdk-alpine:11 and somehow I still see those duplicate http_proxy entries referring to our internal proxy host. I have no idea where they come from.
But I am positive that version 0.26.1 does not complain about this.

**Comment by sabi0** [comment]
I think I figured it out.
Our company's "root POM" defines these properties:
```
<http_proxy>http://proxy.example.org:8080</http_proxy>
...
<docker.buildArg.http_proxy>${http_proxy}</docker.buildArg.http_proxy>
```

And that apparently results in duplicate entries error.

**Comment by sabi0** [comment]
This problem was introduced by #409 fix.

**Comment by rohanKanojia** [comment]
Closed by https://github.com/fabric8io/docker-maven-plugin/pull/1600
