### ISSUE TITLE
Documentation: incomplete sentence

### ISSUE THREAD

**Issue by cipo7741** [fabric8io/docker-maven-plugin#1414]
https://dmp.fabric8.io/#docker:start
 docker-maven-plugin/src/main/asciidoc/inc/start/_overview.adoc 

That similar to the option -i for docker run.
_guess it should be_
That is similar to the option -i for docker run.

Thanks for this amazing docker-maven-plugin! 👍

**Comment by rohanKanojia** [comment]
@cipo7741: Thanks for reporting :-) . Feel free to submit a PR for this :+1:

**Comment by rhuss** [comment]
thank's @cipo7741 for reporting and for pointing out the issue.

I'm going to add it directly in the source code, no need to fight with github for the fix. 

Tip: There is a "Edit" button on each file on the GitHub UI. When you use this, this will create a fork, a branch and PR when you save it. That's often easier for small fixes like doc fixes, than going through the whole GitHub ceremony.
