### ISSUE TITLE
unittests doesn't pass on Win

### ISSUE THREAD

**Issue by omyl** [fabric8io/docker-maven-plugin#1416]
### Description
build a plugin on Win platform fails due failed tests

### Info

* d-m-p version : 0.34.0
* Maven version (`mvn -v`) : 3.6.3
```

**Comment by rohanKanojia** [comment]
@omyl : Could you please share those problematic tests which are failing?

**Comment by omyl** [comment]
![obrazek](https://user-images.githubusercontent.com/5655084/101385207-bfa16f80-38bb-11eb-9454-2f98ce1778ca.png)
