### ISSUE TITLE
Environment variables should not be interpolated into Dockerfile

### ISSUE THREAD

**Issue by NancyChunlan** [fabric8io/docker-maven-plugin#1423]
### Info

* d-m-p version : 0.33.0 - 0.34.1
* Maven version (`mvn -v`) :
```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: /proj/tools/maven/apache-maven-3.5.4
Java version: 1.8.0_251, vendor: Oracle Corporation, runtime: /proj/tools/jdk/jdk1.8.0_251/jre
Default locale: en_US, platform encoding: ISO-8859-1
OS name: "linux", version: "3.10.0-1062.18.1.el7.x86_64", arch: "amd64", family: "unix"

```
* Docker version : 19.03.3
* If it's a bug, how to reproduce : 
* If it's a feature request, what is your use case : $JAVA_HOME are always used in Dockerfile to indicate JAVA execution, it should be replaced by the env variables in build host.
* Sample project : *[GitHub Clone URL]*

**Comment by rhuss** [comment]
Thanks for the report. Could you please provide a specific example where you see that an environment variable (from the environment where Maven is running ?). Actually, there only support for Maven property interpolation by default, see subsection "Filtering" in http://dmp.fabric8.io/#docker:build, I'm not aware of any interpolation of environment variables.

**Comment by rhuss** [comment]
This is issue is a duplicae of #1433 , so let's followup over there.
