### ISSUE TITLE
Documentation incorrectly states "memorySwap ... use -1 to disable swap"

### ISSUE THREAD

**Issue by cdlans** [fabric8io/docker-maven-plugin#1424]
### Description

The documentation at https://dmp.fabric8.io/#start-configuration describes element `memorySwap` as:
> Total memory usage (memory + swap); use -1 to disable swap.

However the [Docker documentation](https://docs.docker.com/config/containers/resource_constraints/#--memory-swap-details) states:
> If `--memory-swap` is explicitly set to `-1`, the container is allowed to use unlimited swap, up to the amount available on the host system.

This is quite the opposite. As far as I can see in the code, the value of `memorySwap` is passed directly to the Docker API so I believe the d-m-p documentation is incorrect.

If you can confirm this, I will be happy to submit a PR.

### Info

* d-m-p version : 0.34.1

**Comment by rohanKanojia** [comment]
Thanks for reporting. Feel free to create PR :-)

**Comment by cdlans** [comment]
Hi @rohanKanojia, I created a PR: https://github.com/fabric8io/docker-maven-plugin/pull/1426
