### ISSUE TITLE
Documentation has wrong <entryPoint> configuration option spelling

### ISSUE THREAD

**Issue by sabi0** [fabric8io/docker-maven-plugin#1449]
http://dmp.fabric8.io/#misc-startup says:
> Using `entrypoint` and `cmd` it is possible ...

This is followed by an example:
```
<entrypoint>
   <!-- shell form  -->
   <shell>java -jar $HOME/server.jar</shell>
</entrypoint>
```

But the actual configuration parameter name is in camel-case - `entryPoint`:
https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java#L146

**Comment by rohanKanojia** [comment]
@sabi0 : Thanks a lot for reporting this! Would appreciate if you raise a quick PR to fix this

**Comment by holleyism** [comment]
Ran into this today.  Submitted PR https://github.com/fabric8io/docker-maven-plugin/pull/1461
