### ISSUE TITLE
mvn docker stop from CLI

### ISSUE THREAD

**Issue by pantinor** [fabric8io/docker-maven-plugin#1458]
If we start several containers with the docker plugin using "mvn docker:start", is it possible to invoke mvn docker:stop but indicate only one of the containers to stop, ie by using an alias tag with the goal?  Thanks.

**Comment by rohanKanojia** [comment]
We do seem to have some containerNamePattern for starting and stopping containers: https://dmp.fabric8.io/#docker:stop . Could you please check if this helps?

**Comment by pantinor** [comment]
This has odd behaviour when running command such as : 
**mvn docker:stop -Ddocker.containerNamePattern=data-store-2**
This appears to have stopped all the **other** containers except the ones that have "data-store" in the name.
Thanks for any ideas.

**Comment by pantinor** [comment]
My ultimate goal is to do this from java programmatically, so maybe better to use the rest API?  If we have any java examples that show how it might be done would also appreciate it. Thanks.

**Comment by pantinor** [comment]
I was able to get this working using docker java APIs such as below:

DockerClient dockerClient = DockerClientBuilder.getInstance().build();
List<Container> containers = dockerClient.listContainersCmd().exec();
Container ds2 = null;
Container ds3 = null;
for (Container c : containers) {
	System.out.printf("%s %s %s\n", c.getId(), Arrays.toString(c.getNames()), c.getCommand());
	if (Arrays.toString(c.getNames()).contains("data-store-2")) {
		ds2 = c;
	}
	if (Arrays.toString(c.getNames()).contains("data-store-3")) {
		ds3 = c;
	}
}

dockerClient.stopContainerCmd(ds2.getId()).exec();
dockerClient.stopContainerCmd(ds3.getId()).exec();
