### ISSUE TITLE
A placeholder in docker.image.tag isn't replaced by the final result when used during docker:build

### ISSUE THREAD

**Issue by henri-tremblay** [fabric8io/docker-maven-plugin#1468]
### Description

If the property `docker.image.tag` is set to `%l` and used in the image name, `docker:build` will fail to replace `%l` in the image name.

### Info

*  See https://github.com/henri-tremblay/docker-bug to reproduce
*  Just do `mvn docker:build`

The cause is that FormatParameterReplacer will do a lookup. In the lookup we get the `docker.image.tag` property but return directly instead of trying to replace the `%l`. Mysteriously, we only do that for `docker.image.tag` and not `docker.image.repo` or anything else.

See the demo project above to reproduce but the layout is:

```xml
  <properties>
    <docker.image.tag>%l</docker.image.tag>
    <docker.image.name>%a</docker.image.name>
    <docker.image.repo>${docker.image.name}</docker.image.repo>
  </properties>
```

```xml
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.35.0</version>
        <configuration>
          <images>
            <image>
              <name>${docker.image.repo}:${docker.image.tag}</name>
              <build>
                <from>adoptopenjdk:11-jre-hotspot</from>
              </build>
            </image>
          </images>
        </configuration>
      </plugin>
```

**Comment by rohanKanojia** [comment]
@henri-tremblay: Thanks for reporting, Would you like to submit a fix for this issue?
