### ISSUE TITLE
<image> -> <registry> not used by docker:build goal, during image tagging

### ISSUE THREAD

**Issue by jacekwzg** [fabric8io/docker-maven-plugin#1473]
### Description
`mvn docker:build` tagging behaves differently for the following cases:
1. if <name> contains registry part, built image tag contains registry part
2. if registry is specified in <registry>, it's not present in image tag

This behavior is at least inconsistent, if not a bug. 
IMO it seems reasonable to use <registry> during `mvn docker:build` tagging.

### Info

* docker-maven-plugin version : 0.28.0, 0.35.0
* Maven version (`mvn -v`) : 
```
Apache Maven 3.6.3
Java version: 1.8.0, vendor: Oracle Corporation
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", arch: "amd64", family: "unix"
```
* Docker version : 19.03.5
* If it's a bug, how to reproduce :
case 1:

```xml
<image>
  <registry>reg</registry>
  <name>name</name>
```
builds an image tagged with _name_

case 2:
```xml
<image>
  <name>reg/name</name>
`
builds an image tagged with _reg/name_

**Comment by rhuss** [comment]
Yes, this is expected behaviour. See http://dmp.fabric8.io/#registry for the reasoning and a detailed explanation.

In short: `<registry>` is used for push/pull operations only, but does not affect the naming when building.
