### ISSUE TITLE
Plugin doesn't abort building an image in case Podman is used and the Dockerfile can't be processed

### ISSUE THREAD

**Issue by jh-cd** [fabric8io/docker-maven-plugin#1512]
### Description

Short:

Podman's response for POST /build lacks of header "Content-Type: application/json".

Long:

When triggering a build, docker-maven-plugin sends a POST /build request and checks the response.
The response is 200 OK despite the build result, so docker-maven-plugin checks for errors in the response's content.
It does this by checking the headers for "Content-Type: application/json". If given, it checks if the response contains an "error" object. If present, docker-maven-plugin raises an exception to stop the Maven build.

The code in HcChunkedResponseHandlerWrapper is:

```
    public Object handleResponse(HttpResponse response) throws IOException {
        try (InputStream stream = response.getEntity().getContent()) {
            // Parse text as json
            if (isJson(response)) {
                EntityStreamReaderUtil.processJsonStream(handler, stream);
            }
        }
        return null;
    }

    private static boolean isJson(HttpResponse response) {
        return Stream.of(response.getAllHeaders())
                .filter(h -> h.getName().equalsIgnoreCase("Content-Type"))
                .anyMatch(h -> h.getValue().toLowerCase().startsWith("application/json"));
    }
```

And the handler BuildJsonResponseHandler is:

```
    public void process(JsonObject json) throws DockerAccessException {
        if (json.has("error")) {
            String msg = json.get("error").getAsString();
            String detailMsg = "";
            ...
            throw new DockerAccessException(...);
        ...
```

In case Podman is used, no "Content-Type: application/json" is given, nor any "Content-Type" at all. docker-maven-plugin won't parse the response-content for errors, and won't raise an exception to stop the Maven build.

A workaround is needed.

### Versions

Maven:

    $ mvn -v
    Apache Maven 3.6.3
    Maven home: /usr/share/maven
    Java version: 1.8.0_312, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
    Default locale: en_US, platform encoding: UTF-8
    OS name: "linux", version: "5.11.0-43-generic", arch: "amd64", family: "unix"

Plugin:

    <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.38.1</version>
    </plugin>

Podman:

podman version 3.4.2

**Comment by rohanKanojia** [comment]
@jh-cd : Hi, Do you plan to contribute a fix upstream for this issue?

**Comment by jh-cd** [comment]
@rohanKanojia Yes, I created PR #1585.

**Comment by manusa** [comment]
![image](https://user-images.githubusercontent.com/488391/181273006-45ace6bb-fb45-4093-9929-2134de89ee6e.png)
