### ISSUE TITLE
'docker.buildx.*' properties seem to be ignored

### ISSUE THREAD

**Issue by dvallant** [fabric8io/docker-maven-plugin#1568]
### Description
As the title says, all 'docker.buildx.*' properties seem to be ignored, whether set as maven properties or as system properties via command line.

### Info

* docker-maven-plugin version : 0.40.0 and 0.41.0-SNAPSHOT
* Maven version (`mvn -v`) : 
```
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/maven
Java version: 11.0.15, vendor: Private Build, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.13.0-44-generic", arch: "amd64", family: "unix"
```
* Docker version : Docker version 20.10.17, build 100c701
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by chonton** [comment]
The documentation for [Properties](https://dmp.fabric8.io/#property-configuration) states: `A build configuration is only created when a docker.from or a docker.fromExt is set.`

Comment in [PropertyConfigHandler](https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java#L106) states `Enable build config only when a '.from.', '.dockerFile.', or '.dockerFileDir.' is configured`

Are any of these properties also set?

**Comment by dvallant** [comment]
My pom.xml configuration looks like this:
```
<configuration>
    <images>
        <image>
            <name>${docker.registry}/${docker.registry.path}/${docker.image.name}</name>
            <build>
                <dockerFile>${project.build.directory}/docker-src/Dockerfile</dockerFile>
                <contextDir>${project.basedir}</contextDir>
            </build>
        </image>
    </images>
</configuration>
```
So 'dockerFile' is configured.

**Comment by chonton** [comment]
dockerFile must be configured from a property.  Quoting from [Properties](https://dmp.fabric8.io/#property-configuration):

> By default, property based configuration uses only properties, ignoring any &lt;build> and &lt;run> sections. To combine values from both sources, use the [property mode configuration](https://dmp.fabric8.io/#combining-property-config).

**Comment by dvallant** [comment]
@chonton Thanks for pointing out the documentation. I unfortunately overlooked that :-/
After some tries I got it to work, but i had to use 'docker.buildx.platform**s.0**' to set the build platform not 'docker.buildx.platform' as the documentation says.

So I think the issue can be closed. Thx

**Comment by chonton** [comment]
@rohanKanojia please close
