### ISSUE TITLE
Confused about buildx behavior

### ISSUE THREAD

**Issue by marcelstoer** [fabric8io/docker-maven-plugin#1576]
Context: I am migrating from [spotify/dockerfile-maven](https://github.com/spotify/dockerfile-maven) to this plugin. The recent introduction for buildx support made us tackle this long overdue migration.

Use case: build an image from `Dockerfile` in `package` phase, tag it with two tags, push image with one of the tags to internal Docker registry in `deploy` phase.

_If there's a better way to ask for community support please let me know. It's not ideal to create an issue, I know._

### Description

The way I interpreted the documentation the following configuration should implement my use case.

```xml
<properties>
    <docker.image-name>hello/multiarch</docker.image-name>
    <docker.docker-file>${project.basedir}/Dockerfile</docker.docker-file>
...
</properties>

<build>
    <plugins>
        <plugin>
            <groupId>io.fabric8</groupId>
            <artifactId>docker-maven-plugin</artifactId>
            <version>0.40.1</version>
            <!-- [package] build Docker image with two tags -->
            <!--           * master                                            -->
            <!--           * $project.version                             -->
            <!-- [deploy] publish the image with the $project.version tag -->
            <configuration>
                <images>
                    <image>
                        <name>${docker.image-name}:${project.version}</name>
                        <registry>docker.io</registry>
                        <build>
                            <dockerFile>${docker.docker-file}</dockerFile>
                            <args>
                                <DOCKER_IMAGE_VERSION>${project.version}</DOCKER_IMAGE_VERSION>
                            </args>
                            <!-- tags *in addition* to potential tag included in the <image><name> -->
                            <tags>
                                <tag>master</tag>
                            </tags>
                            <buildx>
                                <platforms>
                                    <platform>linux/amd64</platform>
                                    <platform>linux/arm64</platform>
                                </platforms>
                            </buildx>
                        </build>
                    </image>
                </images>
            </configuration>
            <executions>
                <execution>
                    <id>build-image</id>
                    <goals>
                        <goal>build</goal>
                    </goals>
                    <phase>package</phase>
                </execution>
                <execution>
                    <id>push-image-version</id>
                    <goals>
                        <goal>push</goal>
                    </goals>
                    <phase>deploy</phase>
                    <configuration>
                        <!-- even though we built an image with two tags, only push one of them -->
                        <filter>${docker.image-name}:${project.version}</filter>
                    </configuration>
                </execution>
            </executions>
        </plugin>
...
    </plugins>
</build>
```

### Issues

Issue 0: the Docker push fails but there are separate issues file for this already e.g. #1574.

Issue 1: since I defined two executions, Docker builds the whole image _twice_. Hence, the Maven `push` goal includes the `build` goal. The effective command is something like `docker ... buildx build ... --push ...`. In fact, the only difference between the two executions is the inclusion of `--push` in the later. They're identical otherwise.

Issue 2: the layers of the parent image are pulled down for every Docker build. I expected them to be cached by default between builds (unless they change of course).

What are the remedies for issues 1 & 2?

### Info

```
* docker-maven-plugin version : 0.40.1
* Maven version (`mvn -v`) : 3.8.5
```

```
* Docker version :
* If it's a bug, how to reproduce : 20.10.16
```

**Comment by chonton** [comment]
Unfortunately, I could not figure out how to push without rebuilding.  

I would like to keep the behavior similar to non-platform builds; build first, test image locally, then push to registry.

The rebuild **should** use the cache and not re-pull parent image.  However, even though the parent image is saved in the local cache, it will be re-pulled.  I do not know if this is a buildx bug or if I am using the wrong options.

**Comment by marcelstoer** [comment]
> The rebuild should use the cache and not re-pull parent image.

I started with your multi-arch example at https://github.com/fabric8io/docker-maven-plugin/tree/master/samples/multi-architecture and modified it such that it uses `Dockerfile` (instead of the XML assembly). I observe that every time you run `mvn install` it pulls the ~130MB * number-of-platforms for the `openjdk:jre` image.

**Comment by chonton** [comment]
Most likely the cache remains on the builder instance.  If you remove and recreate the builder instance between build and push, the parent image is likely re-pulled.

**Comment by chonton** [comment]
Proposal 1.
Remove use of local cache. Keep builder instances between stages. Add a goal to remove builder instances.

Proposal 2.
Keep local cache and remove use of buildx to load and push. Use docker API to load native image from local cache. Use registry API to push images from local cache.

Proposal 3.
Create new buildx goal and let developers determine choose options.

Proposal 4.
Change build goal to only create native platform image and load to local registry.  Push goal will continue to build and push all specified platforms.

**Comment by marcelstoer** [comment]
@chonton Thanks for the buildx-integration improvements and your valuable feedback.

I've since also learned that my old sequence of build steps simply isn't possible with buildx. I didn't realize I can't separate the build-tag-push steps as I only ever used buildx with `--push` straight out of the book.
