### ISSUE TITLE
Cannot pull from registry I'm logged into

### ISSUE THREAD

**Issue by sofax** [fabric8io/docker-maven-plugin#1607]
### Description
In my _Dockerfile_ I have some FROM commands. One of them targets a protected (GitLab) registry which I am currently logged into. When I try to use the docker-maven-plugin to perform a multi-platform build (i.e. _buildx_), I get:
```
DOCKER> error: failed to solve: failed to fetch anonymous token: unexpected status: 403 Forbidden
```
I can only access that registry from my _Dockerfile_, if the image I am trying to build targets that same registry. So, apparently, my current login status is ignored during the build.

### Info

* docker-maven-plugin version : 0.40.2
* Maven version (`mvn -v`) : 3.6.3
* Docker version : 20.10.17

**Comment by sofax** [comment]
I just discovered, that it works, when I explicitly configure the following options:
```
                  <configFile>config.json</configFile>
                  <dockerStateDir>~/.docker</dockerStateDir>
```
This does not seem to match the [documentation](https://dmp.fabric8.io/#authentication), though, unless that section about registry authentication handling is totally unrelated to the authentication needed when building an image from a Dockerfile.

**Comment by sofax** [comment]
This actually only seems to happen in the GitLab CI pipeline (for jobs running inside a dind container). It works fine locally (unless I am logged into more than one docker registry simultaneously).

**Comment by rhuss** [comment]
Sorry, I can't help here much. For your CI pipeline, you might want to try out one of the many authentication options that are described in https://dmp.fabric8.io/#authentication

I hope you don't mind that I close that issue, but feel free to reopen in case you don't agree.
