### ISSUE TITLE
JIB ignores the DOCKER_REGISTRY environment variable

### ISSUE THREAD

**Issue by johngmyers** [fabric8io/docker-maven-plugin#1617]
### Description

When `docker.build.jib` is set to `true`, the `docker:push` goal ignores the value of the `DOCKER_REGISTRY` environment variable. It instead tries to push to Docker Hub.

When `docker.build.jib` is set to `false`, it correctly pushes to the registry specifed in that environment variable.

### Info

* docker-maven-plugin version : 0.40.2
* Maven version (`mvn -v`) : 3.5.0
```

```
* Docker version :
* If it's a bug, how to reproduce :

1. Specify the image name without a registry.
2. Do not specify the `<registry>` subelement of the `<image>` configuration.
3. Do not specify a global configuration element `<registry>`
4. Set the `DOCKER_REGISTRY` environment variable to a registry other than Docker Hub.
6. Run `mvn -Ddocker.build.jib=true docker:build docker:push`

**Comment by rhuss** [comment]
Good find, it definitely sounds like a bug. Anyboyd volunteering to look into it ?

**Comment by rohanKanojia** [comment]
@johngmyers : Could you please try 0.42.0 to see if it resolves your issue?
