### ISSUE TITLE
Support docker run --platform

### ISSUE THREAD

**Issue by chonton** [fabric8io/docker-maven-plugin#1641]
### Description
docker run has an argument --platform which explicitly specifies the platform image to use.  Support configuring this parameter in the start mojo

### Info

* docker-maven-plugin version : 0.42
* Maven version (`mvn -v`) : 3.9.0
```

```
* Docker version : 20.10.22
* If it's a feature request, what is your use case : Support the --platform argument for docker run

**Comment by chonton** [comment]
@rohanKanojia Thanks for merging. Any plans for a release soon?

**Comment by rohanKanojia** [comment]
I just had published a release last week. Is it okay if I delay it to the end of this month? Or do you need this urgently? (I can try releasing this weekend)

**Comment by chonton** [comment]
End of month is fine.  Thanks.

**Comment by chonton** [comment]
@rohanKanojia Ready to release?

**Comment by rohanKanojia** [comment]
@chonton : Let me cut a release tonight
