### ISSUE TITLE
Fallback to default docker driver to speed-up build time in buildx mode

### ISSUE THREAD

**Issue by tfactor2** [fabric8io/docker-maven-plugin#1658]
### Description

While using buildx mode on M1 Mac, I've noticed that "Sending tarball" phase takes extremely long (tens of seconds), some good explanation is here - https://github.com/docker/buildx/issues/107#issuecomment-1307929258.
This makes the plugin unusable in some cases.

...
As far as I see, the plugin builds the image matching host architecture in the build phase, skipping other architectures and using buildx to load the image to local registry (`--load` flag).
It looks like buildx (more specifically `docker-container` driver)  is not optimized for local loading.

My proposal is always to use legacy non-buildx way in build phase and use buildx only on push phase even if `<buildx>` is present in maven configuration . WDYT?

### Info

* docker-maven-plugin version: `0.41.0`
* Maven version (`mvn -v`) : `3.8.6`
* Docker version: `23.0.1`

**Comment by chonton** [comment]
You can accomplish this by using a profile that configures buildx platform.  For example:

In your global properties:
```xml
  <properties>
    <docker.platforms></docker.platforms>
  </properties>
```

In the plugin setup:
```xml
          <plugin>
            <groupId>io.fabric8</groupId>
            <artifactId>docker-maven-plugin</artifactId>
            <configuration>
              <images combine.children="append">
                <image>
                  <name>${docker.registry}/${docker.repository}:${docker.image.tag}</name>
                  <build>
                    <buildx>
                      <platforms>
                        <platform>${docker.platforms}</platform>
                      </platforms>
                    </buildx>
                  </build>
                </image>
              </images>
            </configuration>
            <executions>
              <execution>
                <id>docker-build</id>
                <goals>
                  <goal>build</goal>
                </goals>
                <phase>package</phase>
              </execution>
              <execution>
                <id>docker-push</id>
                <goals>
                  <goal>push</goal>
                </goals>
                <phase>deploy</phase>
              </execution>
            </executions>
          </plugin>
```

In your profile:
```xml
    <profile>
      <!-- CI build turns on this profile -->
      <id>CI</id>
      <properties>
        <docker.platforms>linux/amd64,linux/arm64</docker.platforms>
      </properties>
    </profile>
```

**Comment by tfactor2** [comment]
Wow, thanks.
For me, it looks implicit.
I only now noticed the block:
```java
    public boolean isBuildX() {
        return !getPlatforms().isEmpty();
    }
```

I would expect that at least the presence of `<buildx>` switches the build to buildx mode but not the presence of platforms. Probably toggles like `useBuildx` would be more clear.

But it's my fault, missed the point in the docu:
> Buildx is enabled when there is a non-empty `<platform>` element inside the  `<buildx>` configuration.
Ticket can be closed.

**Comment by tfactor2** [comment]
On another side, I believe the scenario where multiarch build is done on CI and non-buildx is used locally is quite typical. Would be nice to have a straightforward way to implement it. Or at least, have it described in the docu as @chonton suggested.

**Comment by rohanKanojia** [comment]
@tfactor2 : Could you please modify your PR to improve documentation instead?

**Comment by tfactor2** [comment]
I've reread the docu. The example provided in the Examples section at https://dmp.fabric8.io/#build-buildx is enough for me. The ticket, indeed, can be closed. Thanks, @chonton, @rohanKanojia.

**Comment by tfactor2** [comment]
The problem:
The `buildx` mode doesn't use socket connections but rather a command line to build images. In many CI environments, builds are started in a dedicated container. In the case of maven, it's a maven container based on a standard maven image (e.g., `maven:3.8.6-eclipse-temurin-17`). The image **doesn't contain** docker binaries.

What we do is we build our custom image with docker and buildx included. The approach has its own drawbacks, e.g., we have to rebuild the image each time the base maven image is redeployed under the same tag (for example, to propagate a security fix).

PS: Still trying to decide the right place to ask. I'm asking here because the general configuration that can be used in pipeline setup was mentioned. The result of the discussion could be helpful to others.

**Comment by chonton** [comment]
I use a similar CI setup.

Consider a scenario where docker is updated:
- If the docker executable is located inside the container, the container image must be updated
- If the docker executable outside the container, the host package must be updated

Likewise for maven executable.  Likewise for java executable.  Docker-maven-plugin is dependent on java, maven, and docker (whether that is through cli or rpc) If any dependency has security risk, the supply chain must be updated.  Is it easier to update a single image that contains all dependencies or is it easier to update select packages on a host?  Also, what about build reproducibility?

If you have a concrete suggestion, please open a new issue with a feature request.
