### ISSUE TITLE
[feature request] buildx option to disable attestations

### ISSUE THREAD

**Issue by mprins** [fabric8io/docker-maven-plugin#1661]
### Description
It would be nice to have the option to disable attestation generation when using buildx to work around the problem described here: https://github.com/orgs/community/discussions/45969

### Info

* docker-maven-plugin version : 0.42.0
* Maven version (`mvn -v`) : 
```
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: /opt/apache-maven-3.9.1
Java version: 11.0.18, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.19.0-35-generic", arch: "amd64", family: "unix"
``` 
* docker versions: 
  * Docker version 23.0.1, build a5ee5b1
  * github.com/docker/buildx v0.10.2 00ed17d

* If it's a feature request, what is your use case :
> Prevent having useless OS / Arch combinations when browsing https://github.com/B3Partners/tailormap-api/pkgs/container/tailormap-api this could be circumvented using an environment variable, but that is error prone for both onboarding and established developers

**Comment by rohanKanojia** [comment]
cc @chonton , Would appreciate it if you could share your thoughts on this..

**Comment by chonton** [comment]
Control over attestations sounds like a good feature.
However, the original problem is a UI concern that GitHub should deal with.
