### ISSUE TITLE
Release v0.43.0

### ISSUE THREAD

**Issue by saravanaa14** [fabric8io/docker-maven-plugin#1670]
We are trying to utilize the `attestations` feature in `buildX`, however I do not see it available in the latest release version `0.42.1`. That code is already merged in master. Can you please release a new version out so that we can use it?

**Comment by rohanKanojia** [comment]
I want https://github.com/fabric8io/docker-maven-plugin/pull/1671 to be in for  next release as well. Hopefully within 1-2 weeks we should be able to release.

**Comment by saravanaa14** [comment]
thank you for the update. We will see what we can do in the meantime

**Comment by rohanKanojia** [comment]
@saravanaa14 : Do you need this urgently? Are you blocked on this?

**Comment by rohanKanojia** [comment]
@saravanaa14 : I've released [0.43.0 ](https://repo1.maven.org/maven2/io/fabric8/docker-maven-plugin/0.43.0/)which should contain buildx attestation feature. Please try it out and provide feedback whenever you get time.

Closing this issue.
