### ISSUE TITLE
With 0.43.2 push to Docker Hub is not working any more

### ISSUE THREAD

**Issue by ilgrosso** [fabric8io/docker-maven-plugin#1698]
### Description
The Jenkins job which pushes Apache Syncope images to Docker Hub started failing after upgrading the `docker-maven-plugin` from 0.43.0 to 0.43.2.

Sample job output: https://ci-builds.apache.org./job/Syncope/job/Syncope-3_0_X-deploy/203/console

DockerHub credentials are stored under `~/.m2/settings.xml`

### Info

* docker-maven-plugin version : 0.43.2
* Maven version (`mvn -v`) : 3.6.3
```

```
* Docker version :
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
@ilgrosso : Hello, Could you please provide more details? What error are you getting? What is your plugin configuration?

**Comment by ilgrosso** [comment]
@rohanKanojia the reported error is

```
DOCKER> #44 ERROR: failed to push apache/syncope:3.0.5-SNAPSHOT: push access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

The plugin configuration can be found at https://github.com/apache/syncope/blob/3_0_X/docker/core/pom.xml#L237-L273

**Comment by rohanKanojia** [comment]
@ilgrosso : Do you have docker credentials in repository in this format?
```xml
  <servers>
    <server>
      <id>docker.io</id>
      <username>username</username>
      <password>secret</password>  
    </server>
  </servers>

```

**Comment by ilgrosso** [comment]
@rohanKanojia I've asked the Jenkins admin and will report here, thank you

**Comment by rohanKanojia** [comment]
@ilgrosso : Thanks, I'm just trying to check what could have broken in previous release. We did introduce one change related to auth https://github.com/fabric8io/docker-maven-plugin/pull/1693

**Comment by ilgrosso** [comment]
@rohanKanojia this is their response:

> Yes they are exactly like that
> Or it would not have worked all this time I imagine

**Comment by rohanKanojia** [comment]
Thanks for clarifying! Is this behavior seen only on v0.43.2 or also on v0.43.1?

**Comment by ilgrosso** [comment]
Unfortunately I haven't tried with 0.43.1, just 0.43.0 (working) and 0.43.2 (not working)

**Comment by mprins** [comment]
Also running into this problem with ghcr.io and 0.43.2, this setup was working with 0.43.0 and earlier

Maven settings: https://github.com/B3Partners/tailormap-api/blob/7126ebe39a2c3470a7b247cbf91ef4a01a29c675/.github/maven-settings.xml#L7-L17

pom/config: https://github.com/B3Partners/tailormap-api/blob/7126ebe39a2c3470a7b247cbf91ef4a01a29c675/pom.xml#L1148-L1198

credentials are set from secrets as env variables in: https://github.com/B3Partners/tailormap-api/blob/7126ebe39a2c3470a7b247cbf91ef4a01a29c675/.github/workflows/ubuntu-maven.yml#L168-L178

**Comment by rombert** [comment]
Same here for Apache Sling, Docker pushes have started failing for us since we moved from 0.43.0 to 0.43.2 . See for instance https://github.com/apache/sling-org-apache-sling-starter/actions/runs/5785078688/job/15677027953#step:7:3989

> Failed to execute goal io.fabric8:docker-maven-plugin:0.43.2:build (build-docker-image) on project org.apache.sling.starter: Execution build-docker-image of goal io.fabric8:docker-maven-plugin:0.43.2:build failed: Cannot invoke "String.equalsIgnoreCase(String)" because "configuredRegistry" is null

You can see the pom.xml at https://github.com/apache/sling-org-apache-sling-starter/blob/37a32dde3a3fe9f6b1bad206973909da44ccd875/pom.xml#L267-L357 and the way we trigger the build from GitHub actions at https://github.com/apache/sling-org-apache-sling-starter/blob/37a32dde3a3fe9f6b1bad206973909da44ccd875/.github/workflows/docker-push.yml#L37-L48

Hope this helps.

**Comment by rohanKanojia** [comment]
@ilgrosso  @mprins: Hello, I'm trying to debug this issue. `docker:push` goal seems to print the finally executed `buildx` command in maven logs. Could you guys please provide that ran command with v0.43.0 (working) and v0.43.2 (not working)? It can help in debugging what's portion of buildx command is generated differently in this version.

**Comment by ilgrosso** [comment]
With [0.43.2](https://ci-builds.apache.org./job/Syncope/job/Syncope-3_0_X-deploy/203/consoleFull):

```
docker buildx build --progress=plain --builder maven --platform linux/amd64,linux/arm64 --tag apache/syncope:3.0.5-SNAPSHOT --file=/home/jenkins/jenkins-agent/workspace/Syncope/Syncope-3_0_X-deploy/docker/core/target/docker/apache/syncope/3.0.5-SNAPSHOT/tmp/docker-build/Dockerfile /home/jenkins/jenkins-agent/workspace/Syncope/Syncope-3_0_X-deploy/docker/core/target/docker/apache/syncope/3.0.5-SNAPSHOT/tmp/docker-build --push
```

With [0.43.0](https://ci-builds.apache.org./job/Syncope/job/Syncope-3_0_X-deploy/207/consoleFull):

```
docker --config /home/jenkins/workspace/Syncope/Syncope-3_0_X-deploy/docker/core/target/docker/apache/syncope/3.0.5-SNAPSHOT/docker buildx build --progress=plain --builder maven --platform linux/amd64,linux/arm64 --tag apache/syncope:3.0.5-SNAPSHOT --file=/home/jenkins/workspace/Syncope/Syncope-3_0_X-deploy/docker/core/target/docker/apache/syncope/3.0.5-SNAPSHOT/tmp/docker-build/Dockerfile /home/jenkins/workspace/Syncope/Syncope-3_0_X-deploy/docker/core/target/docker/apache/syncope/3.0.5-SNAPSHOT/tmp/docker-build --push
```

**Comment by rohanKanojia** [comment]
@ilgrosso @mprins @rombert : I've released [0.43.3](https://repo1.maven.org/maven2/io/fabric8/docker-maven-plugin/0.43.3/)  . Could you please try again on this version and see if you're still facing this issue?

**Comment by rombert** [comment]
@rohanKanojia - worked just fine for me, thanks! https://github.com/apache/sling-org-apache-sling-starter/actions/runs/5849388029/job/15857660731

**Comment by ilgrosso** [comment]
I confirm that 0.43.3 is working fine for me as well, thank you very much @rohanKanojia

**Comment by mprins** [comment]
0.43.3 works for me
