### ISSUE TITLE
Volume binding bug in windows

### ISSUE THREAD

**Issue by shi00** [fabric8io/docker-maven-plugin#1713]
I think volume binding in windows has a bug.
Consider this snippet:
```
<volumes>
  <bind>
        <volume>d:\a\b:c:\test</volume>
   </bind>
</volumes>
```
I am using Docker Desktop to run a Windows Container on Windows 10. When starting the container, I hope to perform a mount operation, but unfortunately, the operation failed.
When I checked the log information I found the following error:
`**I/O Error [Unable to create container for [builder-base-windows:1.0.0] : {"message":"invalid volume specification: '/d/a/b:c:/test'"} (Internal Server Error: 500)]**`

It is correct for me to start the container through the command line. The startup command is as follows:
**docker run -it -v D:\a\b:c:\test  builder-base-windows:1.0.0 cmd.exe**

Looking at the code it seems that in class VolumeBindingUtil
public static String resolveRelativeVolumeBinding(File baseDir, String bindingString)
Maybe there is something wrong with this code.

docker-maven-plugin version : 0.43.4
Maven version (`mvn -v`) :
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: D:\apache-maven
Java version: 21, vendor: Azul Systems, Inc., runtime: D:\zulu-21
Default locale: zh_CN, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by bergerst** [comment]
@shi00 Can you test if my fix in #1720 works?

1. Clone my fork and switch to the fix-windows-volume-mounts branch
2. Run `mvn install -DskipTests -Dsonar.skip=true`
3. Change the docker-maven-plugin version in your own project's pom.xml to 0.44-SNAPSHOT
4. Trigger the plugin execution

**Comment by bergerst** [comment]
Since I didn't get a response, I set up a Github workflow to test it and the binding works: https://github.com/bergerst/docker-plugin-windows-showcase/tree/windows-container

You can only bind directories into Windows-based containers according to https://github.com/moby/moby/issues/30555.

**Comment by bergerst** [comment]
@rohanKanojia Can be closed now

**Comment by shi00** [comment]
Hi guy, sorry for the late reply. I have completed the test using the fork you provided, and the result is ok. Thank you for your help.

**Comment by rohanKanojia** [comment]
@shi00 : Thanks for your feedback. I'll cut a new release within a few weeks.
