### ISSUE TITLE
docker-maven-plugin cannot correctly execute dockerfile and build it correctly

### ISSUE THREAD

**Issue by mebest100** [fabric8io/docker-maven-plugin#1723]
### Description
Hi,
Previously I use com.spotify plugin to build docker image, and now try with fabric8io.
But I found a bothring problem that fabric8io cannot correctly execute dockerfile and build it correctly.
below is my dockerfile content:
```
ARG JAR_FILE
FROM openjdk:8-jdk-alpine
WORKDIR /app
COPY target/${JAR_FILE} ./app.jar
ENTRYPOINT ["java", "-Dfile.encoding=UTF-8", "-jar", "app.jar"]
```
below pom.xml part with  fabric8io
```
 <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.43.4</version>
                <executions>
                    <execution>
                        <id>default</id>                     
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                            <goal>push</goal>
                        </goals>
                    </execution>
                </executions>

                <configuration>               
                    
                    <serverId>myHarborRegistry</serverId>

                    <registry>${docker.repostory}</registry>
                    <authConfig>
                        <username>admin</username>
                        <password>Harbor12345</password>
                    </authConfig>
                    <images>                
                        <image>
                            <name>${docker.repostory}/library/${project.artifactId}:${image.tag.verion}</name>
                            <build>
                                <contextDir>${project.basedir}</contextDir>
                            </build>
                        </image>
                    </images>               
                    <dockerHost>http://192.168.10.30:2375</dockerHost>
            
                    <buildArgs>
                        <JAR_FILE>${project.build.finalName}.jar</JAR_FILE>
                    </buildArgs>

                </configuration>
            </plugin>
```
The question is fabric8io totally cannot output the docker images based my dockerfile, it's output is very strange as below pic
![image](https://github.com/fabric8io/docker-maven-plugin/assets/11530991/a2777293-c0a8-419a-adfd-566023a9c0a1)

and when run the image will get error of :  "Error: Invalid or corrupt jarfile app.jar" . Simply to see the output is incorrect.

The correct output shall be as follow which is with com.spotify plugin.

![image](https://github.com/fabric8io/docker-maven-plugin/assets/11530991/b2818d7a-2a8a-4a8a-b0bd-34acbb7550f2)
You can see the workdir and jar file is correclt located with  com.spotify plugin.

But why there is problem with fabric8io. I carefully read your user manual and get no idea about it because the manual is too complicated and no related examples .
Thanks for your help

### Info

* docker-maven-plugin version : 0.43.4
* Maven version (`mvn -v`) :  3.6.3
```

```
* Docker version :  18.09.9
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rhuss** [comment]
Where is your Dockerfile located in the source directories ? (not target/). If not top-level, you need to specify it in the configuration. 

Otherwise you just can rely on the [Simple Dockerfile mode]([Simple Dockerfile build](https://dmp.fabric8.io/#simple-dockerfile-build). You can find quite some examples in https://github.com/fabric8io/docker-maven-plugin/tree/master/samples

**Comment by mebest100** [comment]
I found the cause it's dockerfile problem, I need create the diretory for WORKDIR in advanced, otherwise COPY will fail. Thx any way.
