### ISSUE TITLE
TerserUtil.setElement does not actually respect multiple-cardinality elements

### ISSUE THREAD

**Issue by pepsiofficial** [fabric8io/docker-maven-plugin#1728]
### Description

TerserUtil uses Arrays.asList() to wrap values before calling `mergeFields` over in `setField`.  This prevents the list from growing, and so `setElement` ultimately does not add to multiple-cardinality elements as advertised.

**Comment by rohanKanojia** [comment]
Sorry, but which TerserUtil are you referring to?
