### ISSUE TITLE
"DOCKER> unknown flag: --driver" on debian 12.4 "bookworm" amd64

### ISSUE THREAD

**Issue by steinarb** [fabric8io/docker-maven-plugin#1739]
### Info

* docker-maven-plugin version : 0.43.4
* Maven version (`mvn -v`) :
```
Apache Maven 3.8.7
Maven home: /usr/share/maven
Java version: 17.0.9, vendor: Debian, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.1.0-16-amd64", arch: "amd64", family: "unix"
```
* Docker version : Docker version 20.10.24+dfsg1, build 297e128
* If it's a bug, how to reproduce :
```
git clone https://github.com/steinarb/sonar-collector.git
cd sonar-collector
git checkout use-karaf-444-in-docker
mvn install
cd docker
mvn install
```
The final mvn command fails with:
```
[INFO] DOCKER> GET unix://127.0.0.1:1/version
[INFO] Building tar: /home/sb/workspaces/ws02/sonar-collector/docker/target/docker-build/sonar-collector/1.5.21/tmp/docker-build.tar
[INFO] DOCKER> [sonar-collector:1.5.21]: Created docker-build.tar in 28 milliseconds
[INFO] DOCKER> Using Docker CLI 20.10.24+dfsg1
[INFO] DOCKER> docker buildx create --driver docker-container --name maven
[INFO] DOCKER> unknown flag: --driver
[INFO] DOCKER> See 'docker --help'.
[INFO] DOCKER> 
[INFO] DOCKER> Usage:  docker [OPTIONS] COMMAND
...
```

Manually running the command
```
docker buildx create --driver docker-container --name maven
```
gives the same error message as the maven build failure
* If it's a feature request, what is your use case :
* Sample project : *[[GitHub Clone URL](https://github.com/steinarb/sonar-collector.git)]*

**Comment by breun** [comment]
My guess is that Docker 20.10.24 is too old to support that `--driver` flag. You could check the help or man page for your `docker` command.

The current version of Docker is 24.x: https://docs.docker.com/engine/release-notes

**Comment by rohanKanojia** [comment]
@steinarb : Could you please check if you face similar issue on newer version of Docker CLI?

**Comment by breun** [comment]
Hm, I also get that error message with a current version:

```
~ ❯ docker --version
Docker version 24.0.6, build f5ab475
~ ❯ docker buildx create --driver docker-container --name maven
unknown flag: --driver
See 'docker --help'.
(...)
```

**Comment by rohanKanojia** [comment]
@breun : Do you have some simple reproducer project on which I can try it out?

**Comment by breun** [comment]
I don't, but @steinarb included a link to a sample project in the original post. I just tried running the `docker` command that was run to see if it was at least accepted syntax.

**Comment by steinarb** [comment]
> @breun : Do you have some simple reproducer project on which I can try it out?

There is one in the Description of this issue:
```
git clone https://github.com/steinarb/sonar-collector.git
cd sonar-collector
git checkout use-karaf-444-in-docker
mvn install
cd docker
mvn install
```

The config in sonar-collector/docker/pom.xml is probably not working, but it doesn't look like it gets far enough to fail because the docker-maven-plugin sends in a flag docker doesn't like (at least the docker native on current debian stable (12.4 "bookworkm") doesn't understand it. And I would really prefer things to work with that docker).

**Comment by rohanKanojia** [comment]
@steinarb : hello, I tried reproducing this issue by cloning your project and following the steps but I couldn't reproduce it. I am using Fedora 39 at the moment.

I even tried reproducing this issue via[ GitHub actions](https://github.com/rohankanojia-forks/sonar-collector/actions/runs/7429723214/job/20218616135) but still no luck.

**Comment by steinarb** [comment]
Yes, as someone said in a comment over: the docker of debian 12.4 is probably too old (docker 20 while current is 24).

Running the command line command manually gives the same error.

It's still docker 20.x in debian unstable and nothing newer in backports: https://packages.debian.org/sid/docker.io

So I guess this docker-maven-plugin will not work for me (if I can't use the docker provided by debian it will be too much work).

**Comment by steinarb** [comment]
Hm... there is an APT repo appropriate for use on debian 12 https://docs.docker.com/engine/install/debian/

**Comment by breun** [comment]
> Yes, as someone said in a comment over: the docker of debian 12.4 is probably too old (docker 20 while current is 24).

I said that, but I also confirmed that the flag doesn’t exist on the current latest version, so apparently that theory was incorrect.

**Comment by breun** [comment]
@rohanKanojia If you run the commands from https://github.com/fabric8io/docker-maven-plugin/issues/1739#issuecomment-1870165875, do you not get that error saying `unknown flag: --driver`?

**Comment by steinarb** [comment]
>>>>> Nils Breunese ***@***.***>:

>> Yes, as someone said in a comment over: the docker of debian 12.4 is probably too old (docker 20 while current is 24).
> I said that, but I also confirmed that the flag doesn’t exist on the current latest version, so apparently that theory was incorrect.

Yes, I saw that too.

But I got confused as to what was right and figured I was just stuck
with a too old docker.

**Comment by rohanKanojia** [comment]
@steinarb : Do you need to rely on buildkit features? If not, you can disable it via `DOCKER_BUILDKIT=0` environment variable.

@breun : When I run above commands I see this output:
```sh
~ : $ docker --version
Docker version 24.0.7, build afdd53b
~ : $ docker buildx cdocker buildx create --driver docker-container --name maven
maven
```

**Comment by steinarb** [comment]
>>>>> Rohan Kumar ***@***.***>:

> @steinarb : Do you need to rely on buildkit features? If not, you can disable it via `DOCKER_BUILDKIT=0` environment variable.

I don't know. My docker image build requirements are pretty humble, so probably not.

I tried disabling DOCKER_BUILDKIT but I get the same error as before: https://gist.github.com/steinarb/5e6ca961c51d044368b95cabf4fafe42

**Comment by rohanKanojia** [comment]
@steinarb : To make plugin not rely on docker CLI (which it does for `buildx`), you would need to remove `<platform >` from `<buildx>` configuration, or maybe just remove whole `<buildx>` configuration section.

**Comment by steinarb** [comment]
Ok, removing <buildx> worked a lot better: https://gist.github.com/steinarb/3bb38f8df9082db7246a3192585600d6

There is still the issue of docker pulling a wrong architecture image (arm64 instead of amd64) which is the same problem I had with the old, discontinued, [docker-maven-plugin from spotify](https://github.com/spotify/docker-maven-plugin).

But that is probably an issue with the official karaf image. I will investigate with the karaf project.

Here is the branch with the pushed changes: https://github.com/steinarb/sonar-collector/tree/use-karaf-444-in-docker

Thanks! Closing this as fixed/no error.
