### ISSUE TITLE
RegistryServiceTest : remove unused variable `hasImage` and `dockerFileUtilMockedStatic`

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/docker-maven-plugin#1766]
### Description

RegistryServiceTest seems to be initializing these fields but they are not accessed:
https://github.com/fabric8io/docker-maven-plugin/blob/110a8f88eb70a258cdd60be6ff856e181572dac4/src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java#L60

The above field is set in `givenHasImage` method but it's value is not accessed anywhere.

https://github.com/fabric8io/docker-maven-plugin/blob/110a8f88eb70a258cdd60be6ff856e181572dac4/src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java#L62

Probably a leftover from previous refactors, we should remove this field

### Acceptance Criteria
- [ ] `hasImage` and `dockerFileUtilMockedStatic` fields are removed from test
- [ ] `givenHasImage` method is removed
- [ ] RegistryServiceTest passes even after making these changes

**Comment by rohanKanojia** [comment]
@mdxabu : Could you please check if this is clear enough for you? If yes, shall I assign it to you?

**Comment by mdxabu** [comment]
> @mdxabu : Could you please check if this is clear enough for you? If yes, shall I assign it to you?

Yes, I can work in this issue, @rohanKanojia

**Comment by mdxabu** [comment]
https://github.com/fabric8io/docker-maven-plugin/blob/110a8f88eb70a258cdd60be6ff856e181572dac4/src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java#L226

https://github.com/fabric8io/docker-maven-plugin/blob/110a8f88eb70a258cdd60be6ff856e181572dac4/src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java#L110

https://github.com/fabric8io/docker-maven-plugin/blob/110a8f88eb70a258cdd60be6ff856e181572dac4/src/test/java/io/fabric8/maven/docker/service/RegistryServiceTest.java#L139

Many functions call the `givenHasImage()`, It's okay to remove those lines or not.

**Comment by rohanKanojia** [comment]
No longer applicable, the test has been updated.
