### ISSUE TITLE
Version 0.44.0 fails to use the `<args>` configuration to populate the Docker build-args

### ISSUE THREAD

**Issue by aggregat4** [fabric8io/docker-maven-plugin#1776]
### Description

When we upgraded from version 0.43.3 to 0.44.0 of the `docker-maven-plugin` our build failed because the build args were no longer being passed on to the docker command. We use the `<args>` element in the `<build>` section of the maven plugin configuration.

I have taken the `dockerfile-base-as-arg-buildconfig` integration test from your current master and modified it to use the 0.44.0 plugin to demonstrate this effect:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.fabric8.dmp.itests</groupId>
  <artifactId>dmp-it-dockerfile-base-as-arg-buildconfig</artifactId>
  <version>0.45-SNAPSHOT</version>
  <name>dmp-it-dockerfile-base-as-arg-buildconfig</name>

  <build>
    <plugins>
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.44.0</version>
        <configuration>
          <images>
            <image>
              <name>fabric8:dmp-it-dockerfile-base-as-arg-buildconfig</name>
              <build>
                <dockerFile>Dockerfile</dockerFile>
                <args>
                  <FROM_IMAGE>openjdk:21-slim</FROM_IMAGE>
                </args>
              </build>
            </image>
          </images>
        </configuration>
        <executions>
          <execution>
            <id>build</id>
            <goals>
              <goal>build</goal>
            </goals>
            <phase>install</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

With the following `Dockerfile` in `src/main/docker` (this is verbatim from the integration test):

```
ARG FROM_IMAGE
FROM ${FROM_IMAGE} AS jlink
```

Building with `mvn clean install` fails with `Caused by: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonArray` as a root cause, which is just a symptom of the `FROM_IMAGE` argument not being resolved. If you run the build with `mvn -X clean install` you can observe the build args to be empty.

Building the project with the `0.43.3` version of the plugin works. 

### Info

* docker-maven-plugin version : 0.44.0
* Maven version (`mvn -v`) : 3.8.7
* Docker version : 26.0.0

**Comment by rohanKanojia** [comment]
@aggregat4 : Do you think this is duplicate of https://github.com/fabric8io/docker-maven-plugin/issues/1756 ?

**Comment by aggregat4** [comment]
@rohanKanojia  doh! I tried looking for existing issues, but apparently I failed. That is the same thing. I'll close this issue.

**Comment by rohanKanojia** [comment]
@aggregat4 : Could you please check via [SNAPSHOT](https://github.com/fabric8io/docker-maven-plugin/blob/master/doc/HowToUseDockerMavenPluginSnapshotArtifacts.md) build if it's working as expected?

Would you need a patch release for this fix?

**Comment by aggregat4** [comment]
@rohanKanojia I tried with the current 0.45-SNAPSHOT and my testcase works, so that seems fixed.

We don't need a patch release, we can wait for the 0.45 release. Do you know when this would be?
