### ISSUE TITLE
DockerComposeServiceWrapper : Use `isEmpty()` to check collection is empty

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/docker-maven-plugin#1779]
### Description

Instead of checking size greater than zero, use inbuilt `isEmpty` method
https://github.com/fabric8io/docker-maven-plugin/blob/fc53963fc57c466dc10757ac98d2009927f6ef15/src/main/java/io/fabric8/maven/docker/config/handler/compose/DockerComposeServiceWrapper.java#L407-L412

### Acceptance Criteria
- [ ] `size() > 0` check is replaced by `isEmpty()`
- [ ] Rename `configuration` field so that it doesn't collide with class level field

**Comment by rohanKanojia** [comment]
@mdxabu : Could you please check if this is okay for you to pick?

**Comment by alpha951** [comment]
Hey @rohanKanojia can you please assign this issue to me?

**Comment by alpha951** [comment]
Hey @rohanKanojia, I've raised a PR #1782 addressing this issue. Let me know if any further change is required.
