### ISSUE TITLE
WatchService : Anonymous `new Runnable()` can be replaced with lambda 

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/docker-maven-plugin#1780]
### Description

This anonymous class can be replaced with a lambda: 

https://github.com/fabric8io/docker-maven-plugin/blob/fc53963fc57c466dc10757ac98d2009927f6ef15/src/main/java/io/fabric8/maven/docker/service/WatchService.java#L128-L131

### Acceptance Criteria
- [ ] Replace anonymous class with lambda
- [ ] Use `isEmpty()` in place of `size() > 0` check

**Comment by rohanKanojia** [comment]
@mdxabu Could you please review this one? Is it clear enough for you to pick?

**Comment by mdxabu** [comment]
> @mdxabu Could you please review this one? Is it clear enough for you to pick?
yes, I can pick this

**Comment by alpha951** [comment]
If a PR has not been raised yet for this issue, could you please assign it to me? I've submitted a PR for the previous assignment #1782

**Comment by mdxabu** [comment]
> If a PR has not been raised yet for this issue, could you please assign it to me? I've submitted a PR for the previous assignment #1782

Sorry, This issue was assigned for me, I am working on it.

**Comment by mdxabu** [comment]
@rohanKanojia, Close this issue.
