### ISSUE TITLE
VolumeBindingUtil : Replace loop with `List.replaceAll` method

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/docker-maven-plugin#1813]
### Description

We're using this loop in this class where we're applying the same operation on each list object.

https://github.com/fabric8io/docker-maven-plugin/blob/99c52cbd76d538b64eb5b8b07fdb619f1f634c34/src/main/java/io/fabric8/maven/docker/util/VolumeBindingUtil.java#L236-L238

JDK has already provided a method to achieve this task. We should use that instead

**Comment by tusharwebd** [comment]
Hi! Can you assign this task to me? I am fairly new to open source contributions and this looks like a good place to start.
