### ISSUE TITLE
BuildX failing for Docker CLI on Windows

### ISSUE THREAD

**Issue by derHeinz** [fabric8io/docker-maven-plugin#1818]
### Description
BuildX failing for Docker CLI on Windows

Similar to #1754  but for Windows.

The workaround does not work on Windows 10 for me.

### Info

* docker-maven-plugin version :
* Maven version (`mvn -v`) :
```
3.9.6
```
* Docker version : 27.1.1
* If it's a bug, how to reproduce : see https://github.com/fabric8io/docker-maven-plugin/pull/1754
* If it's a feature request, what is your use case : -
* Sample project : *[GitHub Clone URL]*

**Comment by ggjulio** [comment]
Hey, thank you both for the fix,
what is  the next planned release date ?

**Comment by rohanKanojia** [comment]
@ggjulio : Hello, let me cut a patch release with the fix.

**Comment by rohanKanojia** [comment]
@ggjulio @derHeinz : Hello, I've released [v0.45.1](https://repo1.maven.org/maven2/io/fabric8/docker-maven-plugin/0.45.1/) . Could you please give it a try and check whether everything is working as expected?

**Comment by ggjulio** [comment]
For me everything seem to work as expected, thank you.
