### ISSUE TITLE
behavior of 'docker.follow' when set as maven property

### ISSUE THREAD

**Issue by jgangemi** [fabric8io/docker-maven-plugin#249]
what should be the behavior of `docker.follow` if i have it defined in the `properties` section of my pom and i call `docker:start`?

my use case is i'm tired of forgetting to specify `-Ddocker.follow` when i run `docker:logs` so i wanted to set it as a maven property in the `properties` section and just forget about it. the problem is if i run `docker:start`, it starts the container and starts displaying the logs.

the manual says this behavior should occur if the value was specified via a system property, so i wanted to find out if this is a bug or the docs are wrong.

if you don't feel this is a bug, thoughts on how i could fulfill my use case?

**Comment by rhuss** [comment]
You are right these should probably two different properties. I'm on the
road till Monday, will check this then.

Jae Gangemi <notifications@github.com> schrieb am Mi., 5. Aug. 2015 17:01:

**Comment by jgangemi** [comment]
so that explains why my PRs haven't gotten any love. :)

i already investigated, the start mojo defines the `follow` parameter and if it's true, the behavior described occurs.

i don't think we need to use two different properties for this. instead i think the start mojo could just be updated to look for the `follow` property in the system properties and if it finds it there, don't background the container.

**Comment by neilgreatorex** [comment]
+1 for this.

At the moment I'm using the maven-antrun-plugin to change the property between executions (overkill I know):
```
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.7</version>
                <executions>
                    <execution>
                        <id>Set docker follow property</id>
                        <phase>post-integration-test</phase>
                        <configuration>
                            <exportAntProperties>true</exportAntProperties>
                            <target>
                                <property name="docker.follow" value="true"/>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

This workaround has the unintended side effect that you then get each log line twice - presumably because the `docker:start` execution doesn't clean up whatever hooks it has on the logs when it finishes.

**Comment by jgangemi** [comment]
closing, this got added :)
