### ISSUE TITLE
Add possibility to start stopped container with alias

### ISSUE THREAD

**Issue by phihos** [fabric8io/docker-maven-plugin#270]
Hi,

for development purposes I would like to keep the same container. For this I used the alias tag and defined `<namingStrategy>alias</namingStrategy>` for all my images.
When I restart the docker host, all containers are stopped. When I run `docker:start`I would like to start the existing aliased containers, instead of creating new ones. But I get

```
[ERROR] DOCKER> Conflict. The name "<container alias>" is already in use by container <container-id>. You have to delete (or rename) that container to be able to reuse that name.
```

How can I achieve, that docker-maven-plugin checks for a stopped container with the specified alias and tries to start it?

**Comment by jgangemi** [comment]
that functionality does not currently exist. 

if you wanted the containers to automatically restart when the host restarts, you could configure a restart policy.
```
<restartPolicy>
  <name>always</name>
</restartPolicy>
```
