### ISSUE TITLE
Add "log" to PropertyConfigHandler

### ISSUE THREAD

**Issue by rhuss** [fabric8io/docker-maven-plugin#295]
Currently the log section for the runtime property config is missing in `PropertyConfigHandler.extractRunConfiguration()`.

This should be added.

**Comment by mdxabu** [comment]
Can I work on this section?

**Comment by mdxabu** [comment]
can you just give some ideas?

**Comment by rohanKanojia** [comment]
@mdxabu : Looking at code it already seems to be fixed. 
https://github.com/fabric8io/docker-maven-plugin/blob/267e4674e63b8800531bb1ce4a4e2b0b31e8007d/src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java#L231

let me create some other good first issue for you.

**Comment by mdxabu** [comment]
Give me another
