### ISSUE TITLE
Add timing to the build goal

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/docker-maven-plugin#313]
When building a docker image, then a lot of time can be spent in 

- pulling images 
- building the .tar

I would like if the d-m-p could report how long time that task took in seconds.

```
[INFO] - Pulling images took 49 seconds
[INFO] - Building tar took 37 seconds
```

And I guess there is also timing for a docker:push could be good to have as well.

**Comment by andyshinn** [comment]
This would be very helpful. Good idea!

**Comment by jgangemi** [comment]
this shouldn't be too difficult, i'll see about getting this done along side some other things i'm doing.
