### ISSUE TITLE
docker networks instead of links

### ISSUE THREAD

**Issue by ppaland** [fabric8io/docker-maven-plugin#321]
docker 1.9 introduces the new docker networking and at the same time discourages docker links:

https://blog.docker.com/2015/11/docker-multi-host-networking-ga/
https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

Do you have plans to support the feature? It would be interesting because it easily allows two-way-communication.

**Comment by jgangemi** [comment]
yes, i'm sure at some point it will be added. pull requests are always welcome.

**Comment by rhuss** [comment]
Indeed we want to add new features introduced with Docker 1.9, although not quite clear how to do this for *docker network* yet. 

The 0.14.x series is dedicated for adding new Docker 1.9 features. We will also have to think about how to handle backwards compatibility.

**Comment by rhuss** [comment]
Network links are now supported for 0.14.0 with the new `<net>` configuration option. The network specified must exist already, though.

Might be a good idea to create a network on the fly if requested and not existant ?

**Comment by ppaland** [comment]
Would be perfect if PropertyConfigHandler was also extended for this feature.

**Comment by rhuss** [comment]
good point, added this, too.
