### ISSUE TITLE
Any plan to support the new ARG command 

### ISSUE THREAD

**Issue by djsly** [fabric8io/docker-maven-plugin#334]
It would be great if we could provide the maven variables as Docker file build variables.
http://docs.docker.com/engine/reference/builder/#arg

**Comment by jgangemi** [comment]
if you define the container configuration via the plugin xml, this can already be accomplished. you can also already use maven properties inside a `Dockerfile` that you have specified as part of the build, but this is very non-portable.

past that, i believe supporting this would require us to parse the Dockerfile to look for these values and re-create a new Dockerfile with everything substituted. 

actually...now that i think about this, you could probably accomplish this now provided you were always overriding the value on the command line.

```
ARG foo=${some.maven.property}
```

in the above case, the plugin would automatically substitute in the property value and docker would just think a default value was specified and use that. this doesn't work, though, if you wanted to have an actual default value there and only substitute it sometimes.

**Comment by djsly** [comment]
Our current use case would be around a dockerfile that we manage externally. (not using the auto generated dockerfile feature)

docker build 1.9 provides you with a new docker build flag pass ARG. 

so I would see that a new xml attribute could be create 
````
<docker-build-args>
     <docker-build-arg>my_arg=${maven.releaseVersion}</docker-build-arg>
<docker-build-args>
````

which would translate to the equivalent docker remote API call for 

````
--build-arg my_arg=${maven.releaseVersion}
````

**Comment by jgangemi** [comment]
hrm - i didn't see that in the api documentation when i looked the first time.

yeah - something like that should definitely be possible then.

**Comment by rhuss** [comment]
We will consider to support this when we increase the support for external Dockerfiles. Currently these external Dockerfile don't have Maven property substitution (but this is planned for #205)

Luckily we postponed this a bit, because we probably would have chosen the same expression syntax as Docker 1.9 for `ARG` interpolation (namely `${...}`) ;-). So we need sth different for Maven properties if we want to support this as an extension, too. Alternatively we could omit Maven property substitution completely and only use Dockerfile expressions (and feeding in the `build-args` when building the image).

Docker 1.9 support is planned for 0.14 so it might take a bit, though.

**Comment by jgangemi** [comment]
my thought here is while we should be accommodating, we shouldn't bend over backwards to support this and the onus should be on the user to do the right thing.

resource filtering in maven is only enabled if you explicitly turn it on, so if someone wants to use the `build-args` support, they can't run their `Dockerfile` through maven's resource filtering or they need to use unique property names that won't be known to maven.

they can still turn have a `Dockerfile` template, we would just recommend they take one approach or the other.

**Comment by balazsmaria** [comment]
I'd very much like something which translates to 
`docker build --build-arg http_proxy=$http_proxy -t myTag .`
as I don't want to put anything like this into my Dockerfile.

Is this issue about that?

**Comment by rhuss** [comment]
FYU, my thoughts on the ARG support can be found in #409
