### ISSUE TITLE
net=host

### ISSUE THREAD

**Issue by Khazrak** [fabric8io/docker-maven-plugin#335]
There doesn't seem like net=host is supported?

**Comment by jgangemi** [comment]
no - not yet.

**Comment by rhuss** [comment]
Indeed, no support yet (so its currently always `default` aka `bridged`). However we plan to support `docker network` soon and hence will add support for custom networks, too.

**Comment by swachter** [comment]
+1
I also would like to be able to configure a logspout container such that it reuses the network of a logstash container.

**Comment by indyaah** [comment]
+1

**Comment by bsorrentino** [comment]
+1

**Comment by rhuss** [comment]
See also #321

**Comment by rhuss** [comment]
I implemented this for 0.14.0 and pushed a 0.14.0-SNAPSHOT. See https://github.com/rhuss/docker-maven-plugin/blob/integration/doc/manual/docker-start.md for details how to configure the new `<net>` configuration option.

Feel free to give feedback and whether it fits your needs.

**Comment by vrenjith** [comment]
Hi @rhuss - Any hints on when 0.14.0 will be available? Eagerly waiting for it.

**Comment by rhuss** [comment]
Sorry for the delay, I'm just about moving the plugin to a new GitHub orga (fabric8) so that we can join efforts there. 

0.14.0 will be out this week, maybe even today.

**Comment by vrenjith** [comment]
That's is best news that I can hear today. Thank you and appreciate all your efforts for keeping this plugin up-to-date.
