### ISSUE TITLE
docker:build to use a temporary directory inside the ${project.build.directory} directory

### ISSUE THREAD

**Issue by benjefferies** [fabric8io/docker-maven-plugin#356]
We are compiling our source to a different output directory than the default ${basedir}/target. We have done this by overriding the <directory> which is defaults as ${basedir}/target. As docker-maven-plugin builds to the directory ${basedir}/target this leaves the temporary directory in the project directory instead of the new location maven is compiling to.

Example when <directory> set to /tmp/target
`/project/src/main/java/Foo.class`
compiles to
`/tmp/target`
but docker-maven-plugin temp files go to
`/project/target/docker/project/`
instead of
`/tmp/target/docker/project`

**Comment by jgangemi** [comment]
are you using the `sourceDirectory` and `ouputDirectory` configuration settings for the plugin?

**Comment by benjefferies** [comment]
Hi @jgangemi, we are not but from scanning the source code I am not sure if that would help us. If I understand what is going on correctly the `sourceDirectory` and `outputDirectory` is a child directory of ${baseDir}

I am relating to this part of the code where it uses MavenProject to relatively create the output directories under BaseDir instead of the build directory configured.

See https://github.com/rhuss/docker-maven-plugin/blob/e048821fca0325743388b9b5e3aa44400bf63ac6/src/main/java/org/jolokia/docker/maven/util/EnvUtil.java#L203

Let me know if I am not making much sense

**Comment by jgangemi** [comment]
but they don't have to be, you can make them absolute paths, so setting `outputDirectory` to `/tmp/target/docker/project` should achieve what you want.

**Comment by benjefferies** [comment]
@jgangemi thanks I over looked this even though it was starting me right in the face. I guess this issue can be closed for now however it may be worth considering using the build directory given by maven (http://maven.apache.org/ref/3.3.9/maven-model/apidocs/org/apache/maven/model/BuildBase.html#getDirectory()) as this is what we are trying to achieve by putting it into `${baseDir}/target`

**Comment by jgangemi** [comment]
hrm - i guess i'm still confused by what you're trying to accomplish. by default, the plugin should put everything under `target` and from there i believe it goes into a `docker` directory and there are some further sub-dirs under that.

if you override either of the two directories via the global configuration, the paths that are constructed are relative to `$basedir` unless it's an absolute path, in which case we use whatever you give us.

those two overrides are supposed to act just like the overrides you can give for when you compile code w/ the exception that if you change the values for compilation, etc it doesn't cascade down to the plugin.

**Comment by benjefferies** [comment]
You're right in that it does put `build`, `tmp`, `work` under `/mavenProject/target/docker/imageName/imageName`. However we have configured maven to compile elsewhere for build performance reasons, I will elaborate so you can understand the scenario. 

Normally maven will compile `classes`, `test-classes` to `/mavenProject/target` defined implicitly by the maven `<directory>` property as `target` in the super pom.xml (https://maven.apache.org/guides/introduction/introduction-to-the-pom.html). 

We have to overridden where the maven `<directory>` property so it no longer builds `classes`, `test-classes` to `/mavenProject/target` but to `/tmp/mavenProject/target`. However, because docker-maven-plugin explicitly outputs to ${baseDir} specified here https://github.com/rhuss/docker-maven-plugin/blob/e048821fca0325743388b9b5e3aa44400bf63ac6/src/main/java/org/jolokia/docker/maven/util/EnvUtil.java#L203 the maven-docker-plugin continues to output to `/mavenProject/target/docker/imageName/imageName` instead of `/tmp/mavenProject/target/docker/imageName/imageName`

With the background clarified I have spent some time today trying out your suggestion of specifying the absolute path in the `outputDirectory` configuration but this doesn't seem to work as I hoped. It appears to check if something is an absolute path, if it is, it will use that location instead of the default `baseDir`. From what I can see though it is checking if `build`, `tmp`, `work` is an absolute path instead of the `outputDirectory` in the references here https://github.com/rhuss/docker-maven-plugin/blob/e048821fca0325743388b9b5e3aa44400bf63ac6/src/main/java/org/jolokia/docker/maven/assembly/BuildDirs.java

**Comment by jgangemi** [comment]
ahh - you're overriding `directory`, that helps clarify things a bunch. 

i'm about to leave for vacation so i'm not sure if i'll be able to look at this before the new year if @rhuss doesn't get to it first, but we'll for sure get this taken care of!

**Comment by benjefferies** [comment]
Thanks @jgangemi I can't commit to it but if I find some time can try to resolve and raise a pull request or at the least make a start on it.

Not sure if you followed the last part but does this sound like the correct behaviour or is this a bug? 
> With the background clarified I have spent some time today trying out your suggestion of specifying the absolute path in the outputDirectory configuration but this doesn't seem to work as I hoped. It appears to check if something is an absolute path, if it is, it will use that location instead of the default baseDir. From what I can see though it is checking if build, tmp, work is an absolute path instead of the outputDirectory in the references here https://github.com/rhuss/docker-maven-plugin/blob/e048821fca0325743388b9b5e3aa44400bf63ac6/src/main/java/org/jolokia/docker/maven/>assembly/BuildDirs.java

**Comment by jgangemi** [comment]
honestly, i'm not sure, it's been a while since i've really looked at that code. it should be taking the value of `outputDirectory` and using it to construct the paths for `build`, `tmp`, etc although it's possible we do that again the constructed path after the fact. 

either way, specifying an absolute path for the `outputDirectory` should get you what you want, if it isn't, my gut says it's a bug.
