### ISSUE TITLE
Build all, but only some images

### ISSUE THREAD

**Issue by sorenroug** [fabric8io/docker-maven-plugin#364]
I have a use case where the production system uses postgresql. For integration testing, I have a small <build> section that starts from postgresql:9.3 and then puts dummy data into the database. I want to push the application image to our local registry, but not the database image. Unfortunately the global <image>  configuration parameter works on both the build and the push goals.

I know I can do mvn -Ddocker.image=app docker:push

but it would be more convenient if there was a <push.images> configuration parameter.

**Comment by rhuss** [comment]
You can add `<image>` to the top-level configuration for specifying the image to build from the `<images>` section. This is best put into a dedicated profile (along with `combine.self="override"` as attribute to the `<configuration>` tag, see this [Blog](http://blog.sonatype.com/2011/01/maven-how-to-merging-plugin-configuration-in-complex-projects/#.VqSry5MrLKI) for details how to merge plugin configurations).

**Comment by rage-shadowman** [comment]
Why not allow:

    <push><skip>true</skip></push>

...in the image configuration?

**Comment by rage-shadowman** [comment]
I think I just figured out how to do it:

    <executions>
            <execution>
                    <id>docker:remove</id>
                    <phase>clean</phase>
                    <goals>
                            <goal>remove</goal>
                    </goals>
                    <configuration>
                            <filter>
                                    ${project.artifactId}:${project.version},
                                    alias-of-project-test-dependency1,
                                    alias-of-project-test-dependency2,
                                    alias-of-project-test-dependency3,
                                    ${project.artifactId}-test,
                            </filter>
                    </configuration>
            </execution>
            <execution>
                    <id>docker:build</id>
                    <phase>package</phase>
                    <goals>
                            <goal>build-nofork</goal>
                    </goals>
                    <configuration>
                            <filter>
                                    ${project.artifactId}:${project.version},
                                    alias-of-project-test-dependency1,
                                    alias-of-project-test-dependency2,
                                    alias-of-project-test-dependency3,
                                    ${project.artifactId}-test,
                            </filter>
                    </configuration>
            </execution>
            <execution>
                    <id>docker:start</id>
                    <phase>pre-integration-test</phase>
                    <goals>
                            <goal>start</goal>
                    </goals>
                    <configuration>
                            <filter>
                                    alias-of-project-test-dependency1,
                                    alias-of-project-test-dependency2,
                                    alias-of-project-test-dependency3,
                                    ${project.artifactId}-test,
                            </filter>
                    </configuration>
            </execution>
            <execution>
                    <id>docker:stop</id>
                    <phase>post-integration-test</phase>
                    <goals>
                            <goal>stop</goal>
                    </goals>
                    <configuration>
                            <filter>
                                    alias-of-project-test-dependency1,
                                    alias-of-project-test-dependency2,
                                    alias-of-project-test-dependency3,
                                    ${project.artifactId}-test,
                            </filter>
                    </configuration>
            </execution>
            <execution>
                    <id>docker:push</id>
                    <phase>deploy</phase>
                    <goals>
                            <goal>push</goal>
                    </goals>
                    <configuration>
                            <filter>${project.artifactId}:${project.version}</filter>
                    </configuration>
            </execution>
    </executions>

I have a push-able image ${project.artifactId}:${project.version} which cannot be run since it needs to link to all of the dependent images, so I also created a ${project.artifactId}-test image which is just derived directly from the main image but with a run configuration with the necessary links, log params and debug runtime environment variables.

So we remove and build all images, start and stop only the integration test related images, and push only the main artifact image.
