### ISSUE TITLE
Enhancement: add log-driver capability to docker:run

### ISSUE THREAD

**Issue by rikcarve** [fabric8io/docker-maven-plugin#379]
I could not find any support for using a different log-driver within docker:run.
For some containers we use the gelf log driver in docker:
`sudo docker run -d --log-driver=gelf --log-opt gelf-address=udp://localhost:12201 myimage`

Any plans to add this?

**Comment by jgangemi** [comment]
at some point, yes. pull requests welcome...

**Comment by rikcarve** [comment]
Ok, I've got it working now locally. After some cleanup I will make a pull request.

**Comment by rhuss** [comment]
Cool. Looking forward to the PR ;-)

**Comment by rikcarve** [comment]
Finally made a pull request: #387

**Comment by rhuss** [comment]
Thanks ;-) 'will have a look at it ASAP

**Comment by rhuss** [comment]
Merged, should be available in 0.14.0 (to be released in this week)

**Comment by rikcarve** [comment]
Thanks, tested the latest release from maven central and it works as expected.
