### ISSUE TITLE
Invalid wait in samples

### ISSUE THREAD

**Issue by dantran** [fabric8io/docker-maven-plugin#385]
the sample has this wait's settings

    <wait>
      
      <url>http://localhost:${jolokia.port}/jolokia</url>
       
       <time>2000</time>
     </wait>

it should be

    <wait>
      
      <http>
         <url>http://localhost:${jolokia.port}/jolokia</url>
       </http>
       
       <time>2000</time>
     </wait>

**Comment by rhuss** [comment]
Thanks for spotting this. Will be fixed in the next release.
