### ISSUE TITLE
Different configuration for run and build via PropertyConfigHandler

### ISSUE THREAD

**Issue by ppaland** [fabric8io/docker-maven-plugin#386]
The handler currently uses some properties for both build and run configuration, for example docker.env.VARIABLE. I need to set an env value for runtime (integration test) that I don't want to be in the docker container. As far as I see, this is currently not possible.

Proposal: Introduce two other sets of properties (docker.run.x and docker.build.x) to be able to configure them differently.

**Comment by rhuss** [comment]
You are right that's unfortunate. Its a good idea to introduce a more specific level which, when used, takes precedence over the the less specific property (without `build.` or `run.` level). That way we could also keep backwards compatibility.

I don't when having time to implement this but would happily integrate a pull request for this.

**Comment by rhuss** [comment]
Fixed with #948
