### ISSUE TITLE
Support new Volumes API volumes

### ISSUE THREAD

**Issue by Khazrak** [fabric8io/docker-maven-plugin#395]
If you create a volume as:
https://docs.docker.com/engine/reference/commandline/volume_create/

then a manual docker run would be:
```
docker run -it -v myvolume:/my/mount/point ubuntu:14.04
```

I tested the configuration:
```
<volumes>
     <volume>myvolume:/my/mount/point</volume>
</volumes>
```
But only got:
```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.14.0:start (default-cli) on project volume-test: Unable to parse configuration of mojo io.fabric8:docker-maven-plugin:0.14.0:start for parameter volume: Cannot find 'volume' in class io.fabric8.maven.docker.config.VolumeConfiguration -> [Help 1]
```

So I guess that support for the new volumes "entity" from Volumes API isn't supported yet?

**Comment by rhuss** [comment]
There is no explicit support for dedicated Docker volumes, but it seems that the API [supports](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-container) them transparently:

However, you have a configuration error in your example. It should read:

```xml
<volumes>
     <bind>
         <volume>myvolume:/my/mount/point</volume>
     </bind>
</volumes>
```

See also the [manual](http://fabric8io.github.io/docker-maven-plugin/docker-start.html#volume-binding).

Does this work for you ?

**Comment by Khazrak** [comment]
Nice, it seems to work
