### ISSUE TITLE
Releases not published in central maven repo

### ISSUE THREAD

**Issue by arulrajnet** [fabric8io/docker-maven-plugin#415]
The last version in maven central repo is 0.13.9 http://central.maven.org/maven2/org/jolokia/docker-maven-plugin/ . After that there are 3 versions are released. None of them published in maven central repo.

**Comment by arulrajnet** [comment]
Got it. Its released with different groupid http://central.maven.org/maven2/io/fabric8/docker-maven-plugin/ 

Add this as dependency
 
```
<dependency>
	<groupId>io.fabric8</groupId>
	<artifactId>docker-maven-plugin</artifactId>
	<version>0.14.2</version>
</dependency>
```
It should be documented in readme.

**Comment by rhuss** [comment]
@arulrajnet the change has been announced very prominently, its stated in the very first paragraph of the [README](https://github.com/fabric8io/docker-maven-plugin/blame/master/README.md#L6-L10), highlighted as a quote.

Sorry if you had troubles ....
