### ISSUE TITLE
Question, is there a way on push goal to so that jolokia plugin will print the actual push command its using?

### ISSUE THREAD

**Issue by tomer-ben-david** [fabric8io/docker-maven-plugin#418]
I want it for troubleshooting.

**Comment by jgangemi** [comment]
you can run maven w/ the `-X` flag and get debug logging - you can clearly see the REST calls it's making.

**Comment by tomer-ben-david** [comment]
thanks

**Comment by rhuss** [comment]
@tomer-ben-david I'll close that issue, feel free to reopen it in case
