### ISSUE TITLE
'Environment variable must not be null or empty if building an image'

### ISSUE THREAD

**Issue by rodlogic** [fabric8io/docker-maven-plugin#434]
This seems to be a bit harsh :-) What if I want to send an empty environment var either to unset a default or to just document that that env can be changed in the pom.

Here is the error I got trying to declare an empty <env> var:
```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.14.2:build (build) on project docker-app: Execution build of goal io.fabric8:docker-maven-plugin:0.14.2:build failed: Environment variable 'DATASOURCE_PASSWORD' must not be null or empty if building an image -> [Help 1]
```

**Comment by rhuss** [comment]
see the point. Just checked that Docker supports empty value, which seems to be the case (I darkly remembered that Docker croaked on empty env values in the Dockerfile sometimes ago). 

However you want be able to unset the variable that way. I will always be set, even when the value is empty.

will fix that for the next version, thanks ...

**Comment by rodlogic** [comment]
Grazie

**Comment by fabienmifsud** [comment]
I still have the issue with v.0.33.0 with this build conf : 
`<build>
                                        <from>library/openjdk:8-jre-alpine</from>
                                        <env>
                                            <JAVA_OPTS> </JAVA_OPTS>
                                        </env>
                                        <entryPoint>
                                            <exec>
                                                <args>java</args>
                                                <args>$JAVA_OPTS</args>
                                                <args>-jar</args>
                                                <args>/maven/${project.artifactId}-${project.version}.jar</args>
                                            </exec>
                                        </entryPoint>
                                        <assembly>
                                            <descriptorRef>artifact</descriptorRef>
                                        </assembly>
                                        <ports>
                                            <port>8080</port>
                                        </ports>
                                    </build>
                                </image>`

Thank you for advices !
