### ISSUE TITLE
Issue running docker-maven integration test via bamboo on Amazon Linux AMI 

### ISSUE THREAD

**Issue by dougj0220** [fabric8io/docker-maven-plugin#439]
We are using the docker-maven-plugin(v0.13.9) with a maven integration-test to test that our microservices architecture is working as designed. We are building the docker images using the spotify docker-maven-plugin (v 0.3.258) within the services mvn build. The integration test runs fine on my local machine using a macbook pro and boot2docker (docker-machine v0.5.6, Docker v1.9.1).

When we try to run the integration test via a Bamboo build plan. It appears that the service containers can not get a response from our eureka service (get a connection refused exception) when trying to register with discovery. Also, from the bamboo instance I can curl the eureka servers actuator endpoints on localhost http://127.0.0.1:1111/env, but trying to hit  http://127.0.1:1111/eureka/app gives me a 404 with a GET.

Any guidance as to what may be wrong would be greatly appreciated. Also, please let me know if you need anymore details.
 
Bamboo instance details:
Amazon Linux AMI release 2014.03
Docker version 1.9.0, build 76d6bc9
bamboo mvn version: 3.2
DOCKER_HOST=tcp://127.0.0.1:4243  is exported as an environment variable. Would we possibly need the other docker env variables exported?

Bamboo job log:
[bamboo_integration_test_log.txt](https://github.com/fabric8io/docker-maven-plugin/files/252811/bamboo_integration_test_log.txt)

integration Test pom:
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>tii-microservices-it</artifactId>
    <name>Integration Tests</name>

    <parent>
        <groupId>com.tii</groupId>
        <artifactId>tii-microservices</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
	
    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-feign</artifactId>
        </dependency>
    </dependencies>

    <build>
        
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/*.yml</include>
                </includes>
            </testResource>		
        </testResources>
        
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>2.7</version>
                <configuration>
                    <delimiters>
                        <delimiter>${*}</delimiter> 
                        <delimiter>@</delimiter> 
                    </delimiters>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.codehaus.groovy.maven</groupId>
                <artifactId>gmaven-plugin</artifactId>
                
                <executions>
                    <execution>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                        <configuration>
                            <source>
                                project.properties["hostip"] = InetAddress.getLocalHost().getHostAddress()
                            </source>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <id>integration-tests</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <excludes>
                                <exclude>none</exclude>
                            </excludes>
                            <includes>
                                <include>**/*IntegrationTest.java</include>
                            </includes>
                            <systemPropertyVariables>
                                <eureka.client.serviceUrl.defaultZone>http://${docker.host.address}:1111/eureka/</eureka.client.serviceUrl.defaultZone>
                            </systemPropertyVariables>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.jolokia</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.13.9</version>
                <configuration>
                    <logDate>default</logDate>
                    <autoPull>on</autoPull>
                    <verbose>true</verbose>
                    <useColor>true</useColor>
                    
                    <images>
                        <image>
                            
                            <alias>registration-service</alias>
                            <name>docker/registration-service</name>
                            <run>
                                
                                <wait>
                                    <http>
                                        <url>http://${docker.host.address}:1111</url>
                                        <method>GET</method>
                                        <status>200</status>
                                    </http>
                                    <time>50000</time>
                                </wait>
                                <log>
                                    <prefix>Eureka</prefix>
                                    <color>white</color> 
                                </log>
                                <ports>
                                    <port>1111:1111</port> 
                                </ports>
                                <env>
                                    <eureka.instance.hostname>localhost</eureka.instance.hostname> 
                                    
                                </env>
                                
                            </run>
                        </image>
                        <image>
                            <alias>nlp-service</alias>
                            <name>docker/nlp-service</name>
                            <run>
                                <namingStrategy>alias</namingStrategy>
                                <privileged>true</privileged>
                               <extraHosts>
                                    <host>localhost:${hostip}</host>
                                    
                                </extraHosts>
                                <wait>
                                    <http>
                                        <url>http://${docker.host.address}:5555/env</url>
                                        <method>GET</method>
                                        <status>200</status>
                                    </http>
                                    <time>50000</time>
                                </wait>
                                <log>
                                    <prefix>NLP</prefix>
                                    <color>blue</color>
                                </log>
                                <ports>
                                    <port>5555:5555</port>
                                </ports>
                                <links>
                                    <link>registration-service</link> 
                                </links>
                                <env>								
                                    <eureka.client.serviceUrl.defaultZone>http://${docker.host.address}:1111/eureka/</eureka.client.serviceUrl.defaultZone>
                                </env>
                                <hostname>nlp-service</hostname>
                            </run>
                        </image>
                        <image>
                            <alias>kb-service</alias>
                            <name>docker/kb-service</name>
                            <run>
                                <namingStrategy>alias</namingStrategy>
                                <privileged>true</privileged>
                                <extraHosts>
                                    <host>localhost:${hostip}</host>
                                </extraHosts>
                                <wait>
                                    <http>
                                        <url>http://${docker.host.address}:4444/env</url>
                                        <method>GET</method>
                                        <status>200</status>
                                    </http>
                                    <time>50000</time>
                                </wait>
                                <log>
                                    <prefix>KB</prefix>
                                    <color>red</color>
                                </log>
                                <ports>
                                    <port>4444:4444</port>
                                </ports>
                                <links>
                                    <link>registration-service</link> 
                                    <link>nlp-service</link>
                                </links>
                                <env>
                                    
                                    <eureka.client.serviceUrl.defaultZone>http://${docker.host.address}:1111/eureka/</eureka.client.serviceUrl.defaultZone>
                                </env>
                                <hostname>kb-service</hostname>
                            </run>
                        </image>
                        
                        <image>
                            <alias>gatekeeper-service</alias>
                            <name>docker/gatekeeper-service</name>
                            <run>
                                <namingStrategy>alias</namingStrategy>
                                <privileged>true</privileged>
                                <extraHosts>
                                    <host>localhost:${hostip}</host>
                                </extraHosts>
                                <wait>
                                    <http>
                                        <url>http://${docker.host.address}:8765/env</url>
                                        <method>GET</method>
                                        <status>200</status>
                                    </http>
                                    <time>50000</time>
                                </wait>
                                <log>
                                    <prefix>gatekeeper</prefix>
                                    <color>blue</color>
                                </log>
                                <ports>
                                    <port>8765:8765</port>
                                </ports>
                                <links>
                                    
                                    <link>registration-service</link>
                                    <link>kb-service</link>
                                    <link>nlp-service</link>
                                </links>
                                <env>
                                    <eureka.client.serviceUrl.defaultZone>http://${docker.host.address}:1111/eureka/</eureka.client.serviceUrl.defaultZone>
                                    
                                    <eureka.instance.prefer-ip-address>true</eureka.instance.prefer-ip-address>
                                </env>
                                <hostname>gatekeeper-service</hostname>
                            </run>
                        </image>
                    </images>
                </configuration>
                <executions>
                    <execution>
                        <id>start</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>stop</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>remove</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>remove</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>local</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <docker.ip>192.168.99.100:8765</docker.ip> 
            </properties>
        </profile>
        <profile>
            <id>dev</id>
            <properties>
                <docker.ip>localhost:8765</docker.ip> 
            </properties>
        </profile>
    </profiles>
</project>`

**Comment by rhuss** [comment]
Hi,

I had a quick glance over the setup, which is quite complex and would take me quite a bit of time to (a) follow it and (b) to reproduce it. I would happily help you here, but unfortunately my resources are limited. If you could boil it down to a simpler, more isolated test case where you can see an issue with this plugin, things would be much easier. But for the moment, the issue is too complex for providing any help ad hoc. All I can say is, that using 127.0.0.1 for connecting to the container looks suspicious too me since the integration test is running on the machine which executes the tests (the Bamboo agent in this case), and this probably is not the host running your container.

'hope you understand that I can't provide a fully fleshed consulting advice here.

**Comment by dougj0220** [comment]
Hello Rolland,
Thanks for the quick response, I appreciate it. I fully understand that you can not devote the resources it may take to work through this issue. I definitely do not think this is an issue with the plugin. I agree that this is a complex use case. I was just trying to pose the question to see if you or anyone may have ran across someone using the plugin this way. I was wondering if anyone has used the plugin in a amazon linux bamboo build environment. I was under the assumption that ${docker.host.address} in a linux environment would be localhost, and it would work fine.

Again, I appreciate the quick response. Have a good weekend.

Thanks,
Doug

**Comment by rhuss** [comment]
Thanks for your understanding ;-) `${docker.host.address}` is indeed localhost when using the UNIX socker mode, however when the plugin talks to the Docker daemon via TCP its the host adress of the (remote) docker host. 

btw, there is also a mailing list / forum where you might find help, too: https://groups.google.com/forum/#!forum/fabric8
