### ISSUE TITLE
No way to create users prior to assembly being applied

### ISSUE THREAD

**Issue by stevenbower** [fabric8io/docker-maven-plugin#441]
If you want to set the user of a container (so at the end it leaves the container running as a given user) there is no way (without multiple images) to both create the user and switch to that user.

See PR https://github.com/fabric8io/docker-maven-plugin/pull/440 for a patch that adds general support for placing a USER tag at the end of your dockerfile (ie after RUN commands)

**Comment by rhuss** [comment]
Yes, you are right. You can switch users, but only right after the assembly has been added so for creating stuff as root (`adduser` in your example) that wont work. Your patch looks good so far, I will integrate it this week.

Thanks !

**Comment by rhuss** [comment]
Fixed in 0.15.2
