### ISSUE TITLE
util.ImageName.doValidate not allowing legitimate, per spec, multi-component names

### ISSUE THREAD

**Issue by dweomer** [fabric8io/docker-maven-plugin#459]
As per the grammar implemented/documented at http://bit.ly/docker_image_format, specifically:
```
name := [hostname '/'] component ['/' component]*
```

image names should allow multiple sub-components after the first. As implemented currently by [util/ImageName.java](https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/util/ImageName.java) only two total components are allowed.

**Comment by rhuss** [comment]
fixed in 0.15.3, just released.
