### ISSUE TITLE
Read-Only bind volumes are broken since 0.15.2

### ISSUE THREAD

**Issue by Ironlink** [fabric8io/docker-maven-plugin#462]
Pull request #443 breaks the `:ro` suffix for read-only volumes.

Per the [docker API documentation](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#create-a-container), the optional second colon of `HostConfig.Binds` separates the container path from the access mode of the mount. According to the [docker user guide](https://docs.docker.com/engine/userguide/containers/dockervolumes/), Windows users are advised to use Unix-like paths such as `/c/Users/path` in order to avoid the colon issue.

**Comment by rhuss** [comment]
Thanks for pointing this out. It should be fixed now. We still need to cope with pathes like `c:\Users\path` since thats the format as it is stored in Maven properties. However, we will do the conversion on the fly within `EnvUtils.fixupPath()`

**Comment by deboj** [comment]
when can i expect a release containing this fix?

**Comment by rhuss** [comment]
we will do a release tomorrow.

**Comment by rhuss** [comment]
0.15.4 is out :)
