### ISSUE TITLE
Use of "--shm-size" as "docker run" parameter

### ISSUE THREAD

**Issue by obigard** [fabric8io/docker-maven-plugin#463]
Hello,

Is there a way to add the "--shm-size" parameter in the "docker run" command produced by the plugin?
This parameter is a standard one, as described in [Docker reference documentation](https://docs.docker.com/engine/reference/run/)

Thanks,
Olivier

**Comment by rhuss** [comment]
No, not yet. But it should be easy to add. If you feel fancy, please create a PR. Its easy to implement, a starting point is e.g. https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/access/ContainerCreateConfig.java#L102 where  the `Memory` options inserted. For shm its [ShmSize](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#create-a-container)

If not, no problem. I put this on the roadmap (but might take a bit)

**Comment by obigard** [comment]
I'll try to do it!

**Comment by rhuss** [comment]
cool, thx :)

**Comment by obigard** [comment]
done!

**Comment by obigard** [comment]
#464

**Comment by rhuss** [comment]
Thanks. 0.15.4 is released, containing your fixes.
