### ISSUE TITLE
Support to copy resources to another path

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/docker-maven-plugin#465]
Currently, all the resources generated under local directory target/maven are copied to /path within the Docker image according to the `basedir` property

```
                <version>${docker.maven.plugin.version}</version>
                <configuration>
                    <images>
                        <image>
                            <name>${docker.image}</name>
                            <build>
                                <from>${docker.from}</from>
                                <assembly>
                                    <basedir>/deployments</basedir>
                                    <descriptor>${project.basedir}/src/main/resources/assemblies/apiman-gateway-app.xml</descriptor>
```

This config works very well excepted that all the content defined under the folder maven will be copied to /deployments as defined within the Dockerfile generated 

```
COPY maven /deployments/
```

If we would like to copy resources to a specific path, this is not possible. Si, I would like to suggest that the docker command COPY is also supported

```
<build>
     <copy>maven/secret /secret</copy>
</build>
```

**Comment by rhuss** [comment]
You should use a another `baseDir` than `/deployments` (which is the default). That goes directly below `<build>`.

@cmoulliard could I have a look on the full project so that I can reproduce it ? (and maybe fix the setup)

**Comment by rhuss** [comment]
If you need more flexibility for creating images, I recommend to use the dockerfile mode, where an external Dockerfile is evaluated. `<copy>` wont be added to the plugin-config mode since this overlaps with the assembly (and there's nothing a <copy> could do what an assembly can't)

**Comment by cmoulliard** [comment]
Here is the link - https://github.com/cmoulliard/fabric8-ipaas/blob/56d90415bfbcc8bc79b7c8cec3cc2e62629fb286/apiman-gateway/pom.xml#L124

**Comment by rhuss** [comment]
Solution that worked: 

* Set `baseDir` to `/`
* Use `deployments` instead of `.` in the assembly descriptor
