### ISSUE TITLE
Add a default ignore pattern when dockerFileDir is root project dir

### ISSUE THREAD

**Issue by rhuss** [fabric8io/docker-maven-plugin#467]
When the `dockerFileDir` is the same as `${project.baseDir}` then it makes sense to have a default exclude for `target/**` when building the docker image.

**Comment by francescoforesti** [comment]
Hi, I think I'm hitting this issue right now. I'm new to Docker and I'm trying to follow the docs to do a `docker:build`but I keep getting this error : 
`Execution default-cli of goal io.fabric8:docker-maven-plugin:0.16.5:build failed: A tar file cannot include itself.`
I've put the Dockerfile and a `.maven-dockerignore` with 
`<fileset dir="." casesensitive="yes">
    <exclude name="target/**"/>
</fileset>`
in the project root. The dockerFileDir is set up as
`<dockerFileDir>${project.basedir}</dockerFileDir>`
I have also tried renaming the file to .maven-dockerexclude but the result is the same.
Do You know of any workaround for this?

Thanks

**Comment by rhuss** [comment]
The `.maven-dockerignore` is supposed to contain ant-stryle wildcard patterns.

So simply add a single line

```
target/**
```

to this file.

**Comment by hindsholm** [comment]
I also find this quite confusing.
I have my Dockerfile in the project root, and I can easily build it with 
`docker build -t some/name .`
But in order to make this work with docker-maven-plugin, I have to create a `.maven-dockerinclude` file which IMHO is counter-intuitive. I would suggest being more compatible with standard Docker.

**Comment by alan-czajkowski** [comment]
👍

**Comment by rhuss** [comment]
That's an old issue and has been [fixed](https://github.com/fabric8io/docker-maven-plugin/blob/2ff5bd4c13daa269ef08daa72f824a117dfe785b/src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java#L334) since a long time (i.e. target is excluded by default). Also note the 'simple Dockerfile' mode which works without any configuration.

Sorry, forgot to close this issue, doing it now.

**Comment by alan-czajkowski** [comment]
@rhuss can you point to an example that uses the "simple Dockerfile" mode

**Comment by rhuss** [comment]
Sure --> https://github.com/fabric8io/docker-maven-plugin/tree/master/samples/smallest or https://github.com/fabric8io/docker-maven-plugin/tree/master/samples/zero-config
