### ISSUE TITLE
docker:start : ulimit option not configurable

### ISSUE THREAD

**Issue by alexist** [fabric8io/docker-maven-plugin#484]
Hello,
In order to start my container, i have to set the option "--ulimit" in the command line : 
"docker run --ulimit memlock=-1:-1 ....."

I checked the docker-maven-plugin documentation and the source code, but didn't see anything related to this.

It would be nice if plugin can manage this.

**Comment by rhuss** [comment]
You are right, this is currently not supported but would be a nice addition. If you feel fancy, PRs are always welcome ;-) If not no problem, we can implement it in a later release. 

Just in case, let me know whether you are interested, I could give you the proper pointers (it's an easy one).

**Comment by alexist** [comment]
Hi,

Yes i'd like to contribute a PR on this subject

2016-06-28 17:07 GMT+02:00 Roland Huß <notifications@github.com>:

**Comment by rhuss** [comment]
Great !

You'd best start at [RunImageConfiguration](https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java) which holds the configuration for `<run>` elements. There I would introduce a List property, e.g. `List<ULimitConfig> ulimits` where ULimitConfig would be a new Object with properties *name*, *soft* and *hard*. These translate then to the config as described [here](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-a-container).

At the end it should be possible to specify ulimits within `<run>` like

```xml
<run>
   <ulimits>
      <ulimit>
         <name>memlock</name>
         <hard>-1</hard>
         <soft>-1</soft>
      </ulimit>
      ....
   </ulimits>
   ....
</run>
```

At lease one of  `<hard>` or `<soft>` should be provided. You can have a look how the other run options are evaluated.

When you are doing the PR, it would be awesome if you could 

* Provide a Unit-Test (when its not too hard)
* Update the documentation in `doc/manual/docker-start.md`
* Add the possibility to add these options also for the [PropertyConfigHandler](https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java)

Don't hesitate to ask, if something is not clear ;-)

Thanks again, we  **love** pull requests ;-)

**Comment by alexist** [comment]
Hello,
I have created the PR https://github.com/fabric8io/docker-maven-plugin/pull/507
Tell me if anything is wrong

**Comment by rhuss** [comment]
Thanks a lot ! It will be available in the next release.
