### ISSUE TITLE
wait log sometimes does not work

### ISSUE THREAD

**Issue by burtsevyg** [fabric8io/docker-maven-plugin#489]
When I change version of plugin from 0.15.1 to 0.15.7 build failed with error: 
`"Timeout after 300049 ms while waiting on log out 'Database opened.'"`
In pom.xml
```
...
                                <wait>
                                    <log>Database opened.</log>
                                    <time>300000</time>
                                    <exec>
                                        <postStart>/tmp/myScript.sh</postStart>
                                    </exec>
                                </wait>
...

```
move to another server with plugin 0.15.1 version I get this error too:
```
could not open session
Timeout after 300049 ms while waiting on log out 'Database opened.
```

**Comment by rhuss** [comment]
Could you please share a bit more of context ? E.g. it would be perfect if you could provide a working example pom.xml which exhibits this behaviour. BTW, 0.15.9. is out (but there has no changes /wrt log based waiting)

thanks ...

**Comment by burtsevyg** [comment]
Sorry, I forgot close issue. There is error in configuration of docker server.

**Comment by rhuss** [comment]
np, I was late anyway :)
