### ISSUE TITLE
Resolved images are cached even if <image> configuration changes between executions

### ISSUE THREAD

**Issue by twz123** [fabric8io/docker-maven-plugin#495]
When executing more than one goal with different values for the `<image>` configuration, the first `<image>` configuration is used to resolve images. The result is stored inside the plugin context. The next execution may potentially have a different configuration for `<image>`, but won't re-resolve images, but reuse the resolved images that have been stored in the plugin context. Hence it will operate on the wrong set of resolved images.

**Comment by rhuss** [comment]
I'm just about to remove the caching for the next release. It wasn't such a good idea (also because of classloader issues I had lately).

That will be in the next release, which will probably released today.

**Comment by twz123** [comment]
:clap: :ok_hand:

**Comment by rhuss** [comment]
Fixed in 0.15.8

**Comment by zbelzer** [comment]
Thanks for fixing this!

**Comment by zbelzer** [comment]
Actually, it only passed because I had commented out the build in my second module. :cry: 

I have a parent project with two modules, let's call them A and B.
A builds image a
B builds image b, but b runs some integration tests with a container from image a

However, when B is telling me it's building an image, it's telling me it's building a but shoves b's content in there.

This sounds like the bug you fixed, but seems to be happening with 0.15.9. Is there something I'm missing?

**Comment by jgangemi** [comment]
can you post your poms?

**Comment by zbelzer** [comment]
I don't know if I'm legally able to do that as it's for my company. Is there anything in particular that I should look for in the configuration arrangement of my docker plugin sections?

**Comment by zbelzer** [comment]
For demonstration, this is the build portion of the first module and the build portion of the second module. It's pretty clear from the target paths and image names that the wires are crossed.

```
[INFO] Copying files to /home/zbelzer/clearstory/catalog-service/catalog-service-db/target/docker/dkr.ecr.us-west-2.amazonaws.com/catalog-service-db/38.0.2-SNAPSHOT/build/maven
[INFO] Building tar: /home/zbelzer/clearstory/catalog-service/catalog-service-db/target/docker/dkr.ecr.us-west-2.amazonaws.com/catalog-service-db/38.0.2-SNAPSHOT/tmp/docker-build.tar
[INFO] DOCKER> docker-build.tar: Created [dkr.ecr.us-west-2.amazonaws.com/catalog-service-db:38.0.2-SNAPSHOT] "catalog-service-db" in 202 milliseconds
[INFO] DOCKER> [dkr.ecr.us-west-2.amazonaws.com/catalog-service-db:38.0.2-SNAPSHOT] "catalog-service-db": Built image sha256:12f59

... bunch of other stuff ...

[INFO] Copying files to /home/zbelzer/clearstory/catalog-service/catalog-service/target/docker/dkr.ecr.us-west-2.amazonaws.com/catalog-service-db/38.0.2-SNAPSHOT/build/maven
[INFO] Building tar: /home/zbelzer/clearstory/catalog-service/catalog-service/target/docker/dkr.ecr.us-west-2.amazonaws.com/catalog-service-db/38.0.2-SNAPSHOT/tmp/docker-build.tar
[INFO] DOCKER> docker-build.tar: Created [dkr.ecr.us-west-2.amazonaws.com/catalog-service-db:38.0.2-SNAPSHOT] "catalog-service-db" in 132 milliseconds
[INFO] DOCKER> [dkr.ecr.us-west-2.amazonaws.com/catalog-service-db:38.0.2-SNAPSHOT] "catalog-service-db": Built image sha256:84887
[INFO] DOCKER> [dkr.ecr.us-west-2.amazonaws.com/catalog-service-db:38.0.2-SNAPSHOT] "catalog-service-db": Removed image 
```

**Comment by jgangemi** [comment]
yeah - there is something off but w/o being able to see the relevant potions of the poms...

i think you'd be ok if you just substituted any company specific information w/ something generic.
