### ISSUE TITLE
Enhancement Request: Dynamic Host Port defines Environment Variable on container start

### ISSUE THREAD

**Issue by stagrlee** [fabric8io/docker-maven-plugin#496]
Really amazing plugin 👍 

I would like the ability to have the plugin not only define a maven property for a port the plugin chooses to use on boot, but also pass that port into the container as an environment variable so the webserver in the container can get the HTTP URL rewrite working correctly.  Something like this.

```xml
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <images>
            <image>
              <name>${my.image.name}</name>
              <alias>${my.docker.file.dir}</alias>

              <run>

                <env>
                  <SERVER_URL>http://{{my.host}}:{{my.http.port}}</SERVER_URL>
                </env>
                <ports>
                  <port>${my.host}:${my.http.port}:${container.http.port}</port>
                </ports>
```

To work around, I get a random port from [build-helper-maven-plugin:reserve-network-port](http://www.mojohaus.org/build-helper-maven-plugin/reserve-network-port-mojo.html) during an early maven phase and pass that into docker-maven-plugin.  The disadvantage of this approach is I need to run the whole lifecycle to stop/start instead of `mvn docker:stop docker:start` which would be super clean.  Now I do `mvn clean integration-test` which pulls the whole environment down and up.  This is what I have now...

```xml
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>1.10</version>
        <executions>
          <execution>
            <id>reserve-network-port</id>
            <phase>process-resources</phase>
            <goals>
              <goal>reserve-network-port</goal>
            </goals>
            <configuration>
              <portNames>
                <portName>my.http.port</portName>
              </portNames>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <images>
            <image>
              <name>${my.image.name}</name>
              <alias>${my.docker.file.dir}</alias>
              <build>
                <tags><tag>latest</tag></tags>
                <dockerFileDir>${my.docker.file.dir}</dockerFileDir>
                <assembly>
                  <descriptor>${my.docker.file.dir}/assembly.xml</descriptor>
                </assembly>
              </build>
              <run>
                <skip>${skipITs}</skip>
                <hostname>${my.docker.file.dir}</hostname>
                <domainname>${my.test.domain}</domainname>
                <env>
                  <SERVER_URL>http://${docker.host.address}:${my.http.port}</SERVER_URL>
                </env>
                <ports>
                  <port>${my.host}:${my.http.port}:${container.http.port}</port>
                </ports>
```

**Comment by stagrlee** [comment]
Not sure why my ${docker.host.address} works here compared to #461

**Comment by jgangemi** [comment]
unless i'm missing something, i don't think what you're asking for is possible b/c of a chicken and egg situation...docker needs to start the container to know what port its running on, so how could it pass that port into the running container?

if you re-wrote your `build-helper-maven-plugin` configuration so the `configuration` element was not defined inside the `execution`, then you could just explicitly invoke that goal along side `docker:start`.

**Comment by stagrlee** [comment]
I want this to occur during startup (before runtime).

- The plugin can ask for a free port from the docker host OS by calling something like build-helper-maven-plugin straight from java.
- When constructing the docker start command, the ports can be passed to docker along with a plugin created environment variable.  

The list of environment variables sent to the docker start command would need to created after ports were selected.  Its a hybrid case because the port is selected after invocation of the plugin but before the invocation of docker start.

**Comment by stagrlee** [comment]
> if you re-wrote your build-helper-maven-plugin configuration so the configuration element was not defined inside the execution, then you could just explicitly invoke that goal along side docker:start.

This is probably some maven I need to learn!

**Comment by stagrlee** [comment]
I looked into pre-defining the port.  We had our build that way but went to dynamic ports in the builds to avoid occasional stuck sockets.  We were getting some build breaks due to the pre-configuration.

**Comment by jgangemi** [comment]
this seems like a specific use case that doesn't necessarily apply to the general plugin. i think your best bet would be to move the `buildhelper` configuration outside of the `execution` block so you can invoke that goal from outside of a lifecycle and then use it in conjunction w/ `docker:start`.

if that doesn't work for you, then i'd recommend leaving the configuration the same for your automated builds and define a static port to be used for local development and then you can use the `docker:start` command by itself.

**Comment by stagrlee** [comment]
Thanks, excellent pointers.

I think its decently generic as most server apps need to send client apps reply addresses so that the client can connect.  As described above, that network address would be very late binding and all in one step.  But, as we both figured out, there are about 5 ways to do this.

**Comment by jgangemi** [comment]
you may need to define your underlying use case a little bit better then. i'm running plenty of docker apps with random  and the only port i need to pass into my container is whatever i want to expose jmx over b/c that needs to be a 1:1 mapping in order for it to work properly.

another option could be to use the `nginx-proxy` that could accept requests on a known port and then forward them on to whatever the underlying containers port is.

i'm just not sure i think it should fall under this plugins wheelhouse to be able to pick a random port on the operating system to use and then wire that all together upon container startup, but @rhuss may have a different opinion. :)

**Comment by rhuss** [comment]
@stagrlee I wonder how the `buildhelper` plugin is able to find ports on the Docker host since I dont see any host configured for the plugin ?

And as you pointed out its always a bit tricky to find free ports (which btw  you need to do outside of Maven, too when you want to use the image somewhere else, so its not really portable). Of course you can detect it from the outside but then you are still open for race conditions since there is a time span between detection and usage. 

Tbh, its not something I consider as an important use case for this plugin, since it can be easily done from the outside as you did. However, it would be much better if you could detect the externally mapped ports directly within Docker so you can do the rewrite from this information. See https://github.com/docker/docker/issues/3778 for an ongoing discussion on this.

Also orchestration platform like Kubernetes have concept of Ingress routes, which make this sort of use case much more feasible.

I'll close this issue for now, feel free to continue the discussion, though.

**Comment by jgangemi** [comment]
i don't know all the ins and outs of the docker code base, but i'm surprised they just don't expose it as an environment variable inside the container. i would think they'd know the external port they are going to map to before they start the container.
