### ISSUE TITLE
Build goal fails if target folder does not exist

### ISSUE THREAD

**Issue by niriak** [fabric8io/docker-maven-plugin#497]
The build goal fails with an error, when the target folder does not exist.
This looks like a regression: version to reproduce is 0.15.8, last working version is 0.15.7.

> [INFO] --- docker-maven-plugin:0.15.8:build (build docker image) @ bind ---
> [ERROR] DOCKER> Cannot create <some-path>/project/target/docker_build.timestamp for storing time 1467102406129

**Comment by rhuss** [comment]
Thanks, will fix that asap.

**Comment by rhuss** [comment]
Just triggered release 0.15.9, should be available soon.

**Comment by rhuss** [comment]
0.15.9 is out. sorry for any inconvenience.
