### ISSUE TITLE
<wait> on container to finish

### ISSUE THREAD

**Issue by rhuss** [fabric8io/docker-maven-plugin#498]
A new `<wait>` section should be added which waits until a container is finished and exit the build according to the exit status of the container. This is useful for batch like jobs where one simply want to run a container e.g. for initializations or other task.

This could look like

``` xml
<wait>
   <exit>0</exit>
</wait>
```

for an expected exit code of 0 (which could be the default, but since Maven doesnt allow empty tags one probably needs to provide it in any case)

**Comment by robythomas** [comment]
I have the exact requirement to run a container that would eventually exit with a proper code signifying a job completed status. Currently, I <wait> on a <log> pattern in that job container. But I've seen that somtimes this pattern matching doesn't catch it. It has happened in about two or three times already for me. While that perhaps is an issue with the <log> mechanism, having this wait for exit is exactly what I'm looking for.

**Comment by rhuss** [comment]
Implemented with #765
