### ISSUE TITLE
wait http without redirect

### ISSUE THREAD

**Issue by Albatarm** [fabric8io/docker-maven-plugin#499]
Hi,

It is possible to disable redirects on the http waiter for `docker start` goal ? 
I would like to test that my image redirect correctly. But currently the wait fail because it try to get the redirected URL.

**Comment by rhuss** [comment]
That's currently not possible, sorry. However, it shouldn't be hard to implement. Fancy doing a PR ?
This would be the [entry point](https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/util/WaitUtil.java#L153-L153).

**Comment by Albatarm** [comment]
Pull request #500

**Comment by rhuss** [comment]
Thanks for the PR :). The question is, whether we want to have it configurable or not ? I'm not sure about a use case where waiting for a redirected URL to succeed makes sense, so whether it is worth to introduce such a config option. 

wdyt ?

**Comment by Albatarm** [comment]
I agree. We basically want to make sure the application is responding and is correctly initialized. Waiting for the URL given by redirection makes no sens.

**Comment by Albatarm** [comment]
We could introduce a config option when needed

**Comment by rhuss** [comment]
I think we can live without. I will take this over for the next release.

Thanks !
