### ISSUE TITLE
Save generated image to as a .tar file

### ISSUE THREAD

**Issue by kirasagi** [fabric8io/docker-maven-plugin#514]
I'm trying to see if a feature similar to [`docker save`](https://docs.docker.com/engine/reference/commandline/save/) exists. I want to share an image tar and use [`docker load`](https://docs.docker.com/engine/reference/commandline/load/) to actually load it up in a machine. I understand that sharing images is what registries are for but that's not set up yet. Is this possible? I couldn't find it in the docs (`docker:source` seems close but I don't think thats it).

**Comment by rhuss** [comment]
Sorry, this currently does not exist yet, but could make sense in certain cases. Still have to check how this work, but a `mvn docker:save` probably might be useful.

**Comment by rohanKanojia** [comment]
@rhuss Is this still a valid feature request? If yes, I would like to pick it up. Could you please provide me with some code pointers and implementation details?

**Comment by rhuss** [comment]
Actually, in the meantime we already added [docker:save](https://dmp.fabric8.io/#docker:save)

I think its save to close this issue.
