### ISSUE TITLE
build logs

### ISSUE THREAD

**Issue by tschurins** [fabric8io/docker-maven-plugin#517]
I couldn't find an option to show the logs when building an image.
It is very annoying when the build fails to not be able to see why...

**Comment by rhuss** [comment]
You need to set `-Ddocker.verbose` or put this into the plugin configuration.

**Comment by tschurins** [comment]
Thanks, both -Ddocker.verbose or adding <verbose>true</verbose> is working.
Coundn't find it in the doc though...

**Comment by rhuss** [comment]
Good point, will add it.

Sorry for the confusion ...
