### ISSUE TITLE
Is there a way to get container id for tests purpose

### ISSUE THREAD

**Issue by burtsevyg** [fabric8io/docker-maven-plugin#521]
I use jenkins pipeline plugin in which I create pipeline: 
build war - > 
update db(from previous release version) - >
create images - > 
run container(app, db) -> 
run tests -> if test failed I need wait while programmers find root of problem -> than remove containers.
I use auto generate names because many builds may build in one time on the same build agent.
I need save container id for know which containers I need to remove.
How can i get container id?

**Comment by rhuss** [comment]
It's set as an implicit Maven property `docker.container.<alias>.ip`. See https://fabric8io.github.io/docker-maven-plugin/#docker:start for details.

**Comment by burtsevyg** [comment]
Thank you very much!

**Comment by burtsevyg** [comment]
Save docker.container.<alias>.id to file for use outside maven tests.
