### ISSUE TITLE
META-INF/plexus/components.xml should NOT specify plugin versions

### ISSUE THREAD

**Issue by jakub-bochenski** [fabric8io/docker-maven-plugin#539]
Per https://books.sonatype.com/mvnref-book/reference/writing-plugins-sect-plugins-lifecycle.html :

> Set the name of the packaging type under role-hint, and the set of phases containing the coordinates of the goals to bind (omit the version). Multiple goals can be associated with a phase using a comma delimited list.
> 
> Overriding the Default Lifecycle. 
> 
```
> <component-set>
>     <components>
>         <component>
>             <role>org.apache.maven.lifecycle.mapping.LifecycleMapping</role>
>             <role-hint>zip</role-hint>
>             <implementation>
>                 org.apache.maven.lifecycle.mapping.DefaultLifecycleMapping
>             </implementation>
>             <configuration>
>                 <phases>
>                     <process-resources>
>                         org.apache.maven.plugins:maven-resources-plugin:resources
>                     </process-resources>
>                     <compile>
>                         org.apache.maven.plugins:maven-compiler-plugin:compile
>                     </compile>
>                     <package>org.sonatype.mavenbook.plugins:maven-zip-plugin:zip</package>
>                 </phases>
>             </configuration>
>         </component>
>     </components>
> </component-set>
```

Why would you force users to use e.g. a specific version of the compiler plugin instead of letting Maven pick it via the usual mechanism?

The change is rather trivial so I can send a PR if you agree to this..

**Comment by rhuss** [comment]
Thanks, just fixed this. I haven't added the version intensionally, just a c&p issue.
