### ISSUE TITLE
Allow @sha256 digest for tags in FROM

### ISSUE THREAD

**Issue by stephenlawrence** [fabric8io/docker-maven-plugin#541]
When I try to use a digest tag in my Dockerfile FROM: such as "FROM: mytomcat@sha256:b61b1b823ec66a2875c44572885fa332990b3aa0055ed50abf7f94837c9f7925" I get this:

[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.15.14:build (docker-build) on project kestrel-docker: Execution docker-build of goal io.fabric8:docker-maven-plugin:0.15.14:build failed: Given repository name 'mytomcat@sha256:b61b1b823ec66a2875c44572885fa332990b3aa0055ed50abf7f94837c9f7925' is invalid:
[ERROR] \* image part 'mytomcat@sha256' doesn't match allowed pattern '(?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]_[a-zA-Z0-9])(?:(?:.(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]_[a-zA-Z0-9]))+)?(?::[0-9]+)?/)?[a-z0-9]+(?:(?:[._]|__|[-]_)[a-z0-9]+)_(?:/[a-z0-9]+(?:(?:[._]|__|[-]_)[a-z0-9]+)_)?'

I see various mentions in docker re: digest usage and our docker-compose.yml uses it just fine. Do the regex's need to be updated?

**Comment by stephenlawrence** [comment]
Version 0.15.14

**Comment by rhuss** [comment]
Yes, seems to be a bug. The pattern where taken directly from Docker at that time, probably before digests where introduced. 

The relevant spots are:

* d-m-p validation: https://github.com/fabric8io/docker-maven-plugin/blob/39e2577b6a74f2affcecd8c99f919e865e5ee23a/src/main/java/io/fabric8/maven/docker/util/ImageName.java#L217-L217
* Docker Regexps (the best available resource I found):
   - https://github.com/docker/docker/blob/master/vendor/src/github.com/docker/distribution/reference/regexp.go
  - https://github.com/docker/docker/blob/master/vendor/src/github.com/docker/distribution/reference/reference.go

'will fix that, but cant promise when (have a busy week before me). If you feel fancy and need it earlier, we take also pull requests ;-)

**Comment by neelam-007** [comment]
i'm still seeing this problem - even with docker-maven-plugin v 0.22.1 - ?

io.fabric8:docker-maven-plugin:0.22.1:build (build) on project portal-enterprise: Execution build of goal io.fabric8:docker-maven-plugin:0.22.1:build failed: Given Docker name 'docker.io/jetty@sha256:82d64b324a80ac32b3f6412f2d9fb9fa0b7ade76f748b9f0fd1a9bde416f7adc' is invalid:
[ERROR] * image part 'jetty@sha256' doesn't match allowed pattern '[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?(?:(?:/[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?)+)?'
[ERROR] See http://bit.ly/docker_image_fmt for more details

Dockerfile:

FROM docker.io/jetty@sha256:82d64b324a80ac32b3f6412f2d9fb9fa0b7ade76f748b9f0fd1a9bde416f7adc

pulling directly from the command line works, but i need to build my docker image using dockerfile
