### ISSUE TITLE
Avoiding chown to reduce the image size

### ISSUE THREAD

**Issue by dje06** [fabric8io/docker-maven-plugin#544]
The issue #175 introduced an extra layer for the chown that is doubling the content size of the chown ed folder (for an image containing the jdk+jboss it could be huge).
Is it possible to avoid this extra layer using a single CMD (without the COPY)?

By doing a curl and chown in the same RUN command, this drastically reduces the image size, but in this case I have to use an external Dockerfile and I'd prefer being fully maven-style (using the assembly).

Any idea how to fix this?

**Comment by rhuss** [comment]
I see the point, but I wonder how we could doing the COPY / ADD from the assembly and the `chown` in one layer. The real pita is that https://github.com/docker/docker/issues/6119 doesnt get fixed.

If you have an idea I'm happy to add this as an optimization.

**Comment by smallsmallc** [comment]
@rhuss Hi Roland, as [moby/moby#6119](https://github.com/moby/moby/issues/6119) is fixed now, could you please kindly re-consider to make an optimization?

**Comment by rhuss** [comment]
Good point, will start working on it hopefully soonish. Do you know the Docker (or even better API) version, since when these flags are available ?

**Comment by smallsmallc** [comment]
`The feature is included in Docker 17.09 and up` quoted from [moby/moby#6119](https://github.com/moby/moby/issues/6119)

**Comment by KowKiller** [comment]
I also noticed another downside of current implementation.
Since the temporary directory name is randomly generated, docker can't reuse the build cache even if the content of the assembly is not changed.

![image](https://user-images.githubusercontent.com/8671027/68791017-bc03d080-0648-11ea-846b-bf9b5ac3c147.png)

Using --chown would solve this too.

**Comment by rhuss** [comment]
@rohanKanojia If you have some spare cycles (not necessarily for the next release), could you give a look to get rid of our own `chown` mechanism and use that from Docker (for Docker >= 17.09) ?
