### ISSUE TITLE
allow empty cmd

### ISSUE THREAD

**Issue by mufasa1976** [fabric8io/docker-maven-plugin#546]
Is it possible to force the creation of an empty cmd?

I have a Spring-Boot Application as an Entrypoint (```ENTRYPOINT ["/maven/springBoot.jar","run"]```) and would like to give Arguments on Runtime by ```docker run``` on the Command-Line:

```
docker run -d path/springboot --spring-profiles-active=DEV
```

To be able to give this an Empty ```CMD []``` has to be specified so that any Arguments given to ```docker run``` would be interpreted as Arguments to the given Entrypoint.

At the moment this might be impossible because the Docker-Plugin checks for any empty Command-Blocks (neither with ```<cmd><exec/></cmd>``` nor with ```<cmd><shell/></cmd>``` nor with ```<cmd/>```).

**Comment by rhuss** [comment]
If you completely leave out the `<cmd>` does this help ? Or is it because you need to overwrite the `CMD` from your base image ?

**Comment by mufasa1976** [comment]
You're right. It isn't necessary to put a ```CMD[]``` at the End of the Dockerfile to put Parameters to the Entrypoint. So I will close this Issue. Thank you for your support.
