### ISSUE TITLE
Exit status of executed commands after wait in container is not checked

### ISSUE THREAD

**Issue by burtsevyg** [fabric8io/docker-maven-plugin#547]
It would be nice to check exit status of executed commands after wait in container and if it is not equal zero break a build. We always need to know that something goes wrong.

**Comment by rhuss** [comment]
Thanks for opening the issue. Will need to think a bit how to integrated that best for postStarat and preExit  commands.

**Comment by burtsevyg** [comment]
Oh oh oh I need it so much.

**Comment by burtsevyg** [comment]
Could you please tell me what is the progress?

**Comment by rhuss** [comment]
Sorry, no progress yet (but still open for pull requests, as always ;). Any suggestion how to integrate that best? (from an UI perspective)

**Comment by burtsevyg** [comment]
This feature is done.
Now I can add 
`<breakOnError>true</breakOnError>`
