### ISSUE TITLE
support custom key for exposed container properties

### ISSUE THREAD

**Issue by jpraet** [fabric8io/docker-maven-plugin#557]
Currently container properties such as ip are exposed as `docker.container.<alias>.ip`, e.g. `docker.container.jboss.ip`.

In my case the docker plugin configuration is located in a corporate parent pom. All our projects extend from this parent pom. Therefore, in the parent pom, the alias is assigned dynamically as `<alias>jboss-${project.artifactId}-${project.version}` with `<namingStrategy>alias</namingStrategy>`.

This means the container ip is exposed with name `docker.container.jboss-${project.artifactId}-${project.version}.ip`. I am not able to access this property easily, because the name is built dynamically.

It would be nice if I could configure something like `<containerPropertyKey>jboss</containerPropertyKey>` in the image run configuration in order to still have dynamic container names, but with static container property keys.

**Comment by rhuss** [comment]
Yeah, makes sense. Let me check how we can put it into the configuration.

**Comment by jpraet** [comment]
Thanks! I tried to test out the new exposedPropertyKey configuration, but ran into another issue when upgrading: #583
