### ISSUE TITLE
save the image as tar

### ISSUE THREAD

**Issue by arthurtsang** [fabric8io/docker-maven-plugin#561]
it'd be nice if we could save the docker image as a tar file (not the source as in docker-tar packaging type) so that we can upload that to nexus or distribute to another developer.

**Comment by rhuss** [comment]
You mean the same output as `docker export` ?

**Comment by abrahamjaison01** [comment]
@arthurtsang That is what I was looking for too..!
@rhuss : I think he meant about `docker save`. It will be good if we are able to save the image as a tar file and obtain it in the local repository.

**Comment by rhuss** [comment]
Ok, I see. You want save an image (and attach it as articfact) and not export an container. 

I see the value in it, however one should be aware that these tars can be quite large (and rendundant as they contain other dependant jars from the repo). Also, there is no easy way to remove stuff from a repository (especially not for remote repositories), so you can blow up things easily.

@arthurtsang @abrahamjaison01 what is your use case or workflow where you would need such an image ?

**Comment by abrahamjaison01** [comment]
@rhuss My use case is purely within an internal network, where we are not able to push our images to the docker hub due to firewall settings in educational institution I study. In order give the docker image to my peers, I rely on docker save and docker load commands within my project team. Since pushing the images is not permitted, it would be great to have docker save command included in the maven plugin as well.

**Comment by andyliddle** [comment]
I also would like to see this option.

I cannot push my images to an internal registry because they all depend on microsoft/nanoserver.   My test network does not have internet access so i am unable to obtain the dependent images.

**Comment by rhuss** [comment]
@andyliddle In the meantime we introduced a [docker:save](https://dmp.fabric8.io/#docker:save), we were just lazy in closing issues ;-)

A missing piece is probably `load` support. Is this something you would need, too ? If so please open a new issue. This issue about save and can probably be closed now.
