### ISSUE TITLE
Is there any way to see the building output from the plugin?

### ISSUE THREAD

**Issue by edesdan** [fabric8io/docker-maven-plugin#573]
I need to see the output log from docker build via the plugin. How to do that?

**Comment by burtsevyg** [comment]
+1
I need it too.

**Comment by rhuss** [comment]
Try `-Ddocker.verbose`. You can set verbose mode also as a permanent config option.

**Comment by edesdan** [comment]
Oh, very nice! How to set as permanent config option?

**Comment by rhuss** [comment]
Simply:

```xml
<plugin>
   ...
   <configuration>
      <verbose>true</verbose>
   ....
```

See also https://dmp.fabric8.io/#global-configuration

**Comment by edesdan** [comment]
Ah very nice, I love this plugin! thanks guys! +1000

**Comment by rhuss** [comment]
thanks :) going to close the issue, feel free to open a new one in case.
