### ISSUE TITLE
only container properties of first image are exposed

### ISSUE THREAD

**Issue by jpraet** [fabric8io/docker-maven-plugin#583]
As of version 0.16.3, it looks like only the container properties of the first image are exposed.

attached minimal pom.xml example can be used to reproduce the issue:

[pom.xml.txt](https://github.com/fabric8io/docker-maven-plugin/files/522561/pom.xml.txt)

It only outputs: 

  **\* property: docker.container.first-container.id

Expected output:

  **\* property: docker.container.first-container.id
  **\* property: docker.container.second-container.id

This worked in 0.16.2.

**Comment by rhuss** [comment]
Fixed with #590
