### ISSUE TITLE
not possible to bind windows folder

### ISSUE THREAD

**Issue by mireczatko** [fabric8io/docker-maven-plugin#587]
using absolute path with drive-letter is completely bad idea, because of a colon there.

```
<volumes>
    <bind>C:\Users\username\docker:/mnt</bind>
</volumes>
```

this leads to failed build.

using same path without drive-letter using backslash or forward slash causes same configuration:

```
"Mounts": [
    {
        "Source": "/Users/username/docker",
        "Destination": "/mnt",
        "Mode": "",
        "RW": true,
        "Propagation": "rprivate"
    }
]
```

source /Users/username/docker is not found on windows machine...
how to deal with it?

**Comment by rhuss** [comment]
The bind spec is sent literally to the Docker daemon, so you should specify it the way Docker expects its (same as for `docker run -v `)

For using Maven defined properties we use [this conversion](https://github.com/fabric8io/docker-maven-plugin/blob/702a950439795e7a9f17982484599de0ff7270aa/src/main/java/io/fabric8/maven/docker/util/EnvUtil.java#L238-L248) as provided by #188 

Does this answer your question ?

**Comment by mireczatko** [comment]
Hi @rhuss, thank you for your answer and sorry about my late post. I came to the problem back after longer time and after upgrading docker for windows version to 1.12.3 and docker-maven-plugin version to 0.18.1 everything seems to be working perfectly. Thank you.
