### ISSUE TITLE
Lots of warnings are displayed when assembly.mode is tar or tgz when building on windows

### ISSUE THREAD

**Issue by zoltanersek** [fabric8io/docker-maven-plugin#591]
I am doing a build on windows want to keep the permissions on the assembly so I need to use assembly mode tar/tgz. 

Because of this the TarArchiver outputs a lot of warnings when creating the assembly:   **[WARNING] Entry: filename is longer than 100 characters.**

I've noticed when creating the AssembyArchiver the hardcoded value from: DockerAssemblyConfigurationSource is used: 

         @Override
        public String getTarLongFileMode() {
          return "warn";
        }

Can this be changed to be configurable? Or at least read the: assembly.tarLongFileMode property defined on the project. 

Thanks

**Comment by rhuss** [comment]
Is fixed now with 0.17.1
