### ISSUE TITLE
Sometimes don't match log output when wait on log

### ISSUE THREAD

**Issue by smoczarski** [fabric8io/docker-maven-plugin#595]
When configured in run section to wait until a defined log message happens sometimes this log output won't be recognized. 
Config:
```
<run>
...                                        
   <wait>
      <log>Setup finished</log>
      <time>30000</time>
   </wait>
</run>
```
Sometime the build breaks because of this:
```
setup> Setup finished
...
[ERROR] DOCKER> [tns-ticket/setup] "setup": Timeout after 30076 ms while waiting on log out 'Setup finished'
[ERROR] DOCKER> Error occurred during container startup, shutting down...
```
Version: 0.16.8

**Comment by smoczarski** [comment]
Please see pull request https://github.com/fabric8io/docker-maven-plugin/pull/596

**Comment by rhuss** [comment]
Thanks a lot for issue and especially for the analysis and fix as well. Your PR has been applied to branch `integration`, will be available soon in the next release.

**Comment by smoczarski** [comment]
Thanks a lot for applying the patch!

**Comment by seanyinx** [comment]
@rhuss I am still having this issue with version 0.20.0.
```
crossapp-server> 2017-05-23 13:41:25,068 [INFO] Register microservice instance success. microserviceId=2 instanceId=2 endpoints=[rest://localhost:8080] lease 120s 
[ERROR] DOCKER> [crossapp-server:0.1.0-SNAPSHOT] "crossapp-server": Timeout after 120029 ms while waiting on log out 'Register microservice instance success'
```
Running 5 integration tests using docker maven plugin. All servers were started using docker and 4 out of 5 were successful. Sometimes all 5 tests can pass.

**Comment by rhuss** [comment]
@seanyinx Are you using unix socket or a TC connection to the Docker daemon ?

**Comment by seanyinx** [comment]
@rhuss I run the tests on Travis.
you can take a look at the build logs at https://travis-ci.org/WillemJiang/java-chassis/builds.
The recent failed builds are mostly related to this issue.

**Comment by mdsardar** [comment]
Anyone still facing this issue ? I'm getting the same when trying to initiate a docker image to run some funtional-tests. 
Any insights ?

[INFO] --- docker-maven-plugin:0.33.0:start (start-containers) @ function-tests ---
[INFO] DOCKER> [maven.com:5001/you/dev/couchbase:enterprise-6.5.0-2020] "couchbase": Start container 5a4af7309b2b
[ERROR] DOCKER> IO Error while requesting logs: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected Thread-19
[ERROR] DOCKER> [maven.com:5001/you/dev/couchbase:enterprise-6.5.0-2020] "couchbase": Timeout after 160121 ms while waiting on log out 'Setup finished'
[ERROR] DOCKER> Error occurred during container startup, shutting down...
[INFO] DOCKER> [maven.com:5001/you/dev/dev/couchbase:enterprise-6.5.0-2020] "couchbase": Stop and removed container 5a4af7309b2b after 0 ms
[ERROR] DOCKER> I/O Error [[maven.com:5001/you/dev/couchbase:enterprise-6.5.0-2020] "couchbase": Timeout after 160121 ms while waiting on log out 'Setup finished']

    docker-maven-plugin version : docker-maven-plugin:0.33.0
    Maven version (mvn -v) :

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /opt/homebrew/Cellar/maven/3.8.1/libexec
Java version: 1.8.0_292, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre
Default locale: en_IN, platform encoding: US-ASCII
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

    Docker version :3.3.3(64133)
    Docker engine: 20.10.6
