### ISSUE TITLE
Docker port ranges

### ISSUE THREAD

**Issue by xxlabaza** [fabric8io/docker-maven-plugin#598]
As I understand, I can't set up port ranges by setting port mapping. Can I set up it by another way, some additional arguments for running my Docker container, for example? I don't need a random mapping like **my-range:10100-10200**, but just simple **9100-9200:10100-10200** will be enogh

**Comment by rhuss** [comment]
afaiu its not possible to 'shift' ports by providing two ranges (if I read https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/ correctly). You can provide a custom range to which ports should be mapped randomly, though (however not yet supported in this plugin). Or did I misunderstood here something ?

**Comment by xxlabaza** [comment]
@rhuss thanks for answer, but I have already used exec-maven-plugin + docker-compose.yml file, instead of this plugin

**Comment by rhuss** [comment]
ok, thanks for your quick response (much faster than mine, sorry for that). If you don't mind I'd close this issue, feel free to reopen in case.
