### ISSUE TITLE
Cannot create docker access object 

### ISSUE THREAD

**Issue by adilfulara** [fabric8io/docker-maven-plugin#604]
Hi I get the following error when i try to use you plugin on jenkins. The same config works fine locally on a mac with docker 1.12.rc-3

```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.17.1:start (start-image) on project tmol-automation-tests: Cannot create docker access object: Cannot extract API version from server unix://127.0.0.1:1: Permission denied
```

System Info
```
Apache Maven 3.3.3
Docker version 1.6.2, build 7c8fca2
Ubuntu 14.04 LTS
```

Mvn configuration
```
<docker.maven.plugin.version>0.17.1</docker.maven.plugin.version>
<dockerHost>unix:///var/run/docker.sock</dockerHost>
```

I confirmed that docker remote api is working as jenkins user
```
curl -i --unix-socket /var/run/docker.sock http://localhost/info
HTTP/1.1 200 OK
Content-Type: application/json
Job-Name: info
Date: Mon, 31 Oct 2016 06:41:23 GMT
Content-Length: 1389

{"Containers":0,"Debug":0,"DockerRootDir":"/var/lib/docker","Driver":"devicemapper","DriverStatus":[["Pool Name","docker-202:1-1311136-pool"],["Pool Blocksize","65.54 kB"],["Backing Filesystem","extfs"],["Data file","/dev/loop0"],["Metadata file","/dev/loop1"],["Data Space Used","305.7 MB"],["Data Space Total","107.4 GB"],["Data Space Available","99.75 GB"],["Metadata Space Used","733.2 kB"],["Metadata Space Total","2.147 GB"],["Metadata Space Available","2.147 GB"],["Udev Sync Supported","true"],["Data loop file","/var/lib/docker/devicemapper/devicemapper/data"],["Metadata loop file","/var/lib/docker/devicemapper/devicemapper/metadata"],["Library Version","1.02.77 (2012-10-15)"]],"ExecutionDriver":"native-0.2","ID":"LVKT:NG2O:VQHR:ZCJW:TOTX:3GTA:6XIM:CPFF:74P6:7ODG:CEFT:245Y","IPv4Forwarding":1,"Images":0,"IndexServerAddress":"https://index.docker.io/v1/","InitPath":"/usr/lib/docker.io/dockerinit","InitSha1":"22082e594df367c79a11672c59a9d5da15851227","KernelVersion":"3.13.0-48-generic","Labels":null,"MemTotal":15770583040,"MemoryLimit":1,"NCPU":8,"NEventsListener":0,"NFd":14,"NGoroutines":14,"Name":"ip-10-146-17-18","OperatingSystem":"Ubuntu 14.04.2 LTS","RegistryConfig":{"IndexConfigs":{"docker.io":{"Mirrors":null,"Name":"docker.io","Official":true,"Secure":true}},"InsecureRegistryCIDRs":["127.0.0.0/8"]},"SwapLimit":0,"SystemTime":"2016-10-31T06:41:23.202018989Z"}
```

My jenkins job is creating a xvnc session and then trying to run the mvn project if that helps provide some more context.

Any pointers / tips ?
Thank you

**Comment by rhuss** [comment]
From the error message it seems pretty clear, that the Unix socket is not readable by the plugin because of missing permissions. The question e.g. is whether your curl test and the mvn call are similar. E.g. when the Jenkins worker itself is running in a Docker container (volume mounting the Docker unix socket), then this container must run in privileged mode.

I'm afraid with out more detailed information about your setup this hard to debug. Can you try to access this Unix socket directly before the mvn call from your build script, and see whether e.g. you can read something from it ? (e.g. the above curl command, but started from within Jenkins ?)

**Comment by adilfulara** [comment]
You can close this issue. We redid our docker install and that seems to have fixed the issue.

**Comment by podnov** [comment]
I am encountering this same issue and am attempting to work through it. 

I've had success (at runtime through a java debugger) changing the value of DockerAccessWithHcClient.UNIX_URL. The value is hard-coded to "unix://127.0.0.1:1/" but if I change it to a non-restricted socket ("unix://127.0.0.1:1000/", "unix://127.0.0.1:5000/"), everything works.

I'm wondering if, as the constant's associated comment reads ("// Base URL which is given through when using UnixSocket communication but is not really used"), this port number of 1 is intentionally imposing an potentially unnecessary permissions check?
