### ISSUE TITLE
where $DOCKER_HOST is set ?

### ISSUE THREAD

**Issue by yeganx** [fabric8io/docker-maven-plugin#615]
hi ,
I work with clustered openshift system , it's not up by vagrant ,
I have 2 question :
first : why in deploying my code as a developer by $mvn -Pf8-deploy , have to set $DOCKER_HOST in my terminal ? it can cause security problem in my opinion .
second : I have 5 openshift node , and in my master node I changed in /etc/sysconfig/docker 
OPTIONS=' --insecure-registry 172.30.0.0/16 --selinux-enabled --log-driver=json-file --log-opt max-size=50m'
to 
OPTIONS=' --insecure-registry 172.30.0.0/16 --selinux-enabled --log-driver=json-file --log-opt max-size=50m -H tcp://127.0.0.1:2376 -H unix:///var/run/docker.sock'
and restart my docker deomon , but in this case my docker is not running at all , out put of this 
$docker images
is :  Cannot connect to the Docker daemon. Is the docker daemon running on this host?
now i dont know how deploy my java project to openshift :( and what is my $DOCKER_HOST

### Info

docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker--vg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 4.237 GB
 Data Space Total: 10.68 GB
 Data Space Available: 6.446 GB
 Metadata Space Used: 1.319 MB
 Metadata Space Total: 12.58 MB
 Metadata Space Available: 11.26 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.36.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 7.64 GiB
Name: my-openshift-2-origin-master-0.example.com
ID: IP2R:ESMC:YBT6:NOFX:AAMN:OOQT:SNJ3:4H7P:M47C:3VTI:IVSY:KTXS
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: 192.168.20.23:5000 (insecure), docker.io (secure)
:
* Maven version (`mvn -v`) :
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)

```

my project is : https://github.com/yeganx/cdi.git
thanks,

**Comment by rhuss** [comment]
Duplicate of https://github.com/fabric8io/fabric8-maven-plugin/issues/644
