### ISSUE TITLE
Cannot find 'targetDir' in class io.fabric8.maven.docker.config.AssemblyConfiguration

### ISSUE THREAD

**Issue by haifzhu** [fabric8io/docker-maven-plugin#616]
_Please fill out the following information to help us in analyzing the issue, but feel free to skip it if you don't have the information at hand or if it does not apply. Please remove everything which does not apply to the issue. Including this info paragraph ;-)_

### Description
when i want to use targetDir to change the target directory in docker container, but the error will be dumped out  “
 [ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.17.2:build (default-cli) on project helloword: Unable to parse configuration of mojo io.fabric8:docker-maven-plugin:0.17.2:build for parameter targetDir: Cannot find 'targetDir' in class io.fabric8.maven.docker.config.AssemblyConfiguration -> [Help 1]”
### Info
The way of pom is like this:
                   <assembly>
                   <mode>dir</mode>
                   <targetDir>/opt</targetDir>
                   <descriptor>${project.basedir}/assembly.xml</descriptor>
                 </assembly>

* d-m-p version : 0.17.2
* Maven version (`mvn -v`) :
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-1.b15.el7_2.x86_64/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-123.9.3.el7.x86_64", arch: "amd64", family: "unix"
```
* Docker version : 1.10.3
* If it's a bug, how to reproduce :  it can be reproduced when i use targetDir.
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rhuss** [comment]
Sorry, the documentation already described the next version (coming next week). This slipped through already. Please use `basedir` until then.

**Comment by haifzhu** [comment]
Ok, thanks for your response.
