### ISSUE TITLE
AWS ECR login credential exchange

### ISSUE THREAD

**Issue by chonton** [fabric8io/docker-maven-plugin#637]
[AWS ECR](http://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html) requires a [cli login](http://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html) before any docker image push or pull.  I currently have my jenkins job running the `aws ecr get-login` command.  However, I prefer not install the amazon toolkit on all my build infrastructure and require all our developers to also install the amazon toolkit.

I would like to submit a PR that would invoke the [GetAuthorizationToken api](http://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_GetAuthorizationToken.html) to exchange AWS IAM credentials for temporary ECR credentials.  This PR would augment the AuthConfigFactory.  Any login credentials specified for an ECR repository would be considered IAM credentials needing exchange.

An ECR repository has a URL of form **https://**_awsAccountId_**.dkr.ecr.**_awsRegion_**.amazonaws.com**/_repositoryName_

1. Should credentials explicitly specified with docker.* properties be exchanged?
2. Should credentials from ~/.config/kube be exchanged?
3. Should credentials provided in plugin configuration be exchanged?
4. Should credentials from .m2/settings be exchanged?
5. Should credentials from ~/.docker/config.json be exchanged?
6. Should there be a flag to prevent the exchange?

I'm thinking that credentials 1, 2, 3, 4 should be exchanged.  ~/.docker/config.json likely contains already exchanged credentials. ~/.config/kube likely contains IAM credentials, as kubernetes ["will fetch and periodically refresh ECR credentials"](http://kubernetes.io/docs/user-guide/images/#using-aws-ec2-container-registry) .

**Comment by rhuss** [comment]
Thats a good idea.

If I understand you right, d-m-p would do an exchange to obtain an AWS token when it detects that in [pulls](https://github.com/fabric8io/docker-maven-plugin/blob/0912d1ffa3861ba8ca8c7b8e17a999a724487752/src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java#L360-L360) or [pushes](https://github.com/fabric8io/docker-maven-plugin/blob/0912d1ffa3861ba8ca8c7b8e17a999a724487752/src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java#L374-L374) ECR is used. 

This token is then used as password, right ?

Would it be harmful to always do the exchange ? And that point in the code the credentials has been already picked up from the various places so maybe we do not need distinguish all the cases above.

There should be a flag to opt-out for this feature if people want todo the authorization on their own.
