### ISSUE TITLE
Configuration error with Maven 3.0.5

### ISSUE THREAD

**Issue by hwellmann** [fabric8io/docker-maven-plugin#649]
### Description

According to README.md, d-m-p should be compatible with Maven 3.0.5, but it isn't.

I get the following error running under Maven 3.0.5. It does not occur with Maven 3.3.9:

```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.18.1:build (default-build) on project foo-docker-deploy: Unable to parse configuration of mojo io.fabric8:docker-maven-plugin:0.18.1:build for parameter from: Cannot assign configuration entry 'from' with value 'dummy-data' of type java.lang.String to property of type java.util.List -> [Help 1]
```

There seems to be an issue with the <volume> configuration element. The corresponding configuration snippet is:

```
<image>
     <alias>dummy-backend</alias>
     <name>docker.acme.com/core-backend:${foo.core.version}</name>
     <run>
         <namingStrategy>alias</namingStrategy>
         <volumes>
             <from>dummy-data</from>
             <bind>
                 <volume>${foo.system.config}:/usr/local/tomcat/conf/foo/foo-config.xml</volume>
             </bind>
         </volumes>
     </run>
</image>
```

I'm fine with officially raising the minimum required Maven version, but at least d-m-p should fail with a clear error message when it's running under an unsupported Maven version, e.g. by using the `<prerequisites>` tag.

### Info

* d-m-p version : 0.18.1
* Maven version (`mvn -v`) : 3.0.5
* Docker version : 1.12.3

**Comment by rhuss** [comment]
d-m-p was still supposed to work with Maven 3.0.5.

Your configuration is incorrect (as it is described in https://dmp.fabric8.io/#start-volumes). With Maven 3.3.9 you were just lucky that there seems to be an implicit conversion from a String to a single Element list (or, when comma separated, to a multi element string)

You can use the plugin still with 3.0.5 if you use the proper config format:

```xml
<image>
     <alias>dummy-backend</alias>
     <name>docker.acme.com/core-backend:${foo.core.version}</name>
     <run>
         <namingStrategy>alias</namingStrategy>
         <volumes>
             <from>
                 <image>dummy-data</image>
             </from>
             <bind>
                 <volume>${foo.system.config}:/usr/local/tomcat/conf/foo/foo-config.xml</volume>
             </bind>
         </volumes>
     </run>
</image>
```

Does this answers your question ? (and sorry for the long delay)

**Comment by adityagnrao** [comment]
facing the same issue with extraHosts as well.
```
<properties>
    ...
    <hostname.webip.pairs>localhost:127.0.0.1</hostname.webip.pairs>
</properties>
<extraHosts>
    ${hostname.webip.pairs}
</extraHosts>
```

Failed to execute goal io.fabric8:docker-maven-plugin:0.23.0:build (default-cli) on project ...: Unable to parse configuration of mojo io.fabric8:docker-maven-plugin:0.23.0:build for parameter extraHosts: Cannot assign configuration entry 'extraHosts' with value 'localhost:127.0.0.1' of type java.lang.String to property of type java.util.List -> [Help 1]

**Comment by rhuss** [comment]
@adityagnrao So adding an extra element like `<host>` for the list elements does work for you then, too ?

going to close this issue, but feel to reopen if this doesn't help.
