### ISSUE TITLE
how to get docker:build to display its stdout and stderror

### ISSUE THREAD

**Issue by dantran** [fabric8io/docker-maven-plugin#668]
I hope this is the right place to ask this kind of question

**Comment by tazjin** [comment]
I'm wondering about the same thing, have you figured this out?

**Comment by dantran** [comment]
not yet

**Comment by rhuss** [comment]
You should use `-Ddocker.verbose` when running `mvn docker:build`

**Comment by tazjin** [comment]
Wonderful, thanks @rhuss!

Now that you've mentioned it I found the corresponding bits of the docs though, never found it before because I kept searching for terms like `output` or `stdout`.

**Comment by rhuss** [comment]
happy that it works for you. I will add "output" and "stdout" to the description for `verbose` (so that you find it next time ;-)
