### ISSUE TITLE
not execute maven next phase when run docker success

### ISSUE THREAD

**Issue by karamata** [fabric8io/docker-maven-plugin#691]
I just want to redeploy to my build own tomcat docker, it is bkit07/library-edinnova-tomcat7-mysql

But when I execute command line mvn install -P test-with-docker, it wait for a long time on line

my process flow is build docker, then start docker, then redeploy web app to docker then run test

please help!

```
[INFO] --- docker-maven-plugin:0.19.0:run (build-docker) @ core.library.edinnova ---
[INFO] DOCKER> [bkit07/library-edinnova-tomcat7-mysql:0.0.1-SNAPSHOT]: Start container 47676edc5ba1
```

Not execute next step **redeploy** 

```
<profile>
			<id>test-with-docker</id>
			<build>
				<plugins>
					<plugin>
						<groupId>io.fabric8</groupId>
						<artifactId>docker-maven-plugin</artifactId>
						<version>0.19.0</version>
						<configuration>
							<images>
								<image>
									<name>bkit07/library-edinnova-tomcat7-mysql:${project.version}</name>
									<run>
										<ports>
											<port>9006:2211</port>
											<port>9007:8080</port>
											<port>9008:80</port>
										</ports>
										<log>
											<enabled>false</enabled>
										</log>
									</run>
									<build>
										<dockerFileDir>${project.basedir}/docker</dockerFileDir>
									</build>
								</image>
							</images>
						</configuration>
						<executions>
							<execution>
								<id>build-docker</id>
								<phase>validate</phase>
								<goals>
									<goal>build</goal>
									<goal>run</goal>
								</goals>
							</execution>
							<execution>
								<id>stop-docker</id>
								<phase>install</phase>
								<goals>
									<goal>stop</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.tomcat.maven</groupId>
						<artifactId>tomcat7-maven-plugin</artifactId>
						<version>2.2</version>
						<configuration>
							<path>/</path>
							<uriEncoding>UTF-8</uriEncoding>
							<url>http://localhost:9007/manager/text</url>
							<username>disable_user</username>
							<password>XXXXXX</password>
						</configuration>
						<executions>
							<execution>
								<id>deploy-tomcat</id>
								<phase>process-test-classes</phase>
								<goals>
									<goal>redeploy</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
```

**Comment by rhuss** [comment]
You should use the goal 'start' not 'run' to bind it into the execution. `docker:run` runs in the foreground and makes only sense when used interactively where you want to stop the container with CTRL-C. This is the same semantics as for "tomcat start" and "tomcat run"

**Comment by janssk1** [comment]
AFAIK, the run goal must be used to mimic running a container in foreground (docker run without -d)
However, when using run, it never stops,  not even when the container has ended. 

What i'm trying to do is run two containers in sequence: Run container A, wait for it to finish and then run container B. Is there another way to achieve this?

**Comment by rhuss** [comment]
@janssk1 yes, you can use a `<wait>` in the first container and a `<dependsOn>first</dependsOn>` for the second. You can wait on various conditions, the easiest is to wait on some log output of the first container.

Please refer to https://dmp.fabric8.io/#start-wait for the details. If you don't mind I close this ticket, feel free to reopen in case.

**Comment by janssk1** [comment]
Wait kind of works. It does have a drawback though. The wait will wait until a condition happens (like log output) or a timeout happens. Even if the container stops, wait keeps waiting. That is a little weird. I'm using a 'healthy' condition and the plugin keeps waiting for the container to become healthy, even after is has been shutdown (due to eg a wrong configuration).
