### ISSUE TITLE
Build fails on image names with more than three path elements

### ISSUE THREAD

**Issue by jbonevich** [fabric8io/docker-maven-plugin#694]
### Description
If my docker image has more than three path elements (e.g. "some.docker.repository.com/user/path1/path2/path3/my-test-image"), I get the following error:

```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.19.0:build (build) on project docker-fabric8-test: Execution build of goal io.fabric8:docker-maven-plugin:0.19.0:build failed: Given repository name 'some.docker.repository.com/user/path1/path2/path3/my-test-image:latest' is invalid:
[ERROR] * image part 'path1/path2/path3/my-test-image' doesn't match allowed pattern '(?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])(?:(?:\.(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]))+)?(?::[0-9]+)?/)?[a-z0-9]+(?:(?:[._]|__|[-]*)[a-z0-9]+)*(?:/[a-z0-9]+(?:(?:[._]|__|[-]*)[a-z0-9]+)*)?'
[ERROR] See http://bit.ly/docker_image_format for more details
```
Note that the regex above seems to support an optional host name 

     ('(?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])(?:(?:\.(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]))+)?(?::[0-9]+)?/)?') 

followed by a single name component, followed by an optional slash and single name component.  I do not understand the use of the host name component, but that would match 'path1/' in my example; the single component would match 'path2', and the optional slash-and-name component matches '/path3'.  The match then fails on the trailing '/my-test-image.

I have tested building an image with this name from the docker command line with success.  I ran my example with an image name of 'some.docker.repository.com/user/path1/path2/my-test-image' and it runs successfully.

Also, please note that the link to http://bit.ly/docker_image_format is dead.

### Info

* d-m-p version : 0.19.0
* Maven version (`mvn -v`) : 
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /Users/bonevij/maven
Java version: 1.8.0_72, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
```
* Docker version :
Docker version 1.12.6, build 78d1802
* If it's a bug, how to reproduce :
Create a POM file with the docker-maven-plugin and image name with three or more path elements after a repository and user name and before the image element.

* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by jbonevich** [comment]
Content of my pom.xml:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.thermofisher.cloud</groupId>
    <artifactId>docker-fabric8-test</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <build>
        <plugins>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.19.0</version>
                <configuration>
                    <images>
                        <image>
                            <name>some.docker.repository.com/user/path1/path2/path3/my-test-image</name>
                            <build>
                                <dockerFileDir>.</dockerFileDir>
                            </build>
                        </image>
                    </images>
                </configuration>
                <executions>
                    <execution>
                        <id>build</id>
                        <goals>
                            <goal>build</goal>
                        </goals>
                        <phase>install</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>

Content of src/main/docker/Dockerfile:
FROM alpine
ENV HOME /root
WORKDIR /root
CMD ["bash"]

**Comment by rhuss** [comment]
It could be that Docker changed the regexp for new versions of Docker, I have to verify this.

However the regular expression above does allow only a fixed number of element in the format <registry>/<user>/<image>:<tag> with all of them being optional, and <image> as the only mandatory component must match `[a-z0-9]+` (so no additional `/` allowed here). 

I will verify whether this is still the proper regexp for the latest Docker versions and also fix the link to the documentation.

**Comment by rhuss** [comment]
You are right [multiple segments](https://github.com/docker/docker/blob/04da4041757370fb6f85510c8977c5a18ddae380/vendor/github.com/docker/distribution/reference/regexp.go#L56) in the name are allowed these days. Going to fix this.
