### ISSUE TITLE
Docker RUN command(s) via properties {Question}

### ISSUE THREAD

**Issue by GKTheOne** [fabric8io/docker-maven-plugin#695]
I've got an image build that is your basic jar -> image package, nothing fancy, so it's done using the external properties (type properties) way of specifying the build.

One of the things it now requires is to run as a non-root user. Which means I need to add a RUN command to create the user account.

How can I do this using the properties approach?

I attempted a shotgun style approach after my initial attempts failed by using the following properties, but they don't work either.

```
<docker.run.0/>
<docker.runCmds.run.0/>
<docker.runcmds.run.0/>
<docker.runCmd.0/>
<docker.runcmd.0/>
<docker.runCmds.0/>
<docker.runcmds.0/>

<docker.run/>
<docker.runCmds.run/>
<docker.runcmds.run/>
<docker.runCmd/>
<docker.runcmd/>
<docker.runCmds/>
<docker.runcmds/>
```

**Comment by rhuss** [comment]
It's 

```
<docker.run.0>adduser blub</docker.run.0>
```

but you already tried that. Could you provide a larger example where I could reproduce this ?

**Comment by GKTheOne** [comment]
Try this: (Sorry for the delay)
[docker-run.zip](https://github.com/fabric8io/docker-maven-plugin/files/991432/docker-run.zip)

Using this project I get the following Dockerfile, without the run command.
```
FROM centos:7
MAINTAINER noreply@place.net
COPY maven /app/
WORKDIR /app
CMD java \
            -jar /app/bin/docker-run-via-props-1.0-SNAPSHOT.jar Testing
ENTRYPOINT
USER testuser
```

**Comment by GKTheOne** [comment]
n/a
