### ISSUE TITLE
How to include additional files?

### ISSUE THREAD

**Issue by cesartl** [fabric8io/docker-maven-plugin#697]
### Description
I'm using d-m-p without a Dockerfile to build docker image for my project. So far I was directly using the java command in my entry point to start my app:

```
<entryPoint>
    <exec>
        <arg>java</arg>
        <arg>-Xmx400m</arg>
        <arg>-Djava.security.egd=file:/dev/./urandom</arg>
        <arg>-jar</arg>
        <arg>/app/${project.build.finalName}.jar</arg>
    </exec>
</entryPoint>
```

Now I would like to add a script that waits for another service to be ready:

```
<entryPoint>
    <exec>
        <arg>./wait-for-config-server.sh</arg>
        <arg>java</arg>
        <arg>-Xmx400m</arg>
        <arg>-Djava.security.egd=file:/dev/./urandom</arg>
        <arg>-jar</arg>
        <arg>/app/${project.build.finalName}.jar</arg>
    </exec>
</entryPoint>
```

The `wait-for-config-server.sh` file is at the root of my maven project. I tried to include it using the assembly configuration but with no success:

```
<assembly>
    <mode>dir</mode>
    <inline>
        <files>
            <file>
                <source>wait-for-config-server.sh</source>
                <outputDirectory>/</outputDirectory>
                <filtered>true</filtered>
            </file>
        </files>
    </inline>
</assembly>
```

How can I simply add a file to my Docker image like I would with a `COPY` command in my Dockerfile?

### Info

* d-m-p version : 0.14.2
* Maven version (`mvn -v`) : 
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.3", arch: "x86_64", family: "mac"
```

**Comment by cesartl** [comment]
Actually I realised that I already add an assembly tag.

```
<assembly>
    <basedir>/app</basedir>
    <descriptorRef>artifact</descriptorRef>
</assembly>
```

If I add another assembly tag with my file I can see them being copied on the image when I look inside but it overrides the first assembly and the `app` folder is gone

```
<assembly>
    <basedir>/scripts</basedir>
    <inline>
        <files>
            <file>
                <source>wait-for-it.sh</source>
            </file>
            <file>
                <source>wait-for-config-server.sh</source>
            </file>
        </files>
    </inline>
</assembly>
```


How can I add both the artifact and my files?

**Comment by rhuss** [comment]
Yes, you can only use either a `descriptorRef`, `descriptor` or `inline`, so I suggest that you add the content of this descriptorRef [aritfact](https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/resources/assemblies/artifact.xml) in your inline configuration or move everything into an external descriptor file.

However, I doubt that this will work as you expect, because when you specify 

```xml
<entryPoint>
    <exec>
        <arg>./wait-for-config-server.sh</arg>
        <arg>java</arg>
        <arg>-Xmx400m</arg>
        <arg>-Djava.security.egd=file:/dev/./urandom</arg>
        <arg>-jar</arg>
        <arg>/app/${project.build.finalName}.jar</arg>
    </exec>
</entryPoint>
``` 

then only `./wait-for-config-server.sh` will be called with the rest as arguments to the shell script. In this case you should use the shell form, e.g. something like

```xml
<entryPoint>
    <shell>
       ./wait-for-config-server.sh &amp;&amp; java -Xmx400m -Djava.security.egd=file:/dev/./urandom -jar /app/${project.build.finalName}.jar
    </shell>
</entryPoint>
```

or even better put everything in a single shell script (wait + startup) with providing the jar file name as argument.

**Comment by cesartl** [comment]
Thanks @rhuss 

I did

```
<assembly>
    <basedir>/app</basedir>
    <inline>
        <dependencySets>
            <dependencySet>
                <useProjectArtifact>true</useProjectArtifact>
                <includes>
                    <include>${project.groupId}:${project.artifactId}</include>
                </includes>
                <outputFileNameMapping>
                    ${project.build.finalName}.${artifact.extension}
                </outputFileNameMapping>
            </dependencySet>
        </dependencySets>
        <files>
            <file>
                <source>wait-for-it.sh</source>
                <fileMode>777</fileMode>
            </file>
            <file>
                <source>wait-for-config-server.sh</source>
                <fileMode>777</fileMode>
            </file>
        </files>
    </inline>
</assembly>
```
 and it worked fine.

Actually the entry point is what I wanted :) it passes the argument to my `wait-for-config-server.sh` script which runs the rest of the arguments if the config server is ready
