### ISSUE TITLE
Missing context

### ISSUE THREAD

**Issue by fpezzati** [fabric8io/docker-maven-plugin#705]
### Description
Hello, I am new to Docker and this maven-docke-plugin, I think this is a great tool but I am facing an issue. I want to deploy a .war, YoOffer.war, into a jboss/wildfly image. My image build configuration uses `<dockerFile>` and `<dockerFileDir>`. `<dockerFile>` tells what to copy and where, `<dockerFileDir>` is set to ${project.baseDir}. Dockerfile expect to copy my .war by /target dir and /target should be in the context, but maven complains there is no /target/YoOffer.war in context. 

### Info
[https://github.com/fpezzati/Yomoka/blob/no-compose-but-dockerfiles/YoOffer/pom.xml](project's pom)

* d-m-p version : 0.19.0
* Maven version (`mvn -v`) : 3.3.9
I am running Docker by Toolbox on a Windows7 64-bit machine.
* Docker version : 1.12.5
* If it's a bug, how to reproduce : mvn docker:build
* Sample project : *[https://github.com/fpezzati/Yomoka.git]*

**Comment by rhuss** [comment]
Sorry, but I probably don't understand your question and what you mean with "context". 

As explained in https://dmp.fabric8.io/#docker:build you must only use one of `dockerFile` and `dockerFileDir` (they both point to the Docker context directory). If you use `dockerFile` the context is simply the directory which the Dockerfile is in. 

A solution would be to put your Dockerfile into `${project.baseDir}` (using `.docker_ignore` to include the `target/docker` or even better use an assembly within the configuration to be more flexible in matching your generated artefacts.

There will be more support for the plain Dockerfile mode e.g. like replacing properties or referencing an assembly, these efforts are tracked in #205 .

**Comment by fpezzati** [comment]
Hello Roland, I misunderstood docs for sure. I did the test you suggests and plugin runs. What I miss was that you cannot use both <dockerFile> and <dockerFileDir> together. Thank you for your answer.
