### ISSUE TITLE
Add Wait-Support for docker 2.12 HEALTHCHECK

### ISSUE THREAD

**Issue by danielwegener** [fabric8io/docker-maven-plugin#709]
* d-m-p version : 0.19.0
* Maven version (`mvn -v`) : 3.3.9 (any)
* Docker version : 1.13.0

* If it's a feature request, what is your use case :
d-m-p introduces support for the HEALTHCHECK (see #594) in d-m-p build but has no effect in d-m-p run. It would be great to have a similar mechanism like docker compose `depends_on` `condition: service_healthy` (see https://docs.docker.com/compose/compose-file/#/dependson) to delegate the actual healthy checking to the docker engine.

One option would be a "wait" command "healthy" that waits until the started container becomes healthy according to the docker host status.

**Comment by rhuss** [comment]
Agreed that its sounds like a good addition and it makes much sense for having such a wait condition.
