### ISSUE TITLE
Subsequent images cannot access dynamic port properties

### ISSUE THREAD

**Issue by who** [fabric8io/docker-maven-plugin#710]
### Description
When using the dynamic `<host.port>:80` style of port mapping in an image, the property populated with the dynamic port is not available in subsequent `<image><run>*` blocks, even if `dependsOn` is set. 

This seems to contradict the documentation here: https://dmp.fabric8.io/#start-port-mapping
>If the [<host.port>] property is undefined when the start task executes, a port will be dynamically selected by Docker in the ephemeral port range and assigned to the property which may then be used later in the same POM file.

### Info
* Docker version: `1.11.2, build b9f10c9`
* d-m-p version : 0.19.0
* Maven version (`mvn -v`) : 3.3

### Pom.xml repro

```
<groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.19.0</version>
                <configuration>
                    <showLogs>true</showLogs>
                    <autoCreateCustomNetworks>true</autoCreateCustomNetworks>
                    <watchInterval>500</watchInterval>
                    <logDate>default</logDate>
                    <verbose>true</verbose>
                    <startParallel>false</startParallel>
                    <images>
                    <image>
                        <alias>webserver</alias>
                        <name>nginx</name>
                        <run>
                            <network>
                                <name>test-network</name>
                                <alias>box1</alias>
                            </network>
                            <ports>
                                <port>foo:80</port>
                            </ports>
                            <wait>
                                <time>1000</time>
                                <tcp>
                                    <ports>
                                        <port>80</port>
                                    </ports>
                                    <mode>mapped</mode>
                                </tcp>
                            </wait>
                        </run>
                    </image>
                    <image>
                        <alias>webserver-tester</alias>
                        <name>busybox</name>
                        <run>
                            <network>
                                <name>test-network</name>
                                <alias>webserver-tester</alias>
                            </network>
                            <dependsOn>
                                <dependsOn>webserver</dependsOn>
                            </dependsOn>
                            <cmd>
                                <exec>
                                    <args>sh</args>
                                    <args>-c</args>
                                    <args>echo "Dynamic port: "${foo}; tail -f /dev/null</args>
                                </exec>
                            </cmd>
                            <wait>
                                <log>Dynamic port: \d</log>
                            </wait>
                        </run>
                    </image>
                    </images>
                </configuration>
```

Actual Output:

```
[INFO] --- docker-maven-plugin:0.19.0:start (default-cli) @ docker-maven-plugin-bugdemo1 ---
[INFO] DOCKER> [nginx] "webserver": Start container fd18c02f20f4
[INFO] DOCKER> [nginx] "webserver": Waiting for mapped ports [32782] on host localhost
[INFO] DOCKER> [nginx] "webserver": Waited on tcp port '[localhost/127.0.0.1:32782]' 3 ms
[INFO] DOCKER> [busybox] "webserver-tester": Start container 25622ac9301a
10:40:53.813 webserver-tester> Dynamic port:
[ERROR] DOCKER> [busybox] "webserver-tester": Timeout after 10003 ms while waiting on log out 'Dynamic port: \d'
[ERROR] DOCKER> Error occurred during container startup, shutting down...
[INFO] DOCKER> [busybox] "webserver-tester": Stop and removed container 25622ac9301a after 0 ms
[INFO] DOCKER> [nginx] "webserver": Stop and removed container fd18c02f20f4 after 0 ms
```

**Comment by rhuss** [comment]
Yes, thats true because the configuration must be resolved before the first container is started. Thi sis done by Maven itself before it hands over the configuration to the plugin.

However port mapped vars are only available after the container are started and can be used only in subsequent step (like when running integration tests against the app running in the container).

You can still use custom networks to link container together, but you wont be able to inject the externally mapped port into a running container.

But maybe you can elaborate a bit on the use case why you would need this property accessible from within the container ?

**Comment by who** [comment]
Here is the use case that I am trying to replicate:

1. run a memcached container on a custom network with a dynamic port mapping 
2. run a mysql container on a custom network with dynamic port mapping
3. run a java application on `<net>host</host>` that connects to memcached and mysql on the specified dynamic ports

**Comment by rhuss** [comment]
If I understand right, than the Java app in 3. is running also in a container. So why not using a custom network used by all three containers and you java app uses a fixed port access both services (which can be access via name thanks to Docker's internal DNS. Alternative: Use predefined env vars). They could still map their ports to the outside for outside usage on the bridged interface.

**Comment by who** [comment]
Thanks for the recommendation for a work-around. I wanted to run the java app on --net=host, but running it inside the docker network, combined with port mapping, is an acceptable alternative. Thanks @rhuss !
