### ISSUE TITLE
Empty build config created accidentally

### ISSUE THREAD

**Issue by rhuss** [fabric8io/docker-maven-plugin#714]
### Description

It seems, that when using a configuration of the structure

```xml
<images>
  <image>
     <run>...</run>
  </image>
  <image>
      <build>...</build>
      <run>...</run>
</images>
```

then when using `docker:build` also for the first image an image is created with an empty busybox, effectively overwriting any already pulled image. When one turns around the order of the images, this doesn't happens.

Reported by @ppatierno

**Comment by rhuss** [comment]
@ppatierno sorry, I can't reproduce this anymore. Do you have your sample project somewhere handy ?

**Comment by ppatierno** [comment]
Hi @rhuss,
I haven't a simple project but I had the problem with the Eclipse Hono project here : 
https://github.com/eclipse/hono

The "tests" folder is where there is the pom.xml file where I needed to change the order to have it running. You should first run mvn install -Pbuild-docker-image command from the root folder "hono" in order to have all the needed built images on your local PC. Then you can try the mvn verify -Prun-tests under the "tests" folder.

**Comment by rhuss** [comment]
@ppatierno thanks, I could reproduce the issue. Now its time to fix it :)

**Comment by rhuss** [comment]
@ppatierno actual, it's in fact not really a d-m-p issue but an issue of your configuration in hono ;-)

In your parent pom.xml you defined a pluginManagement section for [d-m-p](https://github.com/eclipse/hono/blob/master/pom.xml#L152-L170)

```xml
       <plugin>
          <groupId>io.fabric8</groupId>
          <artifactId>docker-maven-plugin</artifactId>
          <version>${docker-maven-plugin.version}</version>
          <configuration>
            <images>
              <image>
                <name>eclipsehono/${image.target}</name>
                <build>
                  <tags>
                    <tag>latest</tag>
                    <tag>${project.version}</tag>
                    <tag>${timestamp}</tag>
                  </tags>
                </build>
              </image>
            </images>
          </configuration>
        </plugin>
```

This implies that all your *first* image definitions get this `<build>` section merged in. So, if you put the router in the first position, then it will get this more or less naked `<build>` section and so tries to build the image.

You should probably remove this here and tag the images individually.

If you dont mind I'll close this issue since its not reall a d-m-p issue (but a Maven config issue)
