### ISSUE TITLE
Travis-ci for building docker images

### ISSUE THREAD

**Issue by gadieichhorn** [fabric8io/docker-maven-plugin#721]
Hi,

this is not directly related to an issue, I wonder if you tried using the plugin for generating images on travis-ci? I saw you use it to build and test the plugin. 
1. is it possible to only use the plugin to generate the docker file?
2. travis provide a docker host so I can directly use the docker file to create images
3. would the run / wait section work on travis?

thanks.

**Comment by rhuss** [comment]
Yes, you can use the plugin directly against the Docker daemon of travis and every feature should be supported, including run and wait. 

However, not tested it yet. If you try would love to hear, whether it works for you :)

**Comment by gadieichhorn** [comment]
Thanks for the quick respond
Nicely done! :)

https://travis-ci.org/effectus-io/effectus-demo/jobs/203110639

I switched the machine off like this:

              <configuration>
                            <skipMachine>true</skipMachine>
               </configuration>

Thanks!

**Comment by rhuss** [comment]
awesome, looks good. Happy testing .... ;-)
