### ISSUE TITLE
fail to build and deploy 

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/docker-maven-plugin#731]
The docker maven plugin is unable to build and deploy the maven project when the ~/.docker/config.json has `auths` entries without any auth credentials.

Ref: https://github.com/fabric8io/fabric8-maven-plugin/issues/868

**Comment by rhuss** [comment]
This bug is related to https://github.com/fabric8io/docker-maven-plugin/issues/534#issuecomment-289543186 and https://github.com/fabric8io/fabric8-maven-plugin/issues/901

This needs to be fixed in dmp which I will do for 0.20.1 which is supposed to come out tomorrow.
