### ISSUE TITLE
Using compose, the image is not built anymore

### ISSUE THREAD

**Issue by GurvanLd** [fabric8io/docker-maven-plugin#734]
### Description
I have a maven war project building also docker image.
For IT's I want to use a docker-compose.yml, so I used the "external" setup
Consequence is that the image is not built anymore, just silence :
```
[INFO] --- docker-maven-plugin:0.20.0:build (build-image) @ my-component ---
[INFO] 
[INFO] --- docker-maven-plugin:0.20.0:stop (build-image) @ my-component ---
[INFO] 
[INFO] --- docker-maven-plugin:0.20.0:start (run-image) @ my-component --- 
```
I also opened in [stackoverflow](http://stackoverflow.com/questions/42806310/using-compose-in-fabric8io-docker-maven-plugin-deactivates-image-build) 

### Info

* d-m-p version : 0.20.0
* Maven version: 3.3.9
* Docker version : 1.12.6, build 78d1802
* docker-compose version 1.10.1, build b252738
* how to reproduce : Create a maven project type war, with this setup:
```
     <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.20.0</version>
        <configuration>
          <showLogs>true</showLogs>
          <images>
            <image>
              <name>${docker.image.name}</name>
              <alias>${project.artifactId}-${timestamp}</alias>
              <build>
                <dockerFile>${docker.dockerfile}</dockerFile>
              </build>
               </image>
              </images>
            </configuration>
            <executions>
              <execution>
                <id>build-image</id>
                <goals>
                  <goal>build</goal>
                  <goal>stop</goal>
                </goals>
                <phase>pre-integration-test</phase>
              </execution>
              <execution>
                <id>run-image</id>
                <goals>
                  <goal>start</goal>
                </goals>
                <phase>pre-integration-test</phase>
              </execution>
              <execution>
                <id>stop-image</id>
                <goals>
                  <goal>stop</goal>
                </goals>
                <phase>post-integration-test</phase>
              </execution>
            </executions>
          </plugin>
```
-> Works 
Then add in image section :
```
              <external>
                <type>compose</type>
                <basedir>src/main/docker</basedir>
                <composeFile>docker-compose.yml</composeFile>
              </external>
```

-> The image is no more built

**Comment by GurvanLd** [comment]
Does anyone use same kind of project setup, is it working ?

**Comment by GurvanLd** [comment]
In BuildMojo there is 

`            if (buildConfig != null) {
               System.out.println("Build confi si : " + buildConfig.toString());
                if (buildConfig.skip()) {
                   System.out.println(imageConfig.getDescription() + ": Skipped building");
                } else {
                    buildAndTag(hub, imageConfig);
                }
            }`
I am definitely getting into the "else" so "BuildConfiguration" has either not been initialized or set ?

**Comment by rhuss** [comment]
Can you post your compose file please ?

**Comment by GurvanLd** [comment]
`version: '2'
services: 
  my-container:
     image: my-image-name
     ports:
        - "8088:8080"
        - "8448:8443"
     volumes:
        - /myproject/target/docker-logs:/usr/local/tomcat/logs
`

**Comment by GurvanLd** [comment]
I am diggin into th eplugin, so it looks like the image an dit's BuildConfiguration are initialized in DockerComposeConfigHandler class in method "createBuildImageConfiguration"<br>
There it can not be null:
        BuildImageConfiguration buildConfig = imageConfig.getBuildConfiguration();
But when doing what seems like same call in BuildMojo, it's null .

**Comment by GurvanLd** [comment]
I see when building the sample/docker-compose-demo, docker-compose file does not set "image" name for jolokia-war service.
I applied the same and it looks like working now.
So for running the image we just built we use alias of the image for service name in compose file, and we don't put image name ?

**Comment by jssbbonilla** [comment]
Im starting with all of this but  it seems to be working for me with this:
`  <build>
        <plugins>
        <plugin>
            <groupId>io.fabric8</groupId>
            <artifactId>docker-maven-plugin</artifactId>
            <extensions>true</extensions>
            <configuration>
                <images>
                    <image>
                        <external>
                            <type>compose</type>
                            <basedir>../../../docker/</basedir>
                            <composeFile>docker-compose.yml</composeFile>
                        </external>
                    </image>
                </images>
            </configuration>
            <executions>
                <execution>
                    <id>start</id>
                    <phase>pre-integration-test</phase>
                    <goals>
                        
                        <goal>build</goal>
                        <goal>start</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
    </build>`
But also i need some help......with this plugin names of container are random....is there a way to solve that? i need specific names .... the container_name in compose is not working for this

**Comment by ianpojman** [comment]
Having the same issue. I managed to get it (mostly) doing what I want by overriding the configurations in the executions, which is a little confusing/verbose/non-ideal, but assuming this works it'll be an acceptable workaround for me:

```
   <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.21.0</version>

                <configuration>
                    <verbose>true</verbose>
                    <images>
                        <image>
                            <name>$COMPANY.com/$APP:latest</name>
                            <alias>$APP-war</alias>
                            <build>
                                <!--<filter>@</filter>-->
                                <dockerFileDir>${project.basedir}/src/main/docker</dockerFileDir>
                                <assembly>
                                    <descriptorRef>artifact</descriptorRef>
                                </assembly>
                            </build>
                        </image>
                    </images>
                </configuration>

                <executions>
                    <execution>
                        <id>docker-compose-start</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>build</goal>
                            <goal>start</goal>
                        </goals>

                        <configuration>
                            <skipBuild>false</skipBuild>
                            <verbose>true</verbose>
                            <images>
                                <image>
                                    <external>
                                        <type>compose</type>
                                        <basedir>src/main/docker</basedir>
                                        <composeFile>${project.basedir}/target/classes/docker-compose.yml</composeFile> 
                                    </external>
                                </image>
                            </images>
                        </configuration>
                    </execution>
                    <execution>
                        <id>docker-compose-stop</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                        <configuration>
                            <images>
                                <image>
                                    <external>
                                        <type>compose</type>
                                        <basedir>src/main/docker</basedir>
                                        <composeFile>${project.basedir}/target/classes/docker-compose.yml
                                        </composeFile> 
                                    </external>
                                </image>
                            </images>
                        </configuration>
                    </execution>
                    <execution>
                        <id>docker-build</id>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by rhuss** [comment]
Thanks for the workaround but agreed, that does not look so nice. I dont think its hard to fix, it just like that my backlog is simply too large. If you are fance investigating the issue, I would happily can guide you and review a pull request.

**Comment by dezer32** [comment]
Found a solution. Suddenly someone come in handy.

If you mention an alias from pom.xml in docker-compose (e.g. ports), then everything is build.

**Comment by rhuss** [comment]
👍 good to know. I'm so free and close this issue for now. If someone wants to pick this up to provide a proper fix, happy to support a PR for integration in dmp.

Thanks !
