### ISSUE TITLE
Always output version in the built image name in the console about from the build goal

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/docker-maven-plugin#737]
I am using d-m-p 0.20.0 and when I build a docker image with a hardcoded name (without version)
```
            <image>
              <name>camelinaction/spring-docker</name>
              <build>
                <from>openjdk:latest</from>
```

Then the console logs
```
[INFO] DOCKER> docker-build.tar: Created [camelinaction/spring-docker] in 2 seconds
```

It does not show the version which would be `latest` as there was no version specified.

I wonder if the plugin should not output this so the end-user always see the entire coordinate of the built image, eg it should log
```
[INFO] DOCKER> docker-build.tar: Created [camelinaction/spring-docker:latest] in 2 seconds
```

**Comment by rhuss** [comment]
Actually, if there would be provided a tag != 'latest' it would be shown here, too. Also, in the Docker world _no tag_ always means _latest_ and in fact, the name send to the Docker daemon is without `latest` in this case. If you would have specified `<name>camelinaction/spring-docker:latest</name>`, it would have shown the `:latest` here, too (it simplies puts out the name of the image).

But I agreed, let's be more specific here (although it might hinder debugging a bit as it is not the name you have configured, but shouldn't harm here)
