### ISSUE TITLE
docker:volume-remove should not fail the build if the volume is not found

### ISSUE THREAD

**Issue by KedneckInc** [fabric8io/docker-maven-plugin#763]
### Description

Docker:volume-remove mapped to maven lifecycle 'clean' fails the build if the volume cannot be found.

Since the purpose of 'volume-remove' is to simply remove the given volume, if it's already gone, there's no reason to fail the build.

Unfortunately, there doesn't seem to be any flag or setting that will stop the plugin from failing the build.

### Info

* d-m-p version : 0.20.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_121/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-514.10.2.el7.x86_64", arch: "amd64", family: "unix"
```
* Docker version : 17.03.0-ce, build 60ccb22
* If it's a bug, how to reproduce :

I'd call it a bug, but you might think of it as a feature request.  Either way...

Create a simple pom.xml including something like the following

```
...
     <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <extensions>true</extensions>
        <executions>
          <execution>
            <id>volume-cleanup</id>
            <phase>clean</phase>
            <goals><goal>volume-remove</goal></goals>
          </execution>
          <execution>
            <id>volume</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>volume-create</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <verbose>true</verbose>

          <!-- For volume-create -->
          <volumes>
            <volume>
              <name>gcssj-config</name>
              <driver>local</driver>
            </volume>
          </volumes>
...
```
Run `mvn clean` on an already clean project with no volume.  Boom.

* If it's a feature request, what is your use case :

1. Consider binding the volume-clean step to the 'initialize' phase to guarantee that the volume is rebuilt every time.

1. Consider the standard `mvn clean install`, which will fail every time because 'volume-clean' fails when the volume isn't present.

**Comment by rhuss** [comment]
I agree with you that we should be more conservative here and make `fabric8:volume-remove` a no-op when the volume does not exist.

Fancy of sending a PR for this ?

**Comment by KedneckInc** [comment]
I sorta thought I had.  What did I miss?

**Comment by rhuss** [comment]
@KedneckInc Sorry, can't find it. Which PR do you refer to ?

**Comment by KedneckInc** [comment]
Oh!  PR = pull request.  I was thinking PR = problem report.  Sorry.  I'll
look into it.  Life's been a bit busy lately.

**Comment by KedneckInc** [comment]
Ok, it's a simplistic fix, but it will work.

**Comment by rhuss** [comment]
Thanks ;-) I will check this later today.

**Comment by KedneckInc** [comment]
Anything?

**Comment by rhuss** [comment]
I think so, so I'm going to close this isssue. @KedneckInc feel free to re-open if this is not the case.

**Comment by KedneckInc** [comment]
Many Thanks!  I'm sorry I took so long to respond, but this did indeed fix the problem.  Now our developers don't have to manually clean up the old volumes!
