### ISSUE TITLE
Option dockerFile doesn't work

### ISSUE THREAD

**Issue by realmfoo** [fabric8io/docker-maven-plugin#784]
Option *dockerFile* stopped working after #777.

### Info

* d-m-p version : 0.21.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.10.0-20-generic", arch: "amd64", family: "unix"
```
* Docker version : 17.03.1-ce
* If it's a bug, how to reproduce :

```
<dockerFile>MyDockerfile</dockerFile>
```

results in
```
Cannot locate specified Dockerfile: MyDockerfile (Internal Server Error: 500) [Cannot locate specified Dockerfile: MyDockerfile (Internal Server Error: 500)]
```

See: https://github.com/fabric8io/docker-maven-plugin/pull/777#commitcomment-22209514

@rhuss

**Comment by rhuss** [comment]
Where have you put your Dockerfile ? In src/main/docker ?

**Comment by rhuss** [comment]
@realmfoo Just tested it here and it works for me. A fully reproducible example would be awesome.

**Comment by realmfoo** [comment]
@rhuss 
An example with commands to reproduce an error:
https://github.com/realmfoo/dmp-784

**Comment by rhuss** [comment]
Thanks, I will investigate the issue today.
