### ISSUE TITLE
Question: Is docker optimise similar to what docker-squash does?

### ISSUE THREAD

**Issue by gnanasundar** [fabric8io/docker-maven-plugin#785]
I'm trying to reduce the size of my docker image. Is setting optimise to true similar to what docker-squash does?

Would there be a squash option in the future?

**Comment by rhuss** [comment]
`optimise` only concatenates all `RUN` command to a single layer (with the usual `&&` trick). Currently, there is nothing like a `squash` and tbh it is not yet planned.

However, we are happy for any pull request and would help to integrate them into the plugin. If you are fancy for doing a PR we can discuss this and look how to add this best.

**Comment by dexterhu** [comment]
https://github.com/fabric8io/docker-maven-plugin/pull/1366/commits
