### ISSUE TITLE
Mirai DDOS Trojan found in unix executable '[' within busybox-image.tar.gz

### ISSUE THREAD

**Issue by evangates** [fabric8io/docker-maven-plugin#795]
### Description
Trojan found in unix "[" executable nested within busybox-image.tar.gz

### Info
Gmail and virustotal.com find the Mirai DDOS trojan in the src/test/resources/integration/busybox-image.tar.gz from this commit: https://github.com/fabric8io/docker-maven-plugin/commit/4ddbcae5f34b9f680692995a34ddb8eee0ce575a

Virustotal reports:
master branch zip:
https://www.virustotal.com/en/file/f38f1979877f5b526bf0a5b59669b9902d9c0868f106221de4ca7cfc1d19df68/analysis/
busybox-image.tar.gz:
https://www.virustotal.com/en/file/f9c054aed3337aee120957630e58bb7775d66077ff4b65924ef089fec5450411/analysis/
layer.tar (within busybox-image.tar.gz):
https://www.virustotal.com/en/file/e88b3f82283bc59d5e0df427c824e9f95557e661fcb0ea15fb0fb6f97760f9d9/analysis/
infected file within layer.tar (the [ utility):
https://www.virustotal.com/en/file/1a81f6f324037758127689a0d69d63c084513c1562bc042acb79b057e417d8df/analysis/

* d-m-p version :
everything since commit: https://github.com/fabric8io/docker-maven-plugin/commit/4ddbcae5f34b9f680692995a34ddb8eee0ce575a

* If it's a bug, how to reproduce :
Scan with virustotal.com.  It'll tell you which individual scanners find the trojan.  Or attempt to email the files with gmail.

**Comment by rhuss** [comment]
Thanks a lot for the finding ! Doh, I need to be more careful with binary parts in PR @Katsuya-Tomioka heads up, might be that your system is affected, too.

This image archive (included since version 0.20.1) is used in an integration test only and is removed immediately after the test again. The image was also never executed and only used for testing the image save / load feature of d-m-p.

This means it is *not* part of any released Maven artefact. So I consider the impact  low.

What I did right now:

* Replaced `busybox-image.tar.gz` with a clean test image.
* Removed the tar archive from the GitHub repository by rewriting the history.

However, it is still available in any cloned forked out there. *It is highly recommended to either re-fork again or at least rebase against master !!*.

Here are the steps performed to remove it from Git history:

```
git clone --mirror git@github.com:fabric8io/docker-maven-plugin.git
java -jar bfg-1.12.15.jar --delete-files busybox-image.tar.gz docker-maven-plugin.git
cd docker-maven-plugin.git
git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push
```

**Comment by Katsuya-Tomioka** [comment]
Thanks for letting me know, @rhuss.

**Comment by rhuss** [comment]
@Katsuya-Tomioka do you know how you created this image which you added for you integration test? Did you a `save` on an existing image in your Docker daemon? And where did it come from?  `would be really interesting to find out how the Troyan image travels through the world ... ;-)

**Comment by rhuss** [comment]
See https://groups.google.com/forum/#!topic/fabric8/STp_bObsSFM for the mailing list announcement about this issue.

@evangates thanks again for this awesome discovery. How did you found it ? Do you run regularly security checks on your tooling ?

**Comment by Katsuya-Tomioka** [comment]
I'm pretty sure that's from https://hub.docker.com/_/busybox/ (as my usual sanity check) and save from a local docker. I'm trying to track this. Sorry about this!

**Comment by Katsuya-Tomioka** [comment]
Looks like the issue has been fixed in busybox:1.26.1 (https://hub.docker.com/r/library/busybox/tags/). I see the same results from the scan up to the version. Guessing from the date I committed, I think the archive I uploaded is around 1.25.0.

**Comment by rhuss** [comment]
@Katsuya-Tomioka Thanks a lot for the investigation. Wonder whether @docker is aware of this? // @thajeztah

**Comment by rhuss** [comment]
Found out that it is exactly 1.25.1 which contains the Trojan (although the Docer scan at https://hub.docker.com/r/library/busybox/tags/1.25.1/ hasn't found anything).

Try:

```
docker pull busybox:1.25.1
docker save busybox:1.25.1 -o busybox.tar
```

then upload to `busybox.tar` to virustotal.com: 

![screen shot 2017-06-11 at 08 59 48](https://user-images.githubusercontent.com/99080/27009082-f8e78ff6-4e84-11e7-8497-7816679dfdc5.png)

**Comment by Katsuya-Tomioka** [comment]
Sent a note to security@docker just in case.

**Comment by rhuss** [comment]
Seems to be a false positive, according to https://github.com/docker-library/busybox/issues/29#issuecomment-307694768
