### ISSUE TITLE
naming containers

### ISSUE THREAD

**Issue by josephkhafaji** [fabric8io/docker-maven-plugin#797]
Hi,

This is more of a question than an issue. I've been looking around the documentation for a way to explicitly name the containers that we start using the plugin. Is there any support for passing down the name of the containers that we would like to create, something that corresponds to docker's `--name` option.

Cheers,

**Comment by rhuss** [comment]
Use `<alias>` for the container name and a `<namingStrategy>alias</namingStrategy>` in the `<run>` section. Check dmp.fabric8.io for more details.
