### ISSUE TITLE
Always have image tag with the project.version

### ISSUE THREAD

**Issue by meggarr** [fabric8io/docker-maven-plugin#799]
### Description
When we are working with Docker registry provided by Nexus for release, the registry disabled the "redeploy", so every image with the same version/tag can only be pushed once.

But the `docker-maven-plugin` always generate the tag with the POM's project version. E.g. the POM is version 1.0, and with a continuous build number as 8, I specify the tag with
```
<tags>
  <tag>${project.version}.${build.number}</tag>
</tags>
```
The plugin always generates two tags `1.0` and `1.0.8`, and tries to push both to registry. Apparently the push of `1.0` must fail, since it's already pushed to registry together with previous builds, like `1.0.1`.

I think it needs a way to disable the default tag of `project.version`, so I can specify only the intended tags.

### Info

* d-m-p version : 0.20.1
* Maven version (`mvn -v`) : 3.0.5
* Docker version : 1.12.6

**Comment by rhuss** [comment]
Agreed that there should be a way to fully control which tags are created. Sounds like a bug to me.

**Comment by meggarr** [comment]
May I ask when can this be resolved? @rhuss

**Comment by rhuss** [comment]
Sorry, I'm currently quite busy. But it looks like this is also related to #140 . We always have the default tag which is the same as the name of the image. 

So one solution could be to use this tag directly in the `<name>` of your image of your image configuration an omit the tags sections:

```xml
<image>
   <name>myimage:${project.version}.${build.number}</name>
   ...
</image>
```

Does this work for you ?

**Comment by meggarr** [comment]
Yes, the workaround seems working, I will use that temporarily.. Thanks.

**Comment by rhuss** [comment]
Cool. Actually, after some thoughts, I wonder whether this shouldn't be considered even a _proper_ solution, not only a workaround. This would be obviously perfectly backwards compatible and afais supports any use case.

**Comment by rhuss** [comment]
What I mean is, you _have_ full control of what tags are created: The one in the image name (always) plus optionally any tags provided in `<tags>`. Maybe one should clarify this a bit in the documentation though.

**Comment by meggarr** [comment]
Yep, I agree with that. The tag with the name is (always) the default/formal tag, and tags in `<tags>` element are optional and can be skipped via `-Ddocker.skip.tag=true` in `mvn` command line. So my solution is like
```
<name>myimage:${project.version}.${build.number}</name>
<build>
  <tags>
    <tag>latest</tag>
  </tags>
</build
```
When it can only have one tag, `docker.skip.tag=true` is in command line. Thanks!

**Comment by rhuss** [comment]
cool. I'm going to close the issue, feel free to reopen it if there is still something to do.

**Comment by meggarr** [comment]
@rhuss maybe I find another issue, when I tried to build and push in single command,
```
 mvn clean package docker:build docker:push -Ddocker.push.registry=<my-registry> -Ddocker.skip.tag=true
```
it tries to push the tags even they are _skipped_ in build. It looks _push_ does not respect `docker.skip.tag=true`. Is it a bug?

**Comment by meggarr** [comment]
#869
