### ISSUE TITLE
Could't save image

### ISSUE THREAD

**Issue by YuriyTymchiy** [fabric8io/docker-maven-plugin#802]
_Please fill out the following information to help us in analyzing the issue, but feel free to skip it if you don't have the information at hand or if it does not apply. Please remove everything which does not apply to the issue. Including this info paragraph ;-)_

### Description
I want to save existing Docker image to tar.

I got : DOCKER> More than one image with build configuration is defined. Please specify the image with 'docker.name' or 'docker.alias'.
I also tried to add images section to execution but got the same error
Here is my pom:
```
		<profile>
			<id>minimal-pack</id>
			<build>
				<plugins>
					<plugin>
						<groupId>io.fabric8</groupId>
						<artifactId>docker-maven-plugin</artifactId>
						<version>0.21.0</version>
						<configuration>
							<images>
								<image>
									<name>web_idc</name>
									<run></run>
								</image>
							</images>
						</configuration>
						<executions>
							<execution>
								<id>save-database</id>
								<phase>install</phase>
								<goals>
									<goal>save</goal>
								</goals>
								<configuration>
									<filter>web_idc</filter>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
```

### Info

* d-m-p version : 0.21.0
* Maven version (`mvn -v`) : 3.3.9
```

```
* Docker version : 1.12.2
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rhuss** [comment]
It seems that your build configuration contains several image configurations, but you can only save a single image. So you need to specify the image you want to export with the mentioned properties.

You can check the effective pom.xml  with `mvn help:effective-pom`. It could be that you inherit some configuration from a parent etc.

**Comment by YuriyTymchiy** [comment]
Solved. In image definition section must be goal 'build' not 'run' :
```
<configuration>
  <images>
		<image>
			<name>web_idc</name>
			<build></build>
		</image>
</images>
</configuration>
```
Could you please notice that in documentation - this is very hard to find!!

**Comment by rhuss** [comment]
Ah, ok. got it. You want to save an existing image. Don't really understand the use case but I completely agree that the error message is misleading and will fix it.

If you are fine with it, i'd like to close this issue. feel free to reopen it in case.
