### ISSUE TITLE
Support docker credential store

### ISSUE THREAD

**Issue by denisa** [fabric8io/docker-maven-plugin#806]
Docker has recently introduced the concept of a credential store.
With a credential store, docker saves the credentials in a platform specific safe place, such as macOS keychain.

For example, my ~/.docker/config.json looks like:
```
{
    "auths": {
        "https://index.docker.io/v1/": {},
        "https://us.gcr.io": {},
        "us.gcr.io": {}
    },
    "credsStore": "osxkeychain"
}
```
Clean & safe.

However, this doesn't work with version 0.21.0 of the plugin, as it only supports having credential in clear text in that file.

[Docker documentation for the credential store](https://docs.docker.com/engine/reference/commandline/login/)

**Comment by rhuss** [comment]
Sounds like a reasonable addition the plugin, thanks for the heads up. If you feel fancy and might want to contribute and could give you some pointers for where to start. 

Otherwise it might take a bit unti we pick up this feature, we are all currently quite busy otherwise.

**Comment by denisa** [comment]
fair ;-)

From the [instruction](https://github.com/docker/docker-credential-helpers), the helper must be on $PATH and be called with a `get` argument and the desired server on STDIN.

Example:
```
> echo "us.gcr.io" | docker-credential-osxkeychain get
{"ServerURL":"us.gcr.io","Username":"oauth2accesstoken","Secret":"… my secret key …"}
```

**Comment by denisa** [comment]
It seems like docker now also supports credHelpers as an alternative to credsStore, to specify per-registry helpers, see https://github.com/moby/moby/pull/25851

I will look into adding to existing merge request.

**Comment by denisa** [comment]
This is the default behavior of any recent docker installation of docker for mac. This feature is thus important to support the ‘fall-back to docker credentials’ mode of the plugin.

**Comment by rhuss** [comment]
Support has been added.
