### ISSUE TITLE
image.build.assembly.name builder does not exist in configuration class

### ISSUE THREAD

**Issue by ObukhovMG** [fabric8io/docker-maven-plugin#808]
_Please fill out the following information to help us in analyzing the issue, but feel free to skip it if you don't have the information at hand or if it does not apply. Please remove everything which does not apply to the issue. Including this info paragraph ;-)_

### Description
When i try to define image.build.assembly.name in my pom, i get an exception.
But doc tells that this option is available and valid.

Unable to parse configuration of mojo io.fabric8:docker-maven-plugin:0.20.1:build for parameter name: Cannot find 'name' in class io.fabric8.maven.docker.config.AssemblyConfiguration

### Info

* d-m-p version :
* Maven version (`mvn -v`) :
```

```
* Docker version :
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rhuss** [comment]
"name" is only available since version 0.21.0 as mentioned in https://github.com/fabric8io/docker-maven-plugin/blob/master/doc/changelog.md

**Comment by ObukhovMG** [comment]
Thx, omg, too much updates, you know.

**Comment by rhuss** [comment]
np ;-)
