### ISSUE TITLE
mvn clean install failure

### ISSUE THREAD

**Issue by sgangapa** [fabric8io/docker-maven-plugin#817]
_Please fill out the following information to help us in analyzing the issue, but feel free to skip it if you don't have the information at hand or if it does not apply. Please remove everything which does not apply to the issue. Including this info paragraph ;-)_

### Info

* d-m-p version :
* Maven version (`mvn -v`) :
```

```
* Docker version :
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
This does not make any sense to me. Please provide a minimal, complete and verifiable example
