### ISSUE TITLE
Update the required version of docker-compose in DockerComposeConfigHandler to be 2.1

### ISSUE THREAD

**Issue by jimusbobus** [fabric8io/docker-maven-plugin#818]
### Description
Update the required version of docker-compose in DockerComposeConfigHandler to be 2.1

### Info
Updating this would allow docker compose to use the healthcheck option

* d-m-p version : 0.21.0
* Maven version (`mvn -v`) : apache-maven-3.0.5
```

Having multiple containers start up with a dependency chain fails.  This is solved with the healthcheck.

Maybe a simple update of :

    private void validateVersion(Map<String, Object> compose, File file) {
        Object version = compose.get("version");
        if (version == null || !version.toString().trim().equals("2")) {
            throw new ExternalConfigHandlerException("Only version 2 of the docker-compose format is supported for " + file);
        }
    }

to

    private void validateVersion(Map<String, Object> compose, File file) {
        Object version = compose.get("version");
        if (version == null || !version.toString().trim().equals("2.1")) {
            throw new ExternalConfigHandlerException("Only version 2.1 of the docker-compose format is supported for " + file);
        }
    }

would help lots.

Many Thanks

**Comment by rhuss** [comment]
Good point. Maybe even a 'startsWith' is better here to support all of the 2.x variants ?

Fancy to do a pull request ?

**Comment by jimusbobus** [comment]
I'd like to try :) i've never done one before so would need to work out how etc, give me a few days to try!

**Comment by jimusbobus** [comment]
well that was easier than expected :) pull request created.

**Comment by rhuss** [comment]
np, just ask if you have some questions ;-)

thanks !

**Comment by jimusbobus** [comment]
is using DockerComposeConfigHandler to test this blocked?

// Moved temporarily to resources/META-INF/plexus/components.xml because of https://github.com/codehaus-plexus/plexus-containers/issues/4

**Comment by rhuss** [comment]
Not really sure about your question.

But since this change is minimal I don't insist on a test (feel free to try it nevertheless ;-).

Let's merge this for now.

[merge]

**Comment by marty30** [comment]
I think this update broke my build as I am using 'version 2', and that does not start with '2.'. It appears that somebody (@jthoenes) already tried to fix this in https://github.com/fabric8io/docker-maven-plugin/commit/57ff272b3f3c9409b5af844aaf57d8a6459cf3b7 but I think that this is breaking every bui;d as it will always return true.
