### ISSUE TITLE
Setting up the plugin (dockerHost - general configuration) 

### ISSUE THREAD

**Issue by leonBeis** [fabric8io/docker-maven-plugin#822]
I am using Docker for windows(with the default MobyLinuxVM as the base for my linux containers).
In this case does the plugin uses windows-based npipe:////./pipe/docker_engine as docker-host or 
 the linux based unix:///var/run/docker.sock (since the vm I use is mobylinux afterall) and is it automatically set or should I explicitly set it if I just use the docker for windows default?

**Comment by rhuss** [comment]
Its detected automatically, but you can override it by setting docker.host property. See documentation on "dockerHost" in https://dmp.fabric8.io/#global-configuration

Hope this answers your question, feel free to reopen this issue if not.
