### ISSUE TITLE
docker-maven-plugin neo4j

### ISSUE THREAD

**Issue by Artgit** [fabric8io/docker-maven-plugin#823]
I want to launch Neo4j database at Docker container for my IT tests.

This is a command I use to start Neo4j container from cmd:

`docker start --name=neo4j-test1 --publish=7474:7474 --publish=7687:7687 --env NEO4J_AUTH=neo4j/neo4j1 neo4j:3.2.1`

I also need to configure this with a docker-maven-plugin. This is my attempt:

```
			<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.21.0</version>
				<executions>
					<execution>
						<id>prepare-neo4j-database</id>
						<phase>pre-integration-test</phase>
						<goals>
							<goal>start</goal>
						</goals>
						<configuration>
							<images>
								<image>
									<name>neo4j:${neo4j.version}</name>
									<alias>neo4j-database</alias>
									<run>
										<env>
											<NEO4J_AUTH>neo4j/neo4j1</NEO4J_AUTH>
										</env>
										<ports>
											<port>neo4j-database:7474</port>
											<port>neo4j-database:7687</port>
										</ports>
										<wait>
											<http>
												<url>http://${docker.host.address}:7474/browser</url>
											</http>
											<log>Starting...</log>
											<time>20000</time>
										</wait>
									</run>
								</image>
							</images>
						</configuration>
					</execution>
					<execution>
						<id>remove-neo4j-database</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>stop</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```
but this configuration doesn't work right now. Could you please help to create a correct configuration for docker-maven-plugin?

**Comment by rhuss** [comment]
On a first glimpse there are some issues with the port mapping. You instruct the plugin to dynamically map port 7474 and 7687 to random ports and assign them to Maven properties which then can be used later (e.g. in the http check). First, this should be two different property names, of course. Second you should use `${neo4j-database}` instead of 7474 in the wait check.

See also the documentation on port-mapping at https://dmp.fabric8.io

**Comment by Artgit** [comment]
Thanks for your answer. I have fixed port checking with ${neo4j-database}.

Could you please show how to fix the config with ports ? I can't find a way to do it myself right now :(

**Comment by Artgit** [comment]
What is the correct place in plugin configuration to provide `-Dfile.encoding=UTF-8` ?

**Comment by rhuss** [comment]
its within a top-level properties section:

```xml
<properties>
  <file.encoding>utf-8</file.encoding>
</properties>
```

**Comment by rhuss** [comment]
wdym with wait is not working ? Could you please provide some log output ?

**Comment by Artgit** [comment]
wait condition works fine now. 

This is my current plugin neo4j config:

```
			<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.21.0</version>
				<executions>
					<execution>
						<id>prepare-neo4j-database</id>
						<phase>pre-integration-test</phase>
						<goals>
							<goal>start</goal>
						</goals>
						<configuration>
							<images>
								<image>
									<name>neo4j:${neo4j.version}</name>
									<alias>neo4j-database</alias>
									<run>
										<env>
											<NEO4J_AUTH>${neo4j.username}/${neo4j.password}</NEO4J_AUTH>
											<NEO4J_dbms_memory_pagecache_size>2G</NEO4J_dbms_memory_pagecache_size>
											<NEO4J_dbms_memory_heap_maxSize>2G</NEO4J_dbms_memory_heap_maxSize>
										</env>
										<ports>
											<port>${neo4j.http.port}:7474</port>
											<port>${neo4j.bolt.port}:7687</port>
										</ports>
										<wait>
											<http>
												<url>http://${docker.host.address}:${neo4j.http.port}/browser</url>
											</http>
											<time>60000</time>
										</wait>
									</run>
								</image>
							</images>
						</configuration>
					</execution>
					<execution>
						<id>remove-neo4j-database</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>stop</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```



But 

```
<properties>
  <file.encoding>utf-8</file.encoding>
</properties>
```

doesn't work

Everythin works fine only with the following command:

`mvn clean install -Dfile.encoding=UTF-8 `

Is there any way to avoid `-Dfile.encoding=UTF-8 ` in the params and provide it within pom.xml to be able to run only `mvn clean install `?

**Comment by akroch1** [comment]
according to the following neo4j Docker documentation [2.5.7. User-defined procedures](http://neo4j.com/docs/operations-manual/current/installation/docker/#docker-procedures) in order to provide Neo4j instance with a 3rdparty plugins I have to add the following parameters to my docker command:

`--volume=$HOME/neo4j/plugins:/plugins`

Could you please how to extend the configuration of my docker-maven-plugin in order to support this functionality ? Also, what is the $HOME folder ?

**Comment by Artgit** [comment]
according to the following neo4j Docker documentation [2.5.7. User-defined procedures](http://neo4j.com/docs/operations-manual/current/installation/docker/#docker-procedures) in order to provide Neo4j instance with a 3rdparty plugins I have to add the following parameters to my docker command:

`--volume=$HOME/neo4j/plugins:/plugins`

Could you please show how to extend the configuration of my docker-maven-plugin(mentioned in the my post above) in order to support this functionality ? Also, what is the $HOME folder ?

**Comment by Artgit** [comment]
Created a following question for Docker share Windows 10 issue https://stackoverflow.com/questions/45289390/neo4j-and-fabric8io-docker-maven-plugin

**Comment by rhuss** [comment]
* As `$HOME` is mentioned in the neo4j docs, its no way how I can tell you from a d-m-p perspective.
* The file.encoding specification might go differently. Please check the internet, its a pure Maven question which is easy to find.
* How to handle volumes are described in the documentation: https://dmp.fabric8.io/#start-volumes
* Cannot help much with specific Docker for Windows issues which seems to be unrelated to d-m-p, you would get this error with plain docker usage, too.

If you don't mind I'm going to close the issue. Feel free to reopen it, if you think there are still issues with this plugin. Also, feel free to visit us in the #fabric8 channel on freenode.
