### ISSUE TITLE
 docker-maven-plugin and docker:start

### ISSUE THREAD

**Issue by Artgit** [fabric8io/docker-maven-plugin#825]
As it's described at the following topic https://github.com/fabric8io/docker-maven-plugin/issues/823 I have successfully configured Neo4j with docker-maven-plugin Container starts correctly during the build for pre-integration-test Maven phase.

Right now I'd like to be able to spin up the containers via Maven docker-maven-plugin to be able to test my code on demand.

I tried to use the following command:

mvn docker:start

but container doesn't start with no errors and BUILD SUCCESS.

How to correctly start the containers via Maven docker-maven-plugin command ?

**Comment by rhuss** [comment]
As explained in the documentation the `docker:start` starts the container in the background, `docker:run` in the foreground.

**Comment by Artgit** [comment]
I tried `docker:run`

It just hangs and that's it, output:

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building domain 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- docker-maven-plugin:0.21.0:run (default-cli) @ domain ---
```

**Comment by rhuss** [comment]
In the example posted you put image configuration only to the execution binding and will hence only be evaluated when called when called indirectly as bound goal.

Just move the `<configuration>` out of `<executions>`, top-level directly below `<plugin>`.

**Comment by Artgit** [comment]
Thanks, now everything is working fine. Thanks for your help and this awesome plugin and sorry for my silly questions!

**Comment by rhuss** [comment]
Perfect
