### ISSUE TITLE
Only version 2.X of the docker-compose format is supported

### ISSUE THREAD

**Issue by hrishin** [fabric8io/docker-maven-plugin#829]
### Description 
https://github.com/fabric8io/docker-maven-plugin/blob/master/samples/docker-compose/src/main/docker/docker-compose.yml file is having following version number
```
version: "2"
```
When we run the example it logs following message
`Only version 2.X of the docker-compose format is supported for xxx/docker-compose file`
 
Is it  desired behavior or bug?

### Info

* d-m-p version : 0.21
* Maven version (`mvn -v`) :
```
Apache Maven 3.3.9 (NON-CANONICAL_2016-07-01T11:53:38Z_mockbuild; 2016-07-01T17:23:38+05:30)
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-1.b12.fc25.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.11.10-200.fc25.x86_64", arch: "amd64", family: "unix"
```
* Docker version : 1.12.6, build ae7d637/1.12.6
* If it's a bug, how to reproduce : mvn docker:build
* Sample project : *https://github.com/fabric8io/docker-maven-plugin/blob/master/samples/docker-compose/*

**Comment by jthoenes** [comment]
Found a workaround. Set the version to "2.2" and it works for now.

**Comment by jimusbobus** [comment]
@jthoenes  do you mean set the version in 2.2 in the docker-compose.yml file or somewhere else?

**Comment by jthoenes** [comment]
@jimusbobus yes, exactly in the docker-compose.yml file
