### ISSUE TITLE
shmSize support in external configuration with system property

### ISSUE THREAD

**Issue by aiannucci** [fabric8io/docker-maven-plugin#840]
### Info

* d-m-p version : 0.21.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T16:39:06-03:00)
Maven home: /usr/local/apache-maven/apache-maven-3.5.0
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
```
* Docker version : 17.06

Currently it seems to be ignoring when you set the property as <docker.shmSize>
If you can point me to which could be the problem, I can send a PR

**Comment by rhuss** [comment]
Actually, it's `docker.shmsize` (mind the case). Does this work for you ? I will add it to the documentation as it seems to be missing there.

**Comment by aiannucci** [comment]
It worked with all lowercase. I sent PR with the fix.
Thank you!
