### ISSUE TITLE
Out of memory exception when waiting for a log line at container startup

### ISSUE THREAD

**Issue by eduramiba** [fabric8io/docker-maven-plugin#844]
### Description

Out of memory exception when waiting for a log line at container startup

### Info

If the logs returned by the docker daemon are really big, this can cause an out of memory error since the buffer is allocated with the whole log size at once, without any size check: https://github.com/fabric8io/docker-maven-plugin/blob/452c0bdee6df063cfda9327c4086ea4ec552006e/src/main/java/io/fabric8/maven/docker/access/log/LogRequestor.java#L174

Data should be read with a fixed size buffer, chunk by chunk.

**Comment by eduramiba** [comment]
```java
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
at io.fabric8.maven.docker.access.log.LogRequestor.readStreamFrame(LogRequestor.java:174)
at io.fabric8.maven.docker.access.log.LogRequestor.parseResponse(LogRequestor.java:194)
at io.fabric8.maven.docker.access.log.LogRequestor.run(LogRequestor.java:108)
```

**Comment by rhuss** [comment]
Do you a use a multiline match regexp (i.e. with (?s) option) ? If so, the whole log needs to be read in. 

If you dont provide this option, logs are read line by line and should not exhaust your heap memory.

Could you post your setup please ?

thanks ...

**Comment by eduramiba** [comment]
Hi,
We don't use multi line matchers, I think there must be a very long line for some reason in the computer where this happens (a Jenkins agent).

**Comment by rhuss** [comment]
Oh, that must have been a super long line (many MBs worth). I wonder whether this is a corner case or whether we should invest the effort to buffer this. This will be a hard job, because the regexp configured here are supposed to match a single line, so in order to apply the regexp we need this line.

But maybe we do something wrong with line endings ?

would be aswesome if we could be able to reproduce this issue.

**Comment by eduramiba** [comment]
Well a solution would be to limit read lines to a maximum length and only match that length.
We can try to implement this and open a pull request.

**Comment by rhuss** [comment]
yes, would be awesome. thanks !

**Comment by eduramiba** [comment]
Hi,
So this was an issue with the jenkins docker default config using systemd for logging, which gives "From log: configured logging reader does not support reading" response and makes this crash.

Using the log driver configuration fixes it:
```xml
<driver>
   <name>
    <!-- Make sure default docker logging mode is used -->
    json-file
  </name>
</driver>
```
