### ISSUE TITLE
configuration->images->image->build->assembly->targetDir not working despite no dockerfile

### ISSUE THREAD

**Issue by adam66** [fabric8io/docker-maven-plugin#865]
### Info

The docs say that `targetDir` defines where the artifact is included, but I can't get the plugin to accept my value, which is `/` or the root. 

I've tried both `<targetDir></targetDir>` and `<targetDir>/</targetDir>`

It ignores the setting and places the jar in the `/maven/` directory like this:

`[INFO] DOCKER> Step 2/5 : COPY maven /maven/`

I see in the docs there's a comment that the `targetDir` is ignored when a `Dockerfile` is in use, but in this case there isn't.

I can work around this by declaring `<name>/</name>` which gives me 

`[INFO] DOCKER> Step 2/5 : COPY / ///`

and the jar ends up in root.

Took me a while to discover that. I assume this would be instantly reproducible in any project. Here's my XML:

```
           <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <configuration>
                    <logStdout>true</logStdout>
                    <outputDirectory>target/docker-build</outputDirectory>
                    <verbose>true</verbose>
                    <images>
                        <image>
                            <name>${gem.docker.registry}/tardis/tardis</name>
                            <build>
                                <tags>
                                    <tag>latest</tag>
                                    <tag>${git.branch}-${project.version}</tag>
                                    <tag>${git.branch}-latest</tag>
                                </tags>
                                <entryPoint>
                                    <exec>
                                        <arg>java</arg>
                                        <arg>-Dlogging.file=/logs/tardis.log</arg>
                                        <arg>-Djava.security.auth.login.config=/config/login.conf</arg>
                                        <arg>-Djava.security.krb5.conf=/config/krb5.conf</arg>
                                        <arg>-jar</arg>
                                        <arg>tardis.jar</arg>
                                    </exec>
                                </entryPoint>
                                <from>frolvlad/alpine-oraclejdk8:slim</from>
                                <volumes>
                                    <volume>/tmp</volume>
                                </volumes>
                                <runCmds>
                                    <run>mkdir /logs</run>
                                </runCmds>
                                <assembly>
                                    <targetDir></targetDir>
                                    <inline>
                                        <files>
                                            <file>
                                                <source>${project.build.directory}/${build.finalName}.${project.packaging}</source>
                                                <outputDirectory>/</outputDirectory>
                                                <destName>tardis.jar</destName>
                                            </file>
                                        </files>
                                        <fileSet>
                                            <directory>${project.build.directory}/config</directory>
                                            <outputDirectory>/config</outputDirectory>
                                        </fileSet>
                                    </inline>
                                </assembly>
                            </build>
                        </image>
                    </images>
                </configuration>
            </plugin>
```

* d-m-p version :  0.22.1
* Maven version (`mvn -v`) :  3.3.9
* Docker version : 17.06.2

**Comment by rhuss** [comment]
An empty targetDir means the default (which is `/maven`). Are you sure that `<targetDir>/</targetDir>` does not work ? I ask, because this happened to work for quite some time and if not, its a bug.

**Comment by adam66** [comment]
Yes, quite sure. Sorry. I currently working around it by declaring `<name>/</name>` and it is ignoring `<targetDir>/</targetDir>`. 

In your docs you mention that the targetDir element is ignored when there is a Dockerfile present - perhaps that is where the problem lies.

If you've got anything you want me to try, let me know, but I can't see how I can simplify it any more than it is. I'm just trying out this stuff for the first time.

**Comment by rhuss** [comment]
Could you please provide a simple example ? Using a name `/` does not sound valid (actually I would expect the plugin to error here as this is not a valid Docker name)

**Comment by adam66** [comment]
Yes, it's an ugly hack! 👎 

The zip has got all the extra IntelliJ stuff in it - I am just assuming it's nothing to do with the problem. 

The git-commit-id-plugin also works fine locally without any real git repo in existence. 

[docker-plugin-bug.zip](https://github.com/fabric8io/docker-maven-plugin/files/1310443/docker-plugin-bug.zip)

**Comment by rhuss** [comment]
You mapping were simply a bit off. I fixed it with this:

```xml
                               <assembly>
                                    <targetDir>/</targetDir>
                                    <inline>
                                        <files>
                                            <file>
                                                <source>${project.build.directory}/${build.finalName}.${project.packaging}</source>
                                                <outputDirectory>.</outputDirectory>
                                                <destName>test.jar</destName>
                                            </file>
                                        </files>
                                        <fileSet>
                                            <directory>${project.build.directory}/classes/config</directory>
                                            <outputDirectory>config</outputDirectory>
                                            <includes>
                                                <include>**/login.conf</include>
                                                <include>**/krb5.conf</include>
                                            </includes>
                                        </fileSet>
                                    </inline>
                                </assembly>
```

* `targetDir` to `/`
* All other output pathes should be relative
* You config mapping was faulty:
   - The config filres are copied to `target/classes` as they are in src/main/resources.
   - `config` was mentioned twice: In `include` and in the `directory`
* No need to give the assembly a null name.

The snippet above works for me when running `mvn package`.

Does it work for you, too ?

**Comment by adam66** [comment]
No - the result I have an issue with is that the docker-build.tar ends up with the artifact tardis.jar in a subdir 'maven'. I need to put it into the root, with no dir.

**Comment by adam66** [comment]
Right! Sorry, I'm new to docker. I thought that tar image was the same as the final docker image but obviously not. Trying to take shortcuts were there weren't any 👎 

I think what was also concerning me was the directory name 'maven' which just seemed wrong but now I realise it's purely a temporary artifact of the plugin process. 

Thanks for the help.
