### ISSUE TITLE
0.22 Release?

### ISSUE THREAD

**Issue by emetsger** [fabric8io/docker-maven-plugin#886]
Hi folks!

Doing some release planning for a local software project, and right now we have a dependency on `0.22-SNAPSHOT`.  I was wondering what your timing was for releasing `0.22`?  If it isn't in the near future, we would need to perform a release locally.

In the interim, I was also wondering if `0.22-SNAPSHOT` could be pushed to the OSS repo?

Many thanks, great plugin!

**Comment by emetsger** [comment]
In particular, we're interested in #848 being incorporated into the release!

**Comment by rhuss** [comment]
Actually, we already have released 0.22.1, so the next version will be either 0.22.2 or 0.23.0.

Currently quite some PRs has been piled up, and I greatly apologize for not being faster. Day to day works eats me up at the moment, but actually, I hope to review some of the pending PRs and release a new version anytime soon.

I just pushed out a 0.22-SNAPSHOT to Maven central, but if you have any pressure please let me  know, I can cut out a release easily (even when not yet integrated the PRs)

**Comment by rhuss** [comment]
Actually, pushed 0.22-SNAPSHOT to https://oss.sonatype.org/content/repositories/snapshots/  ...

**Comment by emetsger** [comment]
Many thanks @rhuss for the quick response!!  I appreciate the SNAPSHOT push, and the pressures of day-to-day work and life!  A release by the end of this week (or beginning of next) would be ideal, but if that's not feasible, just let me know.  We can roll a local release for time being.  No pressure!

**Comment by paulvi** [comment]
There is already 0.23.0 released. Can this be closed?

**Comment by rhuss** [comment]
yes :)

Thanks for the heads up ....
