### ISSUE TITLE
[BUG] Credentials helpers assumed to return a version number

### ISSUE THREAD

**Issue by giannello** [fabric8io/docker-maven-plugin#896]
### Description
Starting with 0.23, docker-maven-plugin supports docker credential helpers. By default, they are called with the `version` argument to get the plugin version and use it in a log message.
Not all the helpers, however, return a version number when called with the `version` argument (tested with `docker-credential-gcloud` here, part of google-cloud-sdk).

### Info
* d-m-p version: 0.23.0

**Comment by giannello** [comment]
@rhuss any chance to get the PR merged? This bug comes from a wrong assumption about the helpers' behavior, so it makes sense to make the version check optional.

**Comment by rhuss** [comment]
@giannello thanks for the PR, to make a PR integration sweep this weekend (constantly overloaded with 'regular' work at the moment). If I get to it, I will make a new release, too then.

thanks for your contribution ....
