### ISSUE TITLE
[FEATURE] Inherited `image` definitions

### ISSUE THREAD

**Issue by giannello** [fabric8io/docker-maven-plugin#935]
### Description
In case of multiple projects using this plugin, it's pretty difficult to centralize the configuration in a parent POM and reference only the required `image` blocks from child poms (pretty much the way `dependencyManagement` works).
It would be nice to have a section where images can be pre-configured and then simply re-used inside other POMs.
@rhuss we are willing to implement such a feature, would it make sense to have it?

**Comment by rhuss** [comment]
@giannello I see your point, but do you have a concrete use case at hand ? Is it more for the build or run aspect ? 

Actually you can already some extension with Maven inherent mechanism like described in http://blog.sonatype.com/2011/01/maven-how-to-merging-plugin-configuration-in-complex-projects/ with which I came quite far.

So it would be really good to know where this kind of inheritance is not good enough (which could be of course the case).

**Comment by giannello** [comment]
@rhuss we do have a concrete use case. Our microservices are all built using the same maven configuration, where pretty much only some dependencies and versions change between them. We're now working on consolidating also the d-m-p configuration (for both the build and run aspect), as the integration tests for all our service run against similar subsets of images, so having the configuration in a parent pom makes maintenance _much_ easier.
Let's say that our tech stack uses Cassandra, Elasticsearch and Postgres: some services need Cassandra and ES, some others ES and PG, some others all of them.
Configuring everything in the parent POM is - at the moment - not a viable solution, as the POM merge process doesn't guarantee the right output when working with lists of elements. Take the following example:
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>test-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.23.0</version>
                <configuration>
                    <images>
                        <image>
                            <alias>cassandra</alias>
                            <name>cassandra:latest</name>
                            <run>
                                <skip>true</skip>
                            </run>
                        </image>
                        <image>
                            <alias>postgres</alias>
                            <name>postgres:latest</name>
                            <run>
                                <skip>true</skip>
                            </run>
                        </image>
                    </images>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```
This parent POM defines 2 images, both skipped by default. Now we want to override the <skip> parameter for `cassandra` in the child pom
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>test</groupId>
        <artifactId>test-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>test-child</artifactId>
    <packaging>pom</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <configuration>
                    <images>
                        <image>
                            <alias>cassandra</alias>
                            <run>
                                <skip>false</skip>
                            </run>
                        </image>
                    </images>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```
`mvn help:effective-pom` tells us that
```
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.23.0</version>
        <configuration>
          <images>
            <image>
              <alias>cassandra</alias>
              <run>
                <skip>false</skip>
              </run>
              <name>cassandra:latest</name>
            </image>
          </images>
        </configuration>
      </plugin>
```
however, if the order of the images in the parent pom changes
```
                        <image>
                            <alias>postgres</alias>
                            <name>postgres:latest</name>
                            <run>
                                <skip>true</skip>
                            </run>
                        </image>
                        <image>
                            <alias>cassandra</alias>
                            <name>cassandra:latest</name>
                            <run>
                                <skip>true</skip>
                            </run>
                        </image>
```
then the effective POM becomes:
```
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.23.0</version>
        <configuration>
          <images>
            <image>
              <alias>cassandra</alias>
              <run>
                <skip>false</skip>
              </run>
              <name>postgres:latest</name>
            </image>
          </images>
        </configuration>
      </plugin>
```

Relying on the position of the images in the configuration is definitely not something we want to do, as it *will* break at some point.

I see 2 possible solutions here:
* create a `dependencyManagement`-like mechanism, where all the images can be defined in the parent pom and then they need to be explicitely imported in the child pom (using the name or the alias as an ID)
* change the way of declaring the images from using `<image></image>` to using the tag name as the ID (or alias), as following:
Parent pom
```
                    <images>
                        <postgres>
                            <name>postgres:latest</name>
                            <run>
                                <skip>true</skip>
                            </run>
                        </postgres>
                        <cassandra>
                            <name>cassandra:latest</name>
                            <run>
                                <skip>true</skip>
                            </run>
                        </cassandra>
                    </images>
```
Child pom
```
                    <images>
                        <cassandra>
                            <run>
                                <skip>false</skip>
                            </run>
                        </cassandra>
                    </images>
```
Effective pom
```
          <images>
            <cassandra>
              <run>
                <skip>false</skip>
              </run>
              <name>cassandra:latest</name>
            </cassandra>
            <postgres>
              <name>postgres:latest</name>
              <run>
                <skip>true</skip>
              </run>
            </postgres>
          </images>
```

This is probably the easiest solution to implement, but it breaks compatibility with the current way of configuring d-m-p - a compatibility layer should be implemented to take care of that - and I'm not entirely sure how semantically correct this is.

**Comment by rhuss** [comment]
@giannello thanks for the clarification. Actuually I think the best and most intuitive solution would be to implement an own inheritance solution with a correlation key to identify the image configuration to merge. Actually I think the `alias` is the most suitable key for this correlation. 

I mean, when a parent pom declares some configuration for dmp with images that carry aliases, then the child pom can override these definitions when specifying the same alias.

Actually that way, the inherited configuration can only _overwrite_ or _add_ to the parent configuration, but unfortunately not _remove_ (that's why there are 'hack' like the `skip` property for this). 

I'm not sure how well this works with the Maven intrinsic inheritance mechanism as d-m-p only see the already processed configuration. One possibility would be to set `<image combine.self="override">` on the image tags in the child and then go hunting for the parent definitions to do the merge manually, correlated on the `alias`. Not sure if this is easy to achieve, though, as maven is really a beast ;-)

Alternatively I would also be happy to not work with inheritance but with something like a `<dependencyManagement>` as you have original suggested. Again, the correlation could be done via the alias, but the Maven inheritance mechanism would not interfere with our own interpolation. Again, not really sure whether we can achieve this with Maven (maven is a beast when it comes to extensibility, but I guess that's for a good reason. Otherwise it would be gradle and every pom.xml would look differently).

If you still fancy to dive into this, I'm happy to support you and help to integrate a PR.

**Comment by giannello** [comment]
@rhuss life was not nice to the project I was working on, and I completely forgot about this ticket.
As nobody else seem to need this change, I'm closing it.

**Comment by awittha** [comment]
I didn't see this originally, but I do have this use-case, for what it's worth.

I work around the limitations by creating intermediate parent poms that use Maven's `<... combine.self="override">` and `<... combine.children="override">` to ensure that only the relevant definitions are in-scope. Then, you just pick the correct parent pom and you've got your image definitions.

If I had a larger set of image definitions that I needed to work with, or needed to combine them in various (perhaps unknown 'till runtime) ways, this workaround wouldn't work for me. My needs are simple enough that

> Relying on the position of the images in the configuration ...

has been sufficient, as the intermediate poms are "managed" and not exposed to end-users, so they are predictable _enough_.
