### ISSUE TITLE
How can I set ip for container with ip property in fabric8 dmp plugin?

### ISSUE THREAD

**Issue by MSaadatt** [fabric8io/docker-maven-plugin#953]
I try to set static ip for my container with ip property but does not work!

https://dmp.fabric8.io/#docker:start

In this page said that can use ip property to set ip for container in docker start, but I don't know how that works!

I try: `<port>+container.ip.property:host.port:5678</port>`

but I don't want this, I just want to expose container port on internal ip, just like docker command and without port, just expose port in image is enough:

docker run --name new-name --net netwok00 --ip 172.18.0.2 some-container

I don't understand what this page say about ip !

@rhuss Can you help me?

**Comment by MSaadatt** [comment]
Nobody can solve this?!!

**Comment by rhuss** [comment]
Actaly, can you elaborate a bit on your use case ? When you open a port in Docker container it is automatically exposed on the internal IP, nothing special todo here.

If you want to use a custom network (as I might suspect from looking at your docker cli command), you can configure this with [<network>](https://dmp.fabric8.io/#network-configuration).

But maybe you just describe your use case and we might be able to help here.

**Comment by MSaadatt** [comment]
Imagine I want to set static internal ip for container with fabric8 like this command in docker : 

`docker run --name new-name --net netwok00 --ip 172.18.0.2 some-container`

I want my container to always have this ip when it build and runs with fabric8 plugin.

How can I set this configuration in my pom.xml file?

**Comment by rhuss** [comment]
Sorry, thats not supported yet. not sure about the use case either (i.e. why do you require to have a fixed internal IP and dont use any other means of service discovery ?)

**Comment by MSaadatt** [comment]
So, what this table say about ip? I can't understand it!

![capture](https://user-images.githubusercontent.com/22921290/37724509-2e4ee32e-2d46-11e8-927b-0f9498c96b5d.PNG)

**Comment by rhuss** [comment]
It just says that the plugin sets these property automatically for you so that you can reuse it in other parts of the pom.xml. You can't set these properties, they are read-only.

**Comment by MSaadatt** [comment]
So the only way to access my container on a static URL is to publish it on network.
Is it true?

**Comment by rhuss** [comment]
Sorry, would you please mind to describe your use case ? There are many ways how services can be accessed, using a fixed static internal IP is one of the least favorable choices for many reasons (and so not supported by docker-maven-plugin).

**Comment by duchiha** [comment]
Hello, 
if you don't mind i have a similar question, how do i set IP address for my containers ?
I'm trying to set IP in a custom network but it's not working.
Any Help?
