### ISSUE TITLE
how configure can push local image to aliyun?

### ISSUE THREAD

**Issue by chenzhenyang** [fabric8io/docker-maven-plugin#955]
how configure can push local image to aliyun?

怎么配置可以push本地刚打好的镜像到阿里云的容器镜像服务呢？

**Comment by chenzhenyang** [comment]
<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>${docker-maven-plugin.version}</version>
				<configuration>
					<authConfig>
						<username>xxx</username>
						<password>xxxx</password>
					</authConfig>
					<images>
						<image>
							<name>registry.cn-hangzhou.aliyuncs.com/fengxin58/%a:%v</name>
							<registry>registry.cn-hangzhou.aliyuncs.com</registry>
							<build>
								<dockerFileDir>
									${basedir}/src/main/docker
								</dockerFileDir>
								<assembly>
									<descriptorRef>artifact</descriptorRef>
								</assembly>
								<tags>
									<tag>latest</tag>
									<tag>${project.version}</tag>
								</tags>
							</build>
						</image>
					</images>
				</configuration>
			</plugin>

我这么配置之后，提交不上去，看的docker daemon的日志文件，是认证失败，配置的用户名和密码都是对的，用docker login命令登陆之后，使用docker push命令可以push到阿里云。

**Comment by chenzhenyang** [comment]
```
<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>${docker-maven-plugin.version}</version>
				<configuration>
					<authConfig>
						<username>山东丰信农业服务有限公司</username>
						<password>J7nn83cm0243</password>
					</authConfig>
					<images>
						<image>
							<name>registry.cn-hangzhou.aliyuncs.com/fengxin58/%a:%v</name>
							<registry>registry.cn-hangzhou.aliyuncs.com</registry>
							<build>
								<dockerFileDir>
									${basedir}/src/main/docker
								</dockerFileDir>
								<assembly>
									<descriptorRef>artifact</descriptorRef>
								</assembly>
								<tags>
									<tag>latest</tag>
									<tag>${project.version}</tag>
								</tags>
							</build>
						</image>
					</images>
				</configuration>
			</plugin>
```

**Comment by chenzhenyang** [comment]
```
<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>${docker-maven-plugin.version}</version>
				<configuration>
					<authConfig>
						<username>xxxx</username>
						<password>xxxx</password>
					</authConfig>
					<images>
						<image>
							<name>registry.cn-hangzhou.aliyuncs.com/fengxin58/%a:%v</name>
							<registry>registry.cn-hangzhou.aliyuncs.com</registry>
							<build>
								<dockerFileDir>
									${basedir}/src/main/docker
								</dockerFileDir>
								<assembly>
									<descriptorRef>artifact</descriptorRef>
								</assembly>
								<tags>
									<tag>latest</tag>
									<tag>${project.version}</tag>
								</tags>
							</build>
						</image>
					</images>
				</configuration>
			</plugin>
```

**Comment by rhuss** [comment]
Could you please check the reference manual whether it answer your questions ? 
Actually, I don't speak chinese, please in case of an issue, create a new one with an english description, also what goes wrong for you.

Thanks !
