### ISSUE TITLE
Property placeholders are not interpolated when they are the only thing in the XML element value

### ISSUE THREAD

**Issue by aaronjwhiteside** [fabric8io/docker-maven-plugin#960]
### Description

Property interpolation like `${docker.container.<container>.ip}` only seem to work when they are adjacent to other text in the target XML element.

From the sample pom.xml:
`<CONSUL_HTTP_ADDR>${docker.container.consul.ip}:8500</CONSUL_HTTP_ADDR>`
Produces an environment variable of:
`CONSUL_HTTP_ADDR=172.17.0.2:8500` 

However 
`<CONSUL_HTTP_ADDR>${docker.container.consul.ip}</CONSUL_HTTP_ADDR>` 
Just by itself produces an environment variable:
`CONSUL_HTTP_ADDR=` 
When one would expect it to just contain: `CONSUL_HTTP_ADDR=172.17.0.2` 

Also `${docker.container.<container>.ip}` only seems to work when `<link>`ed with the container being referenced. If you comment out the `<links>` in the `consul-test` image, but leave the `<dependsOn>`, `${docker.container.consul.ip}` fails to be interpolated even when other text is present in the xml element.

### Info

* d-m-p version : 0.23.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T00:58:13-07:00)
Maven home: /opt/apache-maven-3.5.2
Java version: 1.8.0_141, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
```
* Docker version :17.12.0-ce

Sample pom.xml to reproduce the problem
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>test</artifactId>
    <packaging>pom</packaging>
    <version>1.0.0-SNAPSHOT</version>

    <build>
        <plugins>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.23.0</version>
                <configuration>
                    <allContainers>true</allContainers>
                    <removeVolumes>true</removeVolumes>
                    <showLogs>true</showLogs>

                    <images>
                        <image>
                            <alias>consul</alias>
                            <name>consul:1.0.6</name>
                            <run>
                                <env>
                                    <CONSUL_BIND_INTERFACE>eth0</CONSUL_BIND_INTERFACE>
                                </env>
                                <wait>
                                    <log>consul: New leader elected</log>
                                    <time>60000</time>
                                </wait>
                            </run>
                        </image>

                        <image>
                            <alias>consul-test</alias>
                            <name>consul:1.0.6</name>
                            <run>
                                <dependsOn>
                                    <container>consul</container>
                                </dependsOn>
                                <links>
                                    <link>consul</link>
                                </links>

                                <env>
                                    <!--suppress MavenModelInspection -->
                                    <!--<CONSUL_HTTP_ADDR>${docker.container.consul.ip}:8500</CONSUL_HTTP_ADDR>-->
                                    <CONSUL_HTTP_ADDR>${docker.container.consul.ip}</CONSUL_HTTP_ADDR>
                                </env>

                                <entrypoint>
                                    <shell>env</shell>
                                </entrypoint>

                                <wait>
                                    <time>60000</time>
                                    <exit>0</exit>
                                </wait>
                            </run>
                        </image>
                    </images>
                </configuration>

                <executions>
                    <!-- Start all the containers -->
                    <execution>
                        <id>start-containers</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>

                    <!-- Stop everything -->
                    <execution>
                        <id>stop-containers</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by rhuss** [comment]
This sounds like an issue in StrSubstitutor as it is used in https://github.com/fabric8io/docker-maven-plugin/blob/674e80fdf56d31fdd263366d53e7a5cf0dc064b3/src/main/java/io/fabric8/maven/docker/access/ContainerCreateConfig.java#L61

The problem with non interpolation of variables could be the startup order of containers, which is fixed when using a dependency like linking containers, but is random when not.

**Comment by aaronjwhiteside** [comment]
Shouldn't `<dependsOn>` be the thing that determines ordering, not `<links>`?

**Comment by rhuss** [comment]
Both imply an order (as you obviously only can link to a running container), and there are even more implicite depdendencies as you can see in https://github.com/fabric8io/docker-maven-plugin/blob/4b16f1243b77ce5e2c2883976feb17b6404996e2/src/main/java/io/fabric8/maven/docker/config/ImageConfiguration.java#L76-L86

**Comment by aaronjwhiteside** [comment]
OK fair enough, makes sense. 

But I would expect that all the properties for a container be available when only `dependsOn` is used... Would you like me to open a separate ticket for this?

**Comment by rhuss** [comment]
Yes, agreed. I think its good enough to have this ticket and fix both issues simultaneously. Unfortunately, I'm quite busy these days, so can't promise when to work on it.

@rohanKanojia would this issue something for you to start with? I don't think its overly complicated and relatively clearly defined. Happy to help of course :)

**Comment by aaronjwhiteside** [comment]
Does this also fix the container ordering issue?
