### ISSUE TITLE
RfE: Add startPeriod to healtCheck

### ISSUE THREAD

**Issue by ascheman** [fabric8io/docker-maven-plugin#961]
Could you please enable setting the healthCheck `start-period`, cf. https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by poikilotherm** [comment]
I think this issue can be closed as done @rhuss @rohanKanojia

**Comment by rohanKanojia** [comment]
Closed via https://github.com/fabric8io/docker-maven-plugin/pull/1022
