### ISSUE TITLE
Disable Windows 10 volume access

### ISSUE THREAD

**Issue by 1605200517** [fabric8io/docker-maven-plugin#967]
Component tries to access drive C: by default if now volumes binding was configured.
Do I have to disable it explicitedly and how?

**Comment by 1605200517** [comment]
See also https://github.com/testcontainers/testcontainers-java/issues/602

**Comment by rhuss** [comment]
Not really sure whether I understand your issue.
Could you please provide an error message and a simple test case (i.e. pom.xml) ?

thanks !

**Comment by 1605200517** [comment]
This is testable only with Windows 10: a simple setup from an example leads to a dialog to allow disk C: access. (I use Docker natively there). For a set of reason's I cannot grant it, so it is not really an error, but an undesired behaviour. If I will be retesting, I will share also the error message. Chances are that is some type of "preflight checks" of a subsystem if it is shared with testcontainers (as referenced there in #602)

**Comment by rhuss** [comment]
If I understand you right, you don't use 'Docker for Windwows' but native Docker on Windows. Sorry for my ignorance, I'm really no Windows user, and when I tested it, it was only with 'Docker for Windows', running with Hyper-V and communicating via named pipes.

**Comment by 1605200517** [comment]
well I'll try my luck with another package, they seem to provide a fix.

**Comment by rhuss** [comment]
@1605200517 ok. would be awesome which package fixes it how, so we might be able to take this over. Also, we are taking pull requests if you are feeling fancy to contribute.

good luck ...
