### ISSUE TITLE
docker:source only takes into account the first image

### ISSUE THREAD

**Issue by pn-santos** [fabric8io/docker-maven-plugin#973]
### Description

I have a config with two images, each with their own build sections. If I run `mvn docker:build` the plugin will correctly build the two images. However if I run `mvn docker:source` then only the first declared image is taken into account.

Not sure if this is intended behavior but I would expect `docker:source` to have the exact same behavior of `docker:build` and create two `docker-build.tar` files (each in their corresponding image dir path).

### Info

* d-m-p version : 0.24.0
* Maven version : 
```
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T08:58:13+01:00)
Maven home: /opt/maven/latest
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /opt/java/jdk1.8.0_151/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.13.0-36-generic", arch: "amd64", family: "unix"
```
* Docker version : 17.12.1-ce
* If it's a bug, how to reproduce :
1) Create a configuration with two images, each with it's own build section (I'm using inline assembly descriptor, not sure if relevant)
2) Run `docker:source` target, only the first image will be taken into account
3) Run `docker:build` target, both images will be built

**Comment by rhuss** [comment]
Actually, there is something missing in the documentation, which needs to be fixed:

There is a configuration parameter `sourceMode` which you can set to:

* `first` --> only the first image is considered for docker:source
* `all` --> all images are considered.


The default mode is `fisrst` so you would have to add

```xml
<configuration>
  <sourceMode>all</sourceMode>
  ....
</configuration>
```

to the plugin configuration.

Does this work for you ?

**Comment by pn-santos** [comment]
That worked! Thanks @rhuss
