### ISSUE TITLE
[question] Building two images within the same pom.xml

### ISSUE THREAD

**Issue by cjdcordeiro** [fabric8io/docker-maven-plugin#977]
### Description

Building two images within the same pom.xml? Is this possible? Basically I want to build two Docker images, for different architecture (thus based on different Docker images), which slightly change on the execution commands.

**Comment by rhuss** [comment]
Yes, this is possible. Just configure two images as described in https://dmp.fabric8.io/#image-configuration and the rest of the manual.

going to close the issue, please reopen if this doesnt answer your question.

**Comment by cjdcordeiro** [comment]
hi @rhuss thanks.

yes that works but that means I need to write another <build> process, where in my case, the two builds just differ in Image name and <from>

**Comment by rhuss** [comment]
You can parameterize your build with properties and profiles if that is what you want to do.
